/* ph_anim_intake.h - generated by ph_intake_anim.py, do not edit
 *
 * "intake": Horner sits on the scanner slab and the machine draws
 * him in.  14.5 s, 8 pose keys, 8 root keys, 4 prop keys.
 *
 * KEYS, not baked frames.  Lerp between them at whatever rate you
 * run at, and smoothstep the parameter - linear on a body this heavy
 * reads mechanical.  Baking this out per-frame at 20 fps would cost
 * ~29 KB; the keys below are under 1 KB.
 *
 * Angles are binary: 0x4000 == 90 degrees.  Order is Z, then Y,
 * then X, matching euler() in ph_rig.py.
 * Zero is the slumped standing pose, NOT a rest pose.
 *
 * PARENTING: from PH_INTAKE_CUE_LIE onward the root translation is
 * in the SLAB's frame - add ph_intake_table's interpolated dz to it,
 * or the machine slides out from under him.
 */
#ifndef PH_ANIM_INTAKE_H
#define PH_ANIM_INTAKE_H

#include "ph_rig.h"

#define PH_INTAKE_FPS        15
#define PH_INTAKE_FRAMES     218
#define PH_INTAKE_POSE_KEYS  8
#define PH_INTAKE_ROOT_KEYS  8
#define PH_INTAKE_TABLE_KEYS 4

typedef struct { u16 frame; s16 rot[PH_JOINT_COUNT][3]; } PhPoseKey;
typedef struct { u16 frame; s16 pos[3]; s16 yaw, pitch; } PhRootKey;
typedef struct { u16 frame; s16 dz; } PhPropKey;

static const PhPoseKey ph_intake_pose[PH_INTAKE_POSE_KEYS] = {
    {   0, {
        {      0,      0,      0},   /* root */
        {      0,      0,      0},   /* spine */
        {      0,      0,      0},   /* chest */
        {      0,      0,      0},   /* neck */
        {      0,      0,      0},   /* head */
        {      0,      0,      0},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,      0},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {      0,      0,      0},   /* hip_R */
        {      0,      0,      0},   /* kne_R */
        {      0,      0,      0},   /* ank_R */
        {      0,      0,      0},   /* hip_L */
        {      0,      0,      0},   /* kne_L */
        {      0,      0,      0},   /* ank_L */
    }},
    {  27, {
        {      0,      0,      0},   /* root */
        {      0,      0,      0},   /* spine */
        {      0,      0,      0},   /* chest */
        {      0,      0,      0},   /* neck */
        {      0,      0,      0},   /* head */
        {      0,      0,      0},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,      0},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {      0,      0,      0},   /* hip_R */
        {      0,      0,      0},   /* kne_R */
        {      0,      0,      0},   /* ank_R */
        {      0,      0,      0},   /* hip_L */
        {      0,      0,      0},   /* kne_L */
        {      0,      0,      0},   /* ank_L */
    }},
    {  45, {
        {      0,      0,      0},   /* root */
        {      0,      0,      0},   /* spine */
        {      0,      0,      0},   /* chest */
        {      0,      0,      0},   /* neck */
        {      0,      0,      0},   /* head */
        {      0,      0,      0},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,      0},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {      0,      0,      0},   /* hip_R */
        {      0,      0,      0},   /* kne_R */
        {      0,      0,      0},   /* ank_R */
        {      0,      0,      0},   /* hip_L */
        {      0,      0,      0},   /* kne_L */
        {      0,      0,      0},   /* ank_L */
    }},
    {  66, {
        {      0,      0,      0},   /* root */
        {    728,      0,      0},   /* spine */
        {    910,      0,      0},   /* chest */
        {    546,      0,      0},   /* neck */
        {   1092,      0,      0},   /* head */
        {      0,      0,  -1092},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,   1092},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        { -16020,      0,      0},   /* hip_R */
        {  15292,      0,      0},   /* kne_R */
        {  -1456,      0,      0},   /* ank_R */
        { -16020,      0,      0},   /* hip_L */
        {  15292,      0,      0},   /* kne_L */
        {  -1456,      0,      0},   /* ank_L */
    }},
    {  93, {
        {      0,      0,      0},   /* root */
        {    728,      0,      0},   /* spine */
        {    910,      0,      0},   /* chest */
        {    546,      0,      0},   /* neck */
        {   1092,      0,      0},   /* head */
        {      0,      0,  -1092},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,   1092},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        { -16020,      0,      0},   /* hip_R */
        {  15292,      0,      0},   /* kne_R */
        {  -1456,      0,      0},   /* ank_R */
        { -16020,      0,      0},   /* hip_L */
        {  15292,      0,      0},   /* kne_L */
        {  -1456,      0,      0},   /* ank_L */
    }},
    { 111, {
        {      0,      0,      0},   /* root */
        {    182,      0,      0},   /* spine */
        {    182,      0,      0},   /* chest */
        {   -728,      0,      0},   /* neck */
        {   -364,      0,      0},   /* head */
        {      0,      0,  -1456},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,   1456},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {  -6554,      0,      0},   /* hip_R */
        {   6190,      0,      0},   /* kne_R */
        {      0,      0,      0},   /* ank_R */
        {  -6554,      0,      0},   /* hip_L */
        {   6190,      0,      0},   /* kne_L */
        {      0,      0,      0},   /* ank_L */
    }},
    { 126, {
        {      0,      0,      0},   /* root */
        {   -546,      0,      0},   /* spine */
        {   -728,      0,      0},   /* chest */
        {  -1638,      0,      0},   /* neck */
        {  -1274,      0,      0},   /* head */
        {      0,      0,   -910},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,    910},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {      0,      0,      0},   /* hip_R */
        {      0,      0,      0},   /* kne_R */
        {  -1092,      0,      0},   /* ank_R */
        {      0,      0,      0},   /* hip_L */
        {      0,      0,      0},   /* kne_L */
        {  -1092,      0,      0},   /* ank_L */
    }},
    { 218, {
        {      0,      0,      0},   /* root */
        {   -546,      0,      0},   /* spine */
        {   -728,      0,      0},   /* chest */
        {  -1638,      0,      0},   /* neck */
        {  -1274,      0,      0},   /* head */
        {      0,      0,   -910},   /* clav_R */
        {      0,      0,      0},   /* elb_R */
        {      0,      0,      0},   /* wri_R */
        {      0,      0,    910},   /* clav_L */
        {      0,      0,      0},   /* elb_L */
        {      0,      0,      0},   /* wri_L */
        {      0,      0,      0},   /* hip_R */
        {      0,      0,      0},   /* kne_R */
        {  -1092,      0,      0},   /* ank_R */
        {      0,      0,      0},   /* hip_L */
        {      0,      0,      0},   /* kne_L */
        {  -1092,      0,      0},   /* ank_L */
    }},
};

static const PhRootKey ph_intake_root[PH_INTAKE_ROOT_KEYS] = {
    {   0, {  -560,   768,  1264},  -32768,       0 },
    {  27, {  -560,   768,  1264},  -32768,       0 },
    {  45, {  -560,   768,  1216},       0,       0 },
    {  66, {  -560,   776,   864},       0,       0 },
    {  93, {  -560,   776,   864},       0,       0 },
    { 111, {  -560,   792,   528},       0,   -8010 },
    { 126, {  -560,   800,   192},       0,  -16384 },
    { 218, {  -560,   800,   192},       0,  -16384 },
};

/* Slide the lab's "table" segment by this along Z.  It is a separate
 * group in dank_lab_gen.py precisely so it can move on its own. */
static const PhPropKey ph_intake_table[PH_INTAKE_TABLE_KEYS] = {
    {   0,      0 },
    { 144,      0 },
    { 195,  -1200 },
    { 218,  -1200 },
};

/* Hold points worth hitting exactly if you cut sound to this: */
#define PH_INTAKE_CUE_LOOK   0   /* he is just standing there */
#define PH_INTAKE_CUE_SIT    66   /* weight lands on the slab */
#define PH_INTAKE_CUE_LIE    126   /* head touches down */
#define PH_INTAKE_CUE_MOTOR  144   /* slab drive starts */
#define PH_INTAKE_CUE_IN     195   /* he is inside */

#endif /* PH_ANIM_INTAKE_H */
