/* SPDX-License-Identifier: MIT
 *
 * engine/src/kiln/kiln_compat.h — the old prefix, for one migration train.
 *
 * docs/NAMING.md section 9 step 2: "Add `fig_*` as the real symbols; `kiln_*`
 * becomes a compatibility macro in one header." This is that header, and it is
 * the ONLY place the old prefix is allowed to appear as an identifier —
 * nix/checks/fig-names.nix skips this file and fails on every other.
 *
 * ── Why a macro and not a second set of declarations ───────────────────
 * Section 10 forbids a public header that ships both spellings as
 * first-class. A macro cannot be linked against, cannot appear in a symbol
 * table, and cannot drift from what it points at — if `fig_scene_begin` is
 * renamed again, every line here fails to compile rather than resolving to
 * something stale. Two sets of prototypes would do the opposite.
 *
 * ── How a downstream gets it ──────────────────────────────────────────
 * Every public engine header includes it. That is deliberately NOT the
 * cheapest arrangement: it was a `-include` in engine/kiln-inst.mk first,
 * which would have made ending the train a two-file diff. That version was
 * wrong, and PetaByte-Madness' pm-cine check is what proved it — a
 * force-include only reaches builds that include kiln-inst.mk, so a Nix check
 * or a host build compiling a downstream's sources directly saw none of it
 * and failed on `kiln_camkey_sample`. A header the consumer already includes
 * reaches every consumer by construction.
 *
 * ── Why the whole public surface and not just what one game calls ─────
 * The first version of this file was generated from what PetaByte-Madness'
 * src/ actually used, so the count would only ever go down and the file would
 * read as a debt ledger. That was too clever: it missed that repo's own
 * nix/checks/, which call the engine too. A bridge with holes in it is worse
 * than a wide one, because the holes are found one build at a time by whoever
 * is unlucky. This is generated from every fig_* / Fig* / FIG_* name in the
 * engine's and plat/host's public headers.
 *
 * ── What is NOT here, on purpose ──────────────────────────────────────
 *  - KILN_DEBUG, KILN_JUMP, KILN_HOST_DFS and KILN_SRC. Those are the FORGE's
 *    build knobs, set by Nix and make (section 4: the Kiln CLI / Nix layer
 *    keeps `kiln`). They were never renamed, so they need no bridge.
 *  - Include guards. Nothing outside a header reads one.
 *  - File names. Section 9 step 2 moves symbols, not files, so
 *    `#include <kiln_skel.h>` and dsp/kiln_jingle.dsp are still correct.
 *
 * ── The stop condition ────────────────────────────────────────────────
 * Section 9 step 6: delete this file, and the one #include line each public
 * header carries, when the tree and the Exsecutor-emitted C no longer mention
 * `kiln_*`. Both halves are a scripted removal.
 */
#ifndef FIG_COMPAT_H
#define FIG_COMPAT_H

#define KILN_ACTOR_CATEGORY_COUNT             FIG_ACTOR_CATEGORY_COUNT
#define KILN_ACTOR_CAT_BOSS                   FIG_ACTOR_CAT_BOSS
#define KILN_ACTOR_CAT_CHEST                  FIG_ACTOR_CAT_CHEST
#define KILN_ACTOR_CAT_DOOR                   FIG_ACTOR_CAT_DOOR
#define KILN_ACTOR_CAT_ENEMY                  FIG_ACTOR_CAT_ENEMY
#define KILN_ACTOR_CAT_ITEM                   FIG_ACTOR_CAT_ITEM
#define KILN_ACTOR_CAT_NPC                    FIG_ACTOR_CAT_NPC
#define KILN_ACTOR_CAT_PLAYER                 FIG_ACTOR_CAT_PLAYER
#define KILN_ACTOR_CAT_PROP                   FIG_ACTOR_CAT_PROP
#define KILN_ACTOR_FLAG_NONE                  FIG_ACTOR_FLAG_NONE
#define KILN_ACTOR_FLAG_NO_DRAW               FIG_ACTOR_FLAG_NO_DRAW
#define KILN_ACTOR_FLAG_PAUSED                FIG_ACTOR_FLAG_PAUSED
#define KILN_ACTOR_HANDLE_NONE                FIG_ACTOR_HANDLE_NONE
#define KILN_ACTOR_ROOM_NONE                  FIG_ACTOR_ROOM_NONE
#define KILN_ACTOR_STATE_MAX                  FIG_ACTOR_STATE_MAX
#define KILN_AUDIO_DEFAULT                    FIG_AUDIO_DEFAULT
#define KILN_AUDIO_MAX_MUSIC                  FIG_AUDIO_MAX_MUSIC
#define KILN_AUDIO_MAX_SFX                    FIG_AUDIO_MAX_SFX
#define KILN_BOARD_MAX_EDGES                  FIG_BOARD_MAX_EDGES
#define KILN_BOARD_MAX_NODES                  FIG_BOARD_MAX_NODES
#define KILN_BTN_                             FIG_BTN_
#define KILN_BTN_A                            FIG_BTN_A
#define KILN_BTN_B                            FIG_BTN_B
#define KILN_BTN_CD                           FIG_BTN_CD
#define KILN_BTN_CL                           FIG_BTN_CL
#define KILN_BTN_CR                           FIG_BTN_CR
#define KILN_BTN_CU                           FIG_BTN_CU
#define KILN_BTN_DD                           FIG_BTN_DD
#define KILN_BTN_DL                           FIG_BTN_DL
#define KILN_BTN_DR                           FIG_BTN_DR
#define KILN_BTN_DU                           FIG_BTN_DU
#define KILN_BTN_L                            FIG_BTN_L
#define KILN_BTN_R                            FIG_BTN_R
#define KILN_BTN_START                        FIG_BTN_START
#define KILN_BTN_Z                            FIG_BTN_Z
#define KILN_CACHE_HANDLE_INVALID             FIG_CACHE_HANDLE_INVALID
#define KILN_CACHE_MAX_ENTRIES                FIG_CACHE_MAX_ENTRIES
#define KILN_CACHE_MAX_KEY_LEN                FIG_CACHE_MAX_KEY_LEN
#define KILN_CAMLINT_ERR_                     FIG_CAMLINT_ERR_
#define KILN_CAMLINT_ERR_COUNT                FIG_CAMLINT_ERR_COUNT
#define KILN_CAMLINT_ERR_DEGENERATE           FIG_CAMLINT_ERR_DEGENERATE
#define KILN_CAMLINT_ERR_FRUSTUM              FIG_CAMLINT_ERR_FRUSTUM
#define KILN_CAMLINT_ERR_KEY_PAST_END         FIG_CAMLINT_ERR_KEY_PAST_END
#define KILN_CAMLINT_ERR_NAN                  FIG_CAMLINT_ERR_NAN
#define KILN_CAMLINT_ERR_NO_KEYS              FIG_CAMLINT_ERR_NO_KEYS
#define KILN_CAMLINT_ERR_SUBJECT_CUT          FIG_CAMLINT_ERR_SUBJECT_CUT
#define KILN_CAMLINT_ERR_TIME_ORDER           FIG_CAMLINT_ERR_TIME_ORDER
#define KILN_CAMLINT_HITCH_RATIO              FIG_CAMLINT_HITCH_RATIO
#define KILN_CAMLINT_NOTE_                    FIG_CAMLINT_NOTE_
#define KILN_CAMLINT_NOTE_DEAD_TAIL           FIG_CAMLINT_NOTE_DEAD_TAIL
#define KILN_CAMLINT_NOTE_HITCH               FIG_CAMLINT_NOTE_HITCH
#define KILN_CAMLINT_NOTE_LATE_START          FIG_CAMLINT_NOTE_LATE_START
#define KILN_CAMLINT_NOTE_NEAR_AIM            FIG_CAMLINT_NOTE_NEAR_AIM
#define KILN_CAMLINT_NOTE_OUTSIDE             FIG_CAMLINT_NOTE_OUTSIDE
#define KILN_CAMLINT_NOTE_OVERSHOOT           FIG_CAMLINT_NOTE_OVERSHOOT
#define KILN_CAMLINT_OVERSHOOT_FRAC           FIG_CAMLINT_OVERSHOOT_FRAC
#define KILN_CAMLINT_SAMPLES_PER_SEG          FIG_CAMLINT_SAMPLES_PER_SEG
#define KILN_CAMLINT_TAIL_FRAC                FIG_CAMLINT_TAIL_FRAC
#define KILN_CAM_BOARD                        FIG_CAM_BOARD
#define KILN_CAM_CUTSCENE                     FIG_CAM_CUTSCENE
#define KILN_CAM_NORMAL                       FIG_CAM_NORMAL
#define KILN_CAM_STACK_DEPTH                  FIG_CAM_STACK_DEPTH
#define KILN_CAM_TARGETING                    FIG_CAM_TARGETING
#define KILN_CRATER_MAX_ACTIVE                FIG_CRATER_MAX_ACTIVE
#define KILN_CTX_NONE                         FIG_CTX_NONE
#define KILN_CTX_OPEN                         FIG_CTX_OPEN
#define KILN_CTX_OPEN_CHEST                   FIG_CTX_OPEN_CHEST
#define KILN_CTX_PICKUP                       FIG_CTX_PICKUP
#define KILN_CTX_TALK                         FIG_CTX_TALK
#define KILN_CTX_UNLOCK                       FIG_CTX_UNLOCK
#define KILN_CTX_USE                          FIG_CTX_USE
#define KILN_DIALOGUE_MAX_LINES               FIG_DIALOGUE_MAX_LINES
#define KILN_DIALOGUE_MAX_PAGES               FIG_DIALOGUE_MAX_PAGES
#define KILN_DICE_MAX_FACES                   FIG_DICE_MAX_FACES
#define KILN_DICT_FLOAT                       FIG_DICT_FLOAT
#define KILN_DICT_INT                         FIG_DICT_INT
#define KILN_DICT_MAX_KEYS                    FIG_DICT_MAX_KEYS
#define KILN_DICT_STRING                      FIG_DICT_STRING
#define KILN_DICT_VEC3                        FIG_DICT_VEC3
#define KILN_EVENT_ARG_MAX                    FIG_EVENT_ARG_MAX
#define KILN_EVENT_MAX                        FIG_EVENT_MAX
#define KILN_EV_PLAYER_FOOTSTEP               FIG_EV_PLAYER_FOOTSTEP
#define KILN_FONT_ASCENT                      FIG_FONT_ASCENT
#define KILN_FONT_DESCENT                     FIG_FONT_DESCENT
#define KILN_FONT_FIRST_CP                    FIG_FONT_FIRST_CP
#define KILN_FONT_LAST_CP                     FIG_FONT_LAST_CP
#define KILN_FONT_LINE_GAP                    FIG_FONT_LINE_GAP
#define KILN_FONT_SPACE_WIDTH                 FIG_FONT_SPACE_WIDTH
#define KILN_FPSCAM_PITCH_LIMIT               FIG_FPSCAM_PITCH_LIMIT
#define KILN_GUI_FONT                         FIG_GUI_FONT
#define KILN_HOST_DIR_T                       FIG_HOST_DIR_T
#define KILN_HOST_EEPROM                      FIG_HOST_EEPROM
#define KILN_INPUT_NO_LOOP                    FIG_INPUT_NO_LOOP
#define KILN_INV_SLOTS                        FIG_INV_SLOTS
#define KILN_LEVEL_                           FIG_LEVEL_
#define KILN_LEVEL_MAX_BRUSHES                FIG_LEVEL_MAX_BRUSHES
#define KILN_LEVEL_MAX_BRUSH_PLANES           FIG_LEVEL_MAX_BRUSH_PLANES
#define KILN_LEVEL_MAX_CLASSNAMES             FIG_LEVEL_MAX_CLASSNAMES
#define KILN_LEVEL_MAX_COORD                  FIG_LEVEL_MAX_COORD
#define KILN_LEVEL_MAX_ENTITIES               FIG_LEVEL_MAX_ENTITIES
#define KILN_LEVEL_MAX_FACES                  FIG_LEVEL_MAX_FACES
#define KILN_LEVEL_MAX_FACE_VERTS             FIG_LEVEL_MAX_FACE_VERTS
#define KILN_LEVEL_MAX_SPAWNS                 FIG_LEVEL_MAX_SPAWNS
#define KILN_PHASE_COUNT                      FIG_PHASE_COUNT
#define KILN_PHASE_END                        FIG_PHASE_END
#define KILN_PHASE_EVENT                      FIG_PHASE_EVENT
#define KILN_PHASE_LAND                       FIG_PHASE_LAND
#define KILN_PHASE_MOVE                       FIG_PHASE_MOVE
#define KILN_PHASE_ROLL                       FIG_PHASE_ROLL
#define KILN_PHYS_DYNAMIC                     FIG_PHYS_DYNAMIC
#define KILN_PHYS_KINEMATIC                   FIG_PHYS_KINEMATIC
#define KILN_PHYS_STATIC                      FIG_PHYS_STATIC
#define KILN_PLAYER_ATTACK                    FIG_PLAYER_ATTACK
#define KILN_PLAYER_FALL                      FIG_PLAYER_FALL
#define KILN_PLAYER_IDLE                      FIG_PLAYER_IDLE
#define KILN_PLAYER_JUMP                      FIG_PLAYER_JUMP
#define KILN_PLAYER_MAXS                      FIG_PLAYER_MAXS
#define KILN_PLAYER_MINS                      FIG_PLAYER_MINS
#define KILN_PLAYER_ROLL                      FIG_PLAYER_ROLL
#define KILN_PLAYER_RUN                       FIG_PLAYER_RUN
#define KILN_PLAYER_STATE_SIZE                FIG_PLAYER_STATE_SIZE
#define KILN_PLAYER_WALK                      FIG_PLAYER_WALK
#define KILN_POSE_MASK_ALL                    FIG_POSE_MASK_ALL
#define KILN_POSE_MAX_BONES                   FIG_POSE_MAX_BONES
#define KILN_PRIM_BATCH                       FIG_PRIM_BATCH
#define KILN_PRIM_FLOOR_MAX_CELLS             FIG_PRIM_FLOOR_MAX_CELLS
#define KILN_PROF_AUDIO                       FIG_PROF_AUDIO
#define KILN_PROF_BEGIN                       FIG_PROF_BEGIN
#define KILN_PROF_COUNT                       FIG_PROF_COUNT
#define KILN_PROF_DEBUG                       FIG_PROF_DEBUG
#define KILN_PROF_END                         FIG_PROF_END
#define KILN_PROF_GUI                         FIG_PROF_GUI
#define KILN_PROF_SCENE                       FIG_PROF_SCENE
#define KILN_PROF_TOTAL                       FIG_PROF_TOTAL
#define KILN_PROF_UPDATE                      FIG_PROF_UPDATE
#define KILN_PROJECTILE_MAX                   FIG_PROJECTILE_MAX
#define KILN_PROJ_GRENADE                     FIG_PROJ_GRENADE
#define KILN_PROJ_GRENADE_W                   FIG_PROJ_GRENADE_W
#define KILN_PROJ_NONE                        FIG_PROJ_NONE
#define KILN_PROJ_PLASMA                      FIG_PROJ_PLASMA
#define KILN_PROJ_PLASMA_W                    FIG_PROJ_PLASMA_W
#define KILN_PROJ_ROCKET                      FIG_PROJ_ROCKET
#define KILN_PROJ_ROCKET_W                    FIG_PROJ_ROCKET_W
#define KILN_ROOM_FLAG_LOADED                 FIG_ROOM_FLAG_LOADED
#define KILN_ROOM_MAX_CLIP_BRUSHES            FIG_ROOM_MAX_CLIP_BRUSHES
#define KILN_ROOM_MAX_LOADED                  FIG_ROOM_MAX_LOADED
#define KILN_ROOM_MAX_NEIGHBOURS              FIG_ROOM_MAX_NEIGHBOURS
#define KILN_ROOM_MAX_SPAWNS                  FIG_ROOM_MAX_SPAWNS
#define KILN_SAVE_MAGIC                       FIG_SAVE_MAGIC
#define KILN_SAVE_MAX_SLOTS                   FIG_SAVE_MAX_SLOTS
#define KILN_SCENE_MAX_LIGHTS                 FIG_SCENE_MAX_LIGHTS
#define KILN_SCRATCH_SIZE                     FIG_SCRATCH_SIZE
#define KILN_SDBFS_MAX_OPEN                   FIG_SDBFS_MAX_OPEN
#define KILN_SIERP_MAX_DEPTH                  FIG_SIERP_MAX_DEPTH
#define KILN_SIERP_MAX_LEAVES                 FIG_SIERP_MAX_LEAVES
#define KILN_SKEL_BASE                        FIG_SKEL_BASE
#define KILN_SKEL_BLEND                       FIG_SKEL_BLEND
#define KILN_SKEL_CLIPS_MAX                   FIG_SKEL_CLIPS_MAX
#define KILN_SKEL_OVERLAY                     FIG_SKEL_OVERLAY
#define KILN_SKEL_OVERRIDES_MAX               FIG_SKEL_OVERRIDES_MAX
#define KILN_SKEL_SLOTS                       FIG_SKEL_SLOTS
#define KILN_SOFT3D_BAD_COUNTS                FIG_SOFT3D_BAD_COUNTS
#define KILN_SOFT3D_BAD_MAGIC                 FIG_SOFT3D_BAD_MAGIC
#define KILN_SOFT3D_EXSG_BYTES                FIG_SOFT3D_EXSG_BYTES
#define KILN_SOFT3D_FB_BYTES                  FIG_SOFT3D_FB_BYTES
#define KILN_SOFT3D_OK                        FIG_SOFT3D_OK
#define KILN_SOFT3D_SHORT_STREAM              FIG_SOFT3D_SHORT_STREAM
#define KILN_SOFT3D_SIDE                      FIG_SOFT3D_SIDE
#define KILN_SOFT3D_TRAILING_BYTES            FIG_SOFT3D_TRAILING_BYTES
#define KILN_SOUND_CHANNELS                   FIG_SOUND_CHANNELS
#define KILN_SOUND_SHADER_MAX                 FIG_SOUND_SHADER_MAX
#define KILN_SPACE_BAD                        FIG_SPACE_BAD
#define KILN_SPACE_BONUS                      FIG_SPACE_BONUS
#define KILN_SPACE_COUNT                      FIG_SPACE_COUNT
#define KILN_SPACE_GOOD                       FIG_SPACE_GOOD
#define KILN_SPACE_MINIGAME                   FIG_SPACE_MINIGAME
#define KILN_SPACE_SHORTCUT                   FIG_SPACE_SHORTCUT
#define KILN_SPACE_START                      FIG_SPACE_START
#define KILN_SPACE_TRADE                      FIG_SPACE_TRADE
#define KILN_STORE_CART_SD                    FIG_STORE_CART_SD
#define KILN_STORE_DFS                        FIG_STORE_DFS
#define KILN_STORE_DIR                        FIG_STORE_DIR
#define KILN_STORE_ECRC                       FIG_STORE_ECRC
#define KILN_STORE_EIO                        FIG_STORE_EIO
#define KILN_STORE_EMAGIC                     FIG_STORE_EMAGIC
#define KILN_STORE_ENAME                      FIG_STORE_ENAME
#define KILN_STORE_ENOENT                     FIG_STORE_ENOENT
#define KILN_STORE_ENOINIT                    FIG_STORE_ENOINIT
#define KILN_STORE_ENOSPACE                   FIG_STORE_ENOSPACE
#define KILN_STORE_EOPEN                      FIG_STORE_EOPEN
#define KILN_STORE_EREADONLY                  FIG_STORE_EREADONLY
#define KILN_STORE_EVERSION                   FIG_STORE_EVERSION
#define KILN_STORE_MAGIC                      FIG_STORE_MAGIC
#define KILN_STORE_MAGIC_LEGACY               FIG_STORE_MAGIC_LEGACY
#define KILN_STORE_NAME_MAX                   FIG_STORE_NAME_MAX
#define KILN_STORE_NONE                       FIG_STORE_NONE
#define KILN_STORE_OK                         FIG_STORE_OK
#define KILN_STORE_SRAM                       FIG_STORE_SRAM
#define KILN_STORE_SRAM_BYTES                 FIG_STORE_SRAM_BYTES
#define KILN_STORE_SRAM_SLOTS                 FIG_STORE_SRAM_SLOTS
#define KILN_STREAMIO_MODEL                   FIG_STREAMIO_MODEL
#define KILN_STREAMIO_OWNER_ROOM              FIG_STREAMIO_OWNER_ROOM
#define KILN_STREAMIO_OWNER_TILE              FIG_STREAMIO_OWNER_TILE
#define KILN_STREAMIO_SPRITE                  FIG_STREAMIO_SPRITE
#define KILN_STREAM_HANDLE_INVALID            FIG_STREAM_HANDLE_INVALID
#define KILN_STREAM_MAX_KEY_LEN               FIG_STREAM_MAX_KEY_LEN
#define KILN_STREAM_MAX_PENDING               FIG_STREAM_MAX_PENDING
#define KILN_STREAM_NORMAL                    FIG_STREAM_NORMAL
#define KILN_STREAM_PREFETCH                  FIG_STREAM_PREFETCH
#define KILN_STREAM_SLOT_ADMITTED             FIG_STREAM_SLOT_ADMITTED
#define KILN_STREAM_SLOT_FREE                 FIG_STREAM_SLOT_FREE
#define KILN_STREAM_SLOT_PENDING              FIG_STREAM_SLOT_PENDING
#define KILN_STREAM_URGENT                    FIG_STREAM_URGENT
#define KILN_SURFACE_MAX                      FIG_SURFACE_MAX
#define KILN_TEXANIM_FLIPBOOK                 FIG_TEXANIM_FLIPBOOK
#define KILN_TEXANIM_OFFSCREEN                FIG_TEXANIM_OFFSCREEN
#define KILN_TEXANIM_PALETTE                  FIG_TEXANIM_PALETTE
#define KILN_TEXANIM_SCROLL                   FIG_TEXANIM_SCROLL
#define KILN_TILE_MAX_LOD                     FIG_TILE_MAX_LOD
#define KILN_TILE_UNLOAD_QUEUE_CAP            FIG_TILE_UNLOAD_QUEUE_CAP
#define KILN_TRIGGER_MAX                      FIG_TRIGGER_MAX
#define KILN_TRIG_MULTIPLE                    FIG_TRIG_MULTIPLE
#define KILN_TRIG_ONCE                        FIG_TRIG_ONCE
#define KILN_TRIG_PUSH                        FIG_TRIG_PUSH
#define KILN_TWOPASS_FAR_LOD_THRESHOLD        FIG_TWOPASS_FAR_LOD_THRESHOLD
#define KILN_VFX_CELSHADE_ALPHA               FIG_VFX_CELSHADE_ALPHA
#define KILN_VFX_CELSHADE_COLOR               FIG_VFX_CELSHADE_COLOR
#define KILN_VFX_NONE                         FIG_VFX_NONE
#define KILN_VFX_OUTLINE                      FIG_VFX_OUTLINE
#define KILN_VFX_SPHERICAL_UV                 FIG_VFX_SPHERICAL_UV
#define KILN_VFX_UV_OFFSET                    FIG_VFX_UV_OFFSET
#define KILN_VOXATLAS_ACROSS                  FIG_VOXATLAS_ACROSS
#define KILN_VOXATLAS_COLD                    FIG_VOXATLAS_COLD
#define KILN_VOXATLAS_COLOURS                 FIG_VOXATLAS_COLOURS
#define KILN_VOXATLAS_SIDE                    FIG_VOXATLAS_SIDE
#define KILN_VOXATLAS_TILE                    FIG_VOXATLAS_TILE
#define KILN_VOXATLAS_TILES                   FIG_VOXATLAS_TILES
#define KILN_VOXATLAS_VEILED                  FIG_VOXATLAS_VEILED
#define KILN_VOXEL_AIR                        FIG_VOXEL_AIR
#define KILN_VOXEL_BLOCK_UNITS                FIG_VOXEL_BLOCK_UNITS
#define KILN_VOXEL_CHUNK                      FIG_VOXEL_CHUNK
#define KILN_VOXEL_CHUNK_BLOCKS               FIG_VOXEL_CHUNK_BLOCKS
#define KILN_VOXEL_DIM_X                      FIG_VOXEL_DIM_X
#define KILN_VOXEL_DIM_Y                      FIG_VOXEL_DIM_Y
#define KILN_VOXEL_DIM_Z                      FIG_VOXEL_DIM_Z
#define KILN_VOXEL_DIRS                       FIG_VOXEL_DIRS
#define KILN_VOXEL_EFULL                      FIG_VOXEL_EFULL
#define KILN_VOXEL_ETYPE                      FIG_VOXEL_ETYPE
#define KILN_VOXEL_GRID_SLOTS                 FIG_VOXEL_GRID_SLOTS
#define KILN_VOXEL_GRID_X                     FIG_VOXEL_GRID_X
#define KILN_VOXEL_GRID_Y                     FIG_VOXEL_GRID_Y
#define KILN_VOXEL_GRID_Z                     FIG_VOXEL_GRID_Z
#define KILN_VOXEL_MAX_CHUNKS                 FIG_VOXEL_MAX_CHUNKS
#define KILN_VOXEL_TYPE_MAX                   FIG_VOXEL_TYPE_MAX
#define KILN_VOXEL_XN                         FIG_VOXEL_XN
#define KILN_VOXEL_XP                         FIG_VOXEL_XP
#define KILN_VOXEL_YN                         FIG_VOXEL_YN
#define KILN_VOXEL_YP                         FIG_VOXEL_YP
#define KILN_VOXEL_ZN                         FIG_VOXEL_ZN
#define KILN_VOXEL_ZP                         FIG_VOXEL_ZP
#define KILN_VOXMESH_BATCH                    FIG_VOXMESH_BATCH
#define KILN_WEAPON_SLOTS                     FIG_WEAPON_SLOTS
#define KILN_WIDGET_CHAR_W                    FIG_WIDGET_CHAR_W
#define KILN_WPN_FIRING                       FIG_WPN_FIRING
#define KILN_WPN_IDLE                         FIG_WPN_IDLE
#define KILN_WPN_RELOADING                    FIG_WPN_RELOADING
#define KILN_WTYPE_HITSCAN                    FIG_WTYPE_HITSCAN
#define KILN_WTYPE_PROJECTILE                 FIG_WTYPE_PROJECTILE
#define KilnActor                             FigActor
#define KilnActorCategory                     FigActorCategory
#define KilnActorDestroyFn                    FigActorDestroyFn
#define KilnActorDrawFn                       FigActorDrawFn
#define KilnActorEventFn                      FigActorEventFn
#define KilnActorHandle                       FigActorHandle
#define KilnActorInitFn                       FigActorInitFn
#define KilnActorProfile                      FigActorProfile
#define KilnActorUpdateFn                     FigActorUpdateFn
#define KilnAsset                             FigAsset
#define KilnAudioConfig                       FigAudioConfig
#define KilnAudioInsert                       FigAudioInsert
#define KilnAudioTap                          FigAudioTap
#define KilnBoard                             FigBoard
#define KilnBoardNode                         FigBoardNode
#define KilnBrush                             FigBrush
#define KilnCache                             FigCache
#define KilnCacheEntry                        FigCacheEntry
#define KilnCacheHandle                       FigCacheHandle
#define KilnCacheLoadFn                       FigCacheLoadFn
#define KilnCacheReleaseFn                    FigCacheReleaseFn
#define KilnCamBounds                         FigCamBounds
#define KilnCamKey                            FigCamKey
#define KilnCamMode                           FigCamMode
#define KilnCamReport                         FigCamReport
#define KilnCamShot                           FigCamShot
#define KilnCamera                            FigCamera
#define KilnCharPassiveFn                     FigCharPassiveFn
#define KilnCharProfile                       FigCharProfile
#define KilnCharSpecialFn                     FigCharSpecialFn
#define KilnCharState                         FigCharState
#define KilnConsoleCmd                        FigConsoleCmd
#define KilnContextAction                     FigContextAction
#define KilnCraterField                       FigCraterField
#define KilnCraterSlot                        FigCraterSlot
#define KilnCraterVert                        FigCraterVert
#define KilnDeform                            FigDeform
#define KilnDeformFn                          FigDeformFn
#define KilnDetailPlace                       FigDetailPlace
#define KilnDetailStats                       FigDetailStats
#define KilnDialogue                          FigDialogue
#define KilnDice                              FigDice
#define KilnDict                              FigDict
#define KilnDictEntry                         FigDictEntry
#define KilnDictType                          FigDictType
#define KilnFontGlyph                         FigFontGlyph
#define KilnFpsCam                            FigFpsCam
#define KilnHostAudioCounters                 FigHostAudioCounters
#define KilnHostCounters                      FigHostCounters
#define KilnHostHooks                         FigHostHooks
#define KilnHostT3DCounters                   FigHostT3DCounters
#define KilnInput                             FigInput
#define KilnInputKey                          FigInputKey
#define KilnInputTape                         FigInputTape
#define KilnInvSlot                           FigInvSlot
#define KilnInventory                         FigInventory
#define KilnLODConfig                         FigLODConfig
#define KilnLODSelectorFn                     FigLODSelectorFn
#define KilnLight                             FigLight
#define KilnMap                               FigMap
#define KilnMapFace                           FigMapFace
#define KilnMapTint                           FigMapTint
#define KilnMenu                              FigMenu
#define KilnMorph                             FigMorph
#define KilnPassDrawFn                        FigPassDrawFn
#define KilnPhysType                          FigPhysType
#define KilnPhysicsBody                       FigPhysicsBody
#define KilnPhysicsWorld                      FigPhysicsWorld
#define KilnPlayer                            FigPlayer
#define KilnPlayerSlot                        FigPlayerSlot
#define KilnPlayerState                       FigPlayerState
#define KilnPrim                              FigPrim
#define KilnProjHitFn                         FigProjHitFn
#define KilnProjType                          FigProjType
#define KilnProjectile                        FigProjectile
#define KilnRadioTrack                        FigRadioTrack
#define KilnRng                               FigRng
#define KilnRoom                              FigRoom
#define KilnRoomDrawFn                        FigRoomDrawFn
#define KilnRoomLoadFn                        FigRoomLoadFn
#define KilnRoomSpawn                         FigRoomSpawn
#define KilnRoomSpawnFn                       FigRoomSpawnFn
#define KilnRoomSystem                        FigRoomSystem
#define KilnRoomUnloadFn                      FigRoomUnloadFn
#define KilnSaveHeader                        FigSaveHeader
#define KilnScene                             FigScene
#define KilnSceneArea                         FigSceneArea
#define KilnScratch                           FigScratch
#define KilnSkel                              FigSkel
#define KilnSkelSlot                          FigSkelSlot
#define KilnSoundShader                       FigSoundShader
#define KilnSpaceType                         FigSpaceType
#define KilnStoreHeader                       FigStoreHeader
#define KilnStoreKind                         FigStoreKind
#define KilnStoreLogFn                        FigStoreLogFn
#define KilnStoreStatus                       FigStoreStatus
#define KilnStream                            FigStream
#define KilnStreamBudget                      FigStreamBudget
#define KilnStreamHandle                      FigStreamHandle
#define KilnStreamIO                          FigStreamIO
#define KilnStreamIOAssetType                 FigStreamIOAssetType
#define KilnStreamIORoomBinding               FigStreamIORoomBinding
#define KilnStreamIORoomKeyFn                 FigStreamIORoomKeyFn
#define KilnStreamIOSlot                      FigStreamIOSlot
#define KilnStreamIOTileBinding               FigStreamIOTileBinding
#define KilnStreamIOTileKeyFn                 FigStreamIOTileKeyFn
#define KilnStreamSlot                        FigStreamSlot
#define KilnStreamSlotState                   FigStreamSlotState
#define KilnStreamUrgency                     FigStreamUrgency
#define KilnSurfaceDef                        FigSurfaceDef
#define KilnTet                               FigTet
#define KilnTexAnim                           FigTexAnim
#define KilnTexAnimMode                       FigTexAnimMode
#define KilnTileGrid                          FigTileGrid
#define KilnTileGridConfig                    FigTileGridConfig
#define KilnTileLoadFn                        FigTileLoadFn
#define KilnTileManager                       FigTileManager
#define KilnTileSlot                          FigTileSlot
#define KilnTileSyncFn                        FigTileSyncFn
#define KilnTileUnloadFn                      FigTileUnloadFn
#define KilnTrace                             FigTrace
#define KilnTransform                         FigTransform
#define KilnTrigType                          FigTrigType
#define KilnTrigger                           FigTrigger
#define KilnTurn                              FigTurn
#define KilnTurnPhase                         FigTurnPhase
#define KilnVertexFX                          FigVertexFX
#define KilnVideo                             FigVideo
#define KilnVoxAtlas                          FigVoxAtlas
#define KilnVoxAtlasState                     FigVoxAtlasState
#define KilnVoxMesh                           FigVoxMesh
#define KilnVoxMeshArena                      FigVoxMeshArena
#define KilnVoxelChunk                        FigVoxelChunk
#define KilnVoxelDir                          FigVoxelDir
#define KilnVoxelHit                          FigVoxelHit
#define KilnVoxelQuad                         FigVoxelQuad
#define KilnVoxelWorld                        FigVoxelWorld
#define KilnWeapon                            FigWeapon
#define KilnWeaponDef                         FigWeaponDef
#define KilnWeaponProj                        FigWeaponProj
#define KilnWeaponSet                         FigWeaponSet
#define KilnWeaponState                       FigWeaponState
#define KilnWeaponType                        FigWeaponType
#define KilnWidgetStyle                       FigWidgetStyle
#define kiln_actor                            fig_actor
#define kiln_actor_count                      fig_actor_count
#define kiln_actor_despawn                    fig_actor_despawn
#define kiln_actor_dispatch_event             fig_actor_dispatch_event
#define kiln_actor_draw_all                   fig_actor_draw_all
#define kiln_actor_first                      fig_actor_first
#define kiln_actor_handle_of                  fig_actor_handle_of
#define kiln_actor_next                       fig_actor_next
#define kiln_actor_resolve                    fig_actor_resolve
#define kiln_actor_spawn                      fig_actor_spawn
#define kiln_actor_spawn_in_room              fig_actor_spawn_in_room
#define kiln_actor_spawn_with_args            fig_actor_spawn_with_args
#define kiln_actor_system_init                fig_actor_system_init
#define kiln_actor_update_all                 fig_actor_update_all
#define kiln_asset                            fig_asset
#define kiln_asset_arena_used                 fig_asset_arena_used
#define kiln_asset_close                      fig_asset_close
#define kiln_asset_count                      fig_asset_count
#define kiln_asset_exists                     fig_asset_exists
#define kiln_asset_find_suffix                fig_asset_find_suffix
#define kiln_asset_load                       fig_asset_load
#define kiln_asset_model                      fig_asset_model
#define kiln_asset_open                       fig_asset_open
#define kiln_asset_probe_size                 fig_asset_probe_size
#define kiln_asset_reader                     fig_asset_reader
#define kiln_asset_size                       fig_asset_size
#define kiln_asset_sprite                     fig_asset_sprite
#define kiln_asset_wav64                      fig_asset_wav64
#define kiln_audio                            fig_audio
#define kiln_audio_close                      fig_audio_close
#define kiln_audio_init                       fig_audio_init
#define kiln_audio_set_insert                 fig_audio_set_insert
#define kiln_audio_set_room_music             fig_audio_set_room_music
#define kiln_audio_set_tap                    fig_audio_set_tap
#define kiln_audio_update                     fig_audio_update
#define kiln_audio_update_rooms               fig_audio_update_rooms
#define kiln_board                            fig_board
#define kiln_board_init                       fig_board_init
#define kiln_board_pos                        fig_board_pos
#define kiln_board_step                       fig_board_step
#define kiln_cache                            fig_cache
#define kiln_cache_acquire                    fig_cache_acquire
#define kiln_cache_count                      fig_cache_count
#define kiln_cache_init                       fig_cache_init
#define kiln_cache_refcount                   fig_cache_refcount
#define kiln_cache_release                    fig_cache_release
#define kiln_cache_resolve                    fig_cache_resolve
#define kiln_camera                           fig_camera
#define kiln_camera_apply                     fig_camera_apply
#define kiln_camera_init                      fig_camera_init
#define kiln_camera_pop                       fig_camera_pop
#define kiln_camera_push                      fig_camera_push
#define kiln_camera_set_board                 fig_camera_set_board
#define kiln_camera_set_board_focus           fig_camera_set_board_focus
#define kiln_camera_set_board_spin            fig_camera_set_board_spin
#define kiln_camera_set_collision             fig_camera_set_collision
#define kiln_camera_set_cutscene              fig_camera_set_cutscene
#define kiln_camera_set_target_actor          fig_camera_set_target_actor
#define kiln_camera_snap                      fig_camera_snap
#define kiln_camera_snap_board                fig_camera_snap_board
#define kiln_camera_update                    fig_camera_update
#define kiln_camkey                           fig_camkey
#define kiln_camkey_sample                    fig_camkey_sample
#define kiln_camkey_spline1                   fig_camkey_spline1
#define kiln_camlint                          fig_camlint
#define kiln_camlint_err_name                 fig_camlint_err_name
#define kiln_camlint_note_name                fig_camlint_note_name
#define kiln_char_add_charge                  fig_char_add_charge
#define kiln_char_assign                      fig_char_assign
#define kiln_char_charge                      fig_char_charge
#define kiln_char_init                        fig_char_init
#define kiln_char_tick_cooldown               fig_char_tick_cooldown
#define kiln_char_tick_passive                fig_char_tick_passive
#define kiln_char_try_special                 fig_char_try_special
#define kiln_clip                             fig_clip
#define kiln_clip_box                         fig_clip_box
#define kiln_clip_ground                      fig_clip_ground
#define kiln_clip_last_trace_brushes          fig_clip_last_trace_brushes
#define kiln_clip_ray                         fig_clip_ray
#define kiln_clip_set_broadphase              fig_clip_set_broadphase
#define kiln_clip_set_world                   fig_clip_set_world
#define kiln_clip_slide                       fig_clip_slide
#define kiln_clip_world_count                 fig_clip_world_count
#define kiln_console                          fig_console
#define kiln_console_                         fig_console_
#define kiln_console_draw                     fig_console_draw
#define kiln_console_exec                     fig_console_exec
#define kiln_console_init                     fig_console_init
#define kiln_console_is_open                  fig_console_is_open
#define kiln_console_log                      fig_console_log
#define kiln_console_register                 fig_console_register
#define kiln_console_tail_line                fig_console_tail_line
#define kiln_console_tail_lines               fig_console_tail_lines
#define kiln_console_update                   fig_console_update
#define kiln_context_execute                  fig_context_execute
#define kiln_context_label                    fig_context_label
#define kiln_context_scan                     fig_context_scan
#define kiln_crater_destroy                   fig_crater_destroy
#define kiln_crater_impact                    fig_crater_impact
#define kiln_crater_init                      fig_crater_init
#define kiln_crater_sample                    fig_crater_sample
#define kiln_crater_update                    fig_crater_update
#define kiln_cull                             fig_cull
#define kiln_cull_sphere_of                   fig_cull_sphere_of
#define kiln_cull_surface_dist_sq             fig_cull_surface_dist_sq
#define kiln_cull_tier_of                     fig_cull_tier_of
#define kiln_dd_aabb                          fig_dd_aabb
#define kiln_dd_axes                          fig_dd_axes
#define kiln_dd_begin                         fig_dd_begin
#define kiln_dd_box                           fig_dd_box
#define kiln_dd_clipped                       fig_dd_clipped
#define kiln_dd_drawn                         fig_dd_drawn
#define kiln_dd_end                           fig_dd_end
#define kiln_dd_frustum                       fig_dd_frustum
#define kiln_dd_line                          fig_dd_line
#define kiln_dd_path                          fig_dd_path
#define kiln_dd_point                         fig_dd_point
#define kiln_dd_text                          fig_dd_text
#define kiln_debugdraw                        fig_debugdraw
#define kiln_deform_                          fig_deform_
#define kiln_deform_destroy                   fig_deform_destroy
#define kiln_deform_draw                      fig_deform_draw
#define kiln_deform_init                      fig_deform_init
#define kiln_deform_update                    fig_deform_update
#define kiln_detail_admit                     fig_detail_admit
#define kiln_detail_count                     fig_detail_count
#define kiln_detail_draw                      fig_detail_draw
#define kiln_detail_frame_begin               fig_detail_frame_begin
#define kiln_detail_model_visible             fig_detail_model_visible
#define kiln_detail_object                    fig_detail_object
#define kiln_detail_stats                     fig_detail_stats
#define kiln_detail_tier_available            fig_detail_tier_available
#define kiln_dfs_exists                       fig_dfs_exists
#define kiln_dialogue_active                  fig_dialogue_active
#define kiln_dialogue_draw                    fig_dialogue_draw
#define kiln_dialogue_start                   fig_dialogue_start
#define kiln_dialogue_update                  fig_dialogue_update
#define kiln_dice                             fig_dice
#define kiln_dice_init                        fig_dice_init
#define kiln_dice_init_uniform                fig_dice_init_uniform
#define kiln_dice_roll                        fig_dice_roll
#define kiln_dice_set_bias                    fig_dice_set_bias
#define kiln_dict_get_                        fig_dict_get_
#define kiln_dict_get_float                   fig_dict_get_float
#define kiln_dict_get_int                     fig_dict_get_int
#define kiln_dict_get_str                     fig_dict_get_str
#define kiln_dict_get_vec3                    fig_dict_get_vec3
#define kiln_dict_has_float                   fig_dict_has_float
#define kiln_dict_has_int                     fig_dict_has_int
#define kiln_dict_has_str                     fig_dict_has_str
#define kiln_dict_has_vec3                    fig_dict_has_vec3
#define kiln_dict_init                        fig_dict_init
#define kiln_dict_parse_float                 fig_dict_parse_float
#define kiln_dict_parse_int                   fig_dict_parse_int
#define kiln_dict_parse_vec3                  fig_dict_parse_vec3
#define kiln_dict_set_auto                    fig_dict_set_auto
#define kiln_dict_set_float                   fig_dict_set_float
#define kiln_dict_set_int                     fig_dict_set_int
#define kiln_dict_set_str                     fig_dict_set_str
#define kiln_dict_set_vec3                    fig_dict_set_vec3
#define kiln_engine                           fig_engine
#define kiln_engine_close                     fig_engine_close
#define kiln_engine_init                      fig_engine_init
#define kiln_event                            fig_event
#define kiln_event_count                      fig_event_count
#define kiln_event_init                       fig_event_init
#define kiln_event_post                       fig_event_post
#define kiln_event_process                    fig_event_process
#define kiln_font_bits                        fig_font_bits
#define kiln_font_glyphs                      fig_font_glyphs
#define kiln_fpscam                           fig_fpscam
#define kiln_fpscam_apply                     fig_fpscam_apply
#define kiln_fpscam_forward                   fig_fpscam_forward
#define kiln_fpscam_init                      fig_fpscam_init
#define kiln_fpscam_right                     fig_fpscam_right
#define kiln_fpscam_snap                      fig_fpscam_snap
#define kiln_fpscam_update                    fig_fpscam_update
#define kiln_frame_begin                      fig_frame_begin
#define kiln_frame_end                        fig_frame_end
#define kiln_gui                              fig_gui
#define kiln_gui_bar                          fig_gui_bar
#define kiln_gui_begin                        fig_gui_begin
#define kiln_gui_close                        fig_gui_close
#define kiln_gui_end                          fig_gui_end
#define kiln_gui_init                         fig_gui_init
#define kiln_gui_line                         fig_gui_line
#define kiln_gui_panel                        fig_gui_panel
#define kiln_gui_rect                         fig_gui_rect
#define kiln_gui_text                         fig_gui_text
#define kiln_host_audio_counters              fig_host_audio_counters
#define kiln_host_capture                     fig_host_capture
#define kiln_host_counters                    fig_host_counters
#define kiln_host_frame                       fig_host_frame
#define kiln_host_hooks                       fig_host_hooks
#define kiln_host_pad_set                     fig_host_pad_set
#define kiln_host_set_hooks                   fig_host_set_hooks
#define kiln_host_stats                       fig_host_stats
#define kiln_host_t3d_counters                fig_host_t3d_counters
#define kiln_host_text_manifest               fig_host_text_manifest
#define kiln_host_text_reset                  fig_host_text_reset
#define kiln_host_ticks32                     fig_host_ticks32
#define kiln_host_tmem_used                   fig_host_tmem_used
#define kiln_input                            fig_input
#define kiln_input_get                        fig_input_get
#define kiln_input_held                       fig_input_held
#define kiln_input_init                       fig_input_init
#define kiln_input_play                       fig_input_play
#define kiln_input_pressed                    fig_input_pressed
#define kiln_input_released                   fig_input_released
#define kiln_input_scripted                   fig_input_scripted
#define kiln_input_set_attract                fig_input_set_attract
#define kiln_input_update                     fig_input_update
#define kiln_inventory_add                    fig_inventory_add
#define kiln_inventory_consume                fig_inventory_consume
#define kiln_inventory_has                    fig_inventory_has
#define kiln_inventory_init                   fig_inventory_init
#define kiln_lod                              fig_lod
#define kiln_lod_init_defaults                fig_lod_init_defaults
#define kiln_lod_select                       fig_lod_select
#define kiln_lod_selector_cb                  fig_lod_selector_cb
#define kiln_lod_visible                      fig_lod_visible
#define kiln_map                              fig_map
#define kiln_map_draw                         fig_map_draw
#define kiln_map_free                         fig_map_free
#define kiln_map_load                         fig_map_load
#define kiln_map_register_classname           fig_map_register_classname
#define kiln_map_tint                         fig_map_tint
#define kiln_menu_draw                        fig_menu_draw
#define kiln_menu_init                        fig_menu_init
#define kiln_menu_move                        fig_menu_move
#define kiln_menu_move_enabled                fig_menu_move_enabled
#define kiln_menu_set_count                   fig_menu_set_count
#define kiln_morph_                           fig_morph_
#define kiln_morph_destroy                    fig_morph_destroy
#define kiln_morph_draw                       fig_morph_draw
#define kiln_morph_init                       fig_morph_init
#define kiln_morph_update                     fig_morph_update
#define kiln_music_first_channel              fig_music_first_channel
#define kiln_music_load                       fig_music_load
#define kiln_music_num_channels               fig_music_num_channels
#define kiln_music_play                       fig_music_play
#define kiln_music_playing                    fig_music_playing
#define kiln_music_seek                       fig_music_seek
#define kiln_music_set_loop                   fig_music_set_loop
#define kiln_music_set_volume                 fig_music_set_volume
#define kiln_music_stop                       fig_music_stop
#define kiln_music_tell                       fig_music_tell
#define kiln_panic_install                    fig_panic_install
#define kiln_panic_message                    fig_panic_message
#define kiln_physics                          fig_physics
#define kiln_physics_apply_impulse            fig_physics_apply_impulse
#define kiln_physics_init                     fig_physics_init
#define kiln_physics_set_enabled              fig_physics_set_enabled
#define kiln_physics_spawn                    fig_physics_spawn
#define kiln_physics_step                     fig_physics_step
#define kiln_player                           fig_player
#define kiln_player_                          fig_player_
#define kiln_player_of                        fig_player_of
#define kiln_player_set_camera_basis          fig_player_set_camera_basis
#define kiln_player_state_size                fig_player_state_size
#define kiln_player_update                    fig_player_update
#define kiln_pose_blend_masked                fig_pose_blend_masked
#define kiln_pose_subtree_mask                fig_pose_subtree_mask
#define kiln_prim_box                         fig_prim_box
#define kiln_prim_draw                        fig_prim_draw
#define kiln_prim_floor                       fig_prim_floor
#define kiln_prim_free                        fig_prim_free
#define kiln_prim_rgba                        fig_prim_rgba
#define kiln_prim_shade                       fig_prim_shade
#define kiln_prim_stage                       fig_prim_stage
#define kiln_prim_tets                        fig_prim_tets
#define kiln_prim_tets_update                 fig_prim_tets_update
#define kiln_prof                             fig_prof
#define kiln_prof_begin                       fig_prof_begin
#define kiln_prof_end                         fig_prof_end
#define kiln_prof_frac                        fig_prof_frac
#define kiln_prof_frame_done                  fig_prof_frame_done
#define kiln_prof_init                        fig_prof_init
#define kiln_prof_label                       fig_prof_label
#define kiln_prof_ms                          fig_prof_ms
#define kiln_prof_print                       fig_prof_print
#define kiln_projectile_draw_all              fig_projectile_draw_all
#define kiln_projectile_init                  fig_projectile_init
#define kiln_projectile_set_damage_fn         fig_projectile_set_damage_fn
#define kiln_projectile_set_hit_fn            fig_projectile_set_hit_fn
#define kiln_projectile_spawn                 fig_projectile_spawn
#define kiln_projectile_update                fig_projectile_update
#define kiln_quat_axis_angle                  fig_quat_axis_angle
#define kiln_quat_mul                         fig_quat_mul
#define kiln_quat_nlerp                       fig_quat_nlerp
#define kiln_radio_mix_seed                   fig_radio_mix_seed
#define kiln_radio_pick                       fig_radio_pick
#define kiln_rng                              fig_rng
#define kiln_rng_f32                          fig_rng_f32
#define kiln_rng_range                        fig_rng_range
#define kiln_rng_seed                         fig_rng_seed
#define kiln_rng_u32                          fig_rng_u32
#define kiln_room                             fig_room
#define kiln_room_current                     fig_room_current
#define kiln_room_draw_all                    fig_room_draw_all
#define kiln_room_first_loaded                fig_room_first_loaded
#define kiln_room_loaded                      fig_room_loaded
#define kiln_room_loaded_count                fig_room_loaded_count
#define kiln_room_next_loaded                 fig_room_next_loaded
#define kiln_room_system_init                 fig_room_system_init
#define kiln_room_system_update               fig_room_system_update
#define kiln_save                             fig_save
#define kiln_save_erase                       fig_save_erase
#define kiln_save_exists                      fig_save_exists
#define kiln_save_init                        fig_save_init
#define kiln_save_read                        fig_save_read
#define kiln_save_slots                       fig_save_slots
#define kiln_save_write                       fig_save_write
#define kiln_scene_begin                      fig_scene_begin
#define kiln_scene_depth                      fig_scene_depth
#define kiln_scene_disable_fog                fig_scene_disable_fog
#define kiln_scene_draw                       fig_scene_draw
#define kiln_scene_frustum                    fig_scene_frustum
#define kiln_scene_init                       fig_scene_init
#define kiln_scene_project                    fig_scene_project
#define kiln_scene_set_fog                    fig_scene_set_fog
#define kiln_scene_update                     fig_scene_update
#define kiln_scratch                          fig_scratch
#define kiln_scratch_alloc                    fig_scratch_alloc
#define kiln_scratch_alloc_uncached           fig_scratch_alloc_uncached
#define kiln_scratch_begin                    fig_scratch_begin
#define kiln_scratch_init                     fig_scratch_init
#define kiln_scratch_mat4fp                   fig_scratch_mat4fp
#define kiln_scratch_remaining                fig_scratch_remaining
#define kiln_sdbfs                            fig_sdbfs
#define kiln_sdbfs_key_is_dma                 fig_sdbfs_key_is_dma
#define kiln_sdbfs_mount                      fig_sdbfs_mount
#define kiln_sdbfs_unmount                    fig_sdbfs_unmount
#define kiln_sfx                              fig_sfx
#define kiln_sfx_                             fig_sfx_
#define kiln_sfx_load                         fig_sfx_load
#define kiln_sfx_play                         fig_sfx_play
#define kiln_sfx_play_ex                      fig_sfx_play_ex
#define kiln_sfx_play_pan                     fig_sfx_play_pan
#define kiln_sfx_playing                      fig_sfx_playing
#define kiln_sfx_set_freq                     fig_sfx_set_freq
#define kiln_sfx_set_pitch                    fig_sfx_set_pitch
#define kiln_sfx_set_vol_pan                  fig_sfx_set_vol_pan
#define kiln_sfx_stop                         fig_sfx_stop
#define kiln_sierp_leaves                     fig_sierp_leaves
#define kiln_sierp_morph                      fig_sierp_morph
#define kiln_sierp_negate                     fig_sierp_negate
#define kiln_sierp_regular                    fig_sierp_regular
#define kiln_sierp_rotate_y                   fig_sierp_rotate_y
#define kiln_sierp_smooth                     fig_sierp_smooth
#define kiln_skel                             fig_skel
#define kiln_skel_bone                        fig_skel_bone
#define kiln_skel_bone_pos                    fig_skel_bone_pos
#define kiln_skel_bone_push                   fig_skel_bone_push
#define kiln_skel_bone_rotate                 fig_skel_bone_rotate
#define kiln_skel_clip                        fig_skel_clip
#define kiln_skel_create                      fig_skel_create
#define kiln_skel_crossfade                   fig_skel_crossfade
#define kiln_skel_destroy                     fig_skel_destroy
#define kiln_skel_done                        fig_skel_done
#define kiln_skel_draw                        fig_skel_draw
#define kiln_skel_is_done                     fig_skel_is_done
#define kiln_skel_length                      fig_skel_length
#define kiln_skel_mask_bone                   fig_skel_mask_bone
#define kiln_skel_overlay                     fig_skel_overlay
#define kiln_skel_overlay_active              fig_skel_overlay_active
#define kiln_skel_overlay_stop                fig_skel_overlay_stop
#define kiln_skel_play                        fig_skel_play
#define kiln_skel_play_blend                  fig_skel_play_blend
#define kiln_skel_set_blend                   fig_skel_set_blend
#define kiln_skel_set_overlay_mask            fig_skel_set_overlay_mask
#define kiln_skel_set_phase                   fig_skel_set_phase
#define kiln_skel_set_speed                   fig_skel_set_speed
#define kiln_skel_time                        fig_skel_time
#define kiln_skel_update                      fig_skel_update
#define kiln_soft3d_framebuffer               fig_soft3d_framebuffer
#define kiln_soft3d_init                      fig_soft3d_init
#define kiln_soft3d_present                   fig_soft3d_present
#define kiln_soft3d_render_frame              fig_soft3d_render_frame
#define kiln_sound_init                       fig_sound_init
#define kiln_sound_play                       fig_sound_play
#define kiln_sound_stop                       fig_sound_stop
#define kiln_sound_update                     fig_sound_update
#define kiln_sound_update_listener            fig_sound_update_listener
#define kiln_splash_apply                     fig_splash_apply
#define kiln_splash_done                      fig_splash_done
#define kiln_splash_draw2d                    fig_splash_draw2d
#define kiln_splash_draw3d                    fig_splash_draw3d
#define kiln_splash_init                      fig_splash_init
#define kiln_splash_update                    fig_splash_update
#define kiln_store                            fig_store
#define kiln_store_bus_name                   fig_store_bus_name
#define kiln_store_cart_name                  fig_store_cart_name
#define kiln_store_close                      fig_store_close
#define kiln_store_crc32                      fig_store_crc32
#define kiln_store_exists                     fig_store_exists
#define kiln_store_init                       fig_store_init
#define kiln_store_kind                       fig_store_kind
#define kiln_store_kind_name                  fig_store_kind_name
#define kiln_store_log                        fig_store_log
#define kiln_store_read                       fig_store_read
#define kiln_store_selftest                   fig_store_selftest
#define kiln_store_status_name                fig_store_status_name
#define kiln_store_writable                   fig_store_writable
#define kiln_store_write                      fig_store_write
#define kiln_store_write_text                 fig_store_write_text
#define kiln_stream                           fig_stream
#define kiln_stream_admits_this_frame         fig_stream_admits_this_frame
#define kiln_stream_bytes_admitted_this_frame fig_stream_bytes_admitted_this_frame
#define kiln_stream_cancel                    fig_stream_cancel
#define kiln_stream_complete                  fig_stream_complete
#define kiln_stream_dropped_total             fig_stream_dropped_total
#define kiln_stream_first_admitted            fig_stream_first_admitted
#define kiln_stream_frame_begin               fig_stream_frame_begin
#define kiln_stream_high_water                fig_stream_high_water
#define kiln_stream_init                      fig_stream_init
#define kiln_stream_next_admitted             fig_stream_next_admitted
#define kiln_stream_pending_count             fig_stream_pending_count
#define kiln_stream_request                   fig_stream_request
#define kiln_streamio_fail_total              fig_streamio_fail_total
#define kiln_streamio_init                    fig_streamio_init
#define kiln_streamio_pump                    fig_streamio_pump
#define kiln_streamio_room_bind               fig_streamio_room_bind
#define kiln_streamio_room_on_load            fig_streamio_room_on_load
#define kiln_streamio_room_on_unload          fig_streamio_room_on_unload
#define kiln_streamio_tile_bind               fig_streamio_tile_bind
#define kiln_streamio_tile_on_load            fig_streamio_tile_on_load
#define kiln_streamio_tile_on_unload          fig_streamio_tile_on_unload
#define kiln_surface                          fig_surface
#define kiln_surface_get                      fig_surface_get
#define kiln_surface_play_footstep            fig_surface_play_footstep
#define kiln_surface_register                 fig_surface_register
#define kiln_target                           fig_target
#define kiln_target_acquire                   fig_target_acquire
#define kiln_target_draw_reticle              fig_target_draw_reticle
#define kiln_target_switch                    fig_target_switch
#define kiln_texanim                          fig_texanim
#define kiln_texanim_draw                     fig_texanim_draw
#define kiln_texanim_update                   fig_texanim_update
#define kiln_tile                             fig_tile
#define kiln_tile_center                      fig_tile_center
#define kiln_tile_first                       fig_tile_first
#define kiln_tile_flush_unload                fig_tile_flush_unload
#define kiln_tile_init                        fig_tile_init
#define kiln_tile_lookup                      fig_tile_lookup
#define kiln_tile_next                        fig_tile_next
#define kiln_tile_update                      fig_tile_update
#define kiln_tile_world_to_tile               fig_tile_world_to_tile
#define kiln_transform_free                   fig_transform_free
#define kiln_transform_init                   fig_transform_init
#define kiln_transform_pop                    fig_transform_pop
#define kiln_transform_push                   fig_transform_push
#define kiln_trigger_add                      fig_trigger_add
#define kiln_trigger_clear                    fig_trigger_clear
#define kiln_trigger_init                     fig_trigger_init
#define kiln_trigger_update                   fig_trigger_update
#define kiln_turn                             fig_turn
#define kiln_turn_advance_phase               fig_turn_advance_phase
#define kiln_turn_init                        fig_turn_init
#define kiln_turn_is_last_phase               fig_turn_is_last_phase
#define kiln_turn_round_will_advance          fig_turn_round_will_advance
#define kiln_turn_skip_to_end                 fig_turn_skip_to_end
#define kiln_twopass_render                   fig_twopass_render
#define kiln_vanim                            fig_vanim
#define kiln_vfx_                             fig_vfx_
#define kiln_vfx_clear                        fig_vfx_clear
#define kiln_vfx_set                          fig_vfx_set
#define kiln_video_close                      fig_video_close
#define kiln_video_draw                       fig_video_draw
#define kiln_video_open                       fig_video_open
#define kiln_video_update                     fig_video_update
#define kiln_voxatlas_bind                    fig_voxatlas_bind
#define kiln_voxatlas_close                   fig_voxatlas_close
#define kiln_voxatlas_fill_tile               fig_voxatlas_fill_tile
#define kiln_voxatlas_init                    fig_voxatlas_init
#define kiln_voxatlas_peek                    fig_voxatlas_peek
#define kiln_voxatlas_plot                    fig_voxatlas_plot
#define kiln_voxel                            fig_voxel
#define kiln_voxel_bounds                     fig_voxel_bounds
#define kiln_voxel_boxes                      fig_voxel_boxes
#define kiln_voxel_chunk_count                fig_voxel_chunk_count
#define kiln_voxel_clear                      fig_voxel_clear
#define kiln_voxel_dir_axes                   fig_voxel_dir_axes
#define kiln_voxel_fill                       fig_voxel_fill
#define kiln_voxel_get                        fig_voxel_get
#define kiln_voxel_in_bounds                  fig_voxel_in_bounds
#define kiln_voxel_quads                      fig_voxel_quads
#define kiln_voxel_raycast                    fig_voxel_raycast
#define kiln_voxel_set                        fig_voxel_set
#define kiln_voxel_slot_first                 fig_voxel_slot_first
#define kiln_voxel_slot_next                  fig_voxel_slot_next
#define kiln_voxel_solid_count                fig_voxel_solid_count
#define kiln_voxmesh                          fig_voxmesh
#define kiln_voxmesh_arena_init               fig_voxmesh_arena_init
#define kiln_voxmesh_arena_reset              fig_voxmesh_arena_reset
#define kiln_voxmesh_arena_used_pct           fig_voxmesh_arena_used_pct
#define kiln_voxmesh_build                    fig_voxmesh_build
#define kiln_voxmesh_draw                     fig_voxmesh_draw
#define kiln_weapon_can_fire                  fig_weapon_can_fire
#define kiln_weapon_fire                      fig_weapon_fire
#define kiln_weapon_init                      fig_weapon_init
#define kiln_weapon_reload                    fig_weapon_reload
#define kiln_weapon_update                    fig_weapon_update
#define kiln_weapons_active_def               fig_weapons_active_def
#define kiln_weapons_active_state             fig_weapons_active_state
#define kiln_weapons_can_fire                 fig_weapons_can_fire
#define kiln_weapons_fire                     fig_weapons_fire
#define kiln_weapons_init                     fig_weapons_init
#define kiln_weapons_next                     fig_weapons_next
#define kiln_weapons_prev                     fig_weapons_prev
#define kiln_weapons_reload                   fig_weapons_reload
#define kiln_weapons_switch                   fig_weapons_switch
#define kiln_weapons_update                   fig_weapons_update
#define kiln_widget_banner                    fig_widget_banner
#define kiln_widget_button                    fig_widget_button
#define kiln_widget_dice                      fig_widget_dice
#define kiln_widget_hud_strip                 fig_widget_hud_strip
#define kiln_widget_jitter                    fig_widget_jitter
#define kiln_widget_panel_skew                fig_widget_panel_skew
#define kiln_widget_results                   fig_widget_results
#define kiln_widget_style_default             fig_widget_style_default
#define kiln_widget_style_funky               fig_widget_style_funky
#define kiln_widget_tick                      fig_widget_tick
#define kiln_widget_time                      fig_widget_time

#endif /* FIG_COMPAT_H */
