/* SPDX-License-Identifier: MIT
 *
 * GENERATED by tools/schema/level_vocab.py from tools/schema/level_vocab.json.
 * Do not edit. nix/checks/level-vocab.nix regenerates this and diffs it.
 *
 * Macros only, deliberately. The engine has no use for the classname
 * strings -- fig_map_register_classname is how a GAME binds one to its
 * own profile id -- and a header that published both a FIG_LEVEL_* macro
 * set and a table would be two namespaces in one file. See CLAUDE.md:
 * "a generated header is a namespace, not just a file".
 *
 * FIG_LEVEL_MAX_FACES is brushes x 6, the way kiln_map.c always derived
 * MAX_FACES; storing 1536 would be the same arithmetic written twice.
 */
#ifndef FIG_LEVELVOCAB_H
#define FIG_LEVELVOCAB_H

#define FIG_LEVEL_MAX_BRUSHES    256
#define FIG_LEVEL_MAX_FACES      (FIG_LEVEL_MAX_BRUSHES * 6)
#define FIG_LEVEL_MAX_SPAWNS     64
#define FIG_LEVEL_MAX_CLASSNAMES 32
#define FIG_LEVEL_MAX_ENTITIES   64
#define FIG_LEVEL_MAX_COORD      32767
#define FIG_LEVEL_MAX_BRUSH_PLANES 32
#define FIG_LEVEL_MAX_FACE_VERTS   16

#endif /* FIG_LEVELVOCAB_H */
