/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 4, "exsecutor: this hospes has 32-bit addresses");

uint64_t exs_redundantia32(unsigned char *p0, uint64_t p1, uint64_t p2);
void exs_caput_lege(unsigned char *p0, unsigned char *p1, uint64_t p2);
void exs_indicium_lege(unsigned char *p0, unsigned char *p1, uint64_t p2);
void exs_recordum_lege(unsigned char *p0, unsigned char *p1, uint64_t p2);
uint64_t exs_octo_lege(unsigned char *p0, uint64_t p1);
void exs_nomen_lege(unsigned char *p0, unsigned char *p1, uint64_t p2);
uint64_t exs_caput_valet(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_caput_elige(unsigned char *p0, uint64_t p1);
uint64_t exs_indicem_numera(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_indicem_proba(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3);
uint64_t exs_indicem_quaere(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3, uint64_t p4);
uint64_t exs_arbor_percurre(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3);
uint64_t exs_arbor_descende(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_clavem_quaere(unsigned char *p0, unsigned char *p1, uint64_t p2);
uint64_t exs_documentum_proba(unsigned char *p0, uint64_t p1, unsigned char *p2);
uint64_t exs_documentum_quaere(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3, unsigned char *p4, uint64_t p5);
void exs_suffixum_percurre(unsigned char *p0, unsigned char *p1, unsigned char *p2, uint64_t p3);

uint64_t exs_redundantia32(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    unsigned char *v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v37;
    uint64_t v38;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v46;
    uint64_t v47;
    uint64_t v49;
    uint64_t v50;
    uint64_t t7;
    uint64_t t10;
    uint64_t t21;
    uint64_t t24;
    uint64_t t44;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(4294967295);
    v5 = UINT64_C(0);
    t10 = v4;
    t7 = v5;
    v10 = t10;
    v7 = t7;
    goto b2;
b2:
    v8 = (v7 < v3);
    if (v8) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v11 = exsi_add_u(v2, v7, 32);
    v12 = UINT64_C(65536);
    if (v11 >= v12) exsrt_abortus(1);
    v14 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v11 * 1);
    v15 = exsi_norm_u(exsi_ld_n(v14 + 0, 1), 8);
    v16 = exsi_norm_u(exsi_norm_u(v15, 8), 32);
    v17 = v10 ^ v16;
    v18 = UINT64_C(0);
    v19 = UINT64_C(8);
    t24 = v17;
    t21 = v18;
    v24 = t24;
    v21 = t21;
    goto b6;
b4:
    v49 = UINT64_C(4294967295);
    v50 = v10 ^ v49;
    return v50;
b5:
    v46 = UINT64_C(1);
    v47 = exsi_norm_u(v7 + v46, 32);
    t10 = v24;
    t7 = v47;
    v10 = t10;
    v7 = t7;
    goto b2;
b6:
    v22 = (v21 < v19);
    if (v22) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v25 = UINT64_C(31);
    v26 = exsi_shl_u(v24, v25, 32);
    v27 = UINT64_C(31);
    v28 = exsi_shr_u(v26, v27, 32);
    v29 = UINT64_C(1);
    v30 = (v28 == v29);
    if (v30) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    goto b5;
b9:
    v41 = UINT64_C(1);
    v42 = exsi_norm_u(v21 + v41, 32);
    t24 = v44;
    t21 = v42;
    v24 = t24;
    v21 = t21;
    goto b6;
b10:
    v32 = UINT64_C(1);
    v33 = exsi_shr_u(v24, v32, 32);
    v34 = UINT64_C(3988292384);
    v35 = v33 ^ v34;
    t44 = v35;
    v44 = t44;
    goto b12;
b11:
    v37 = UINT64_C(1);
    v38 = exsi_shr_u(v24, v37, 32);
    t44 = v38;
    v44 = t44;
    goto b12;
b12:
    goto b9;
}

void exs_caput_lege(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v27;
    uint64_t v28;
    unsigned char *v30;
    uint64_t v33;
    uint64_t v34;
    uint64_t t8;
    uint64_t t20;
    _Alignas(1) unsigned char s4[128];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = s4;
    v5 = UINT64_C(0);
    v6 = UINT64_C(0);
    t8 = v6;
    v8 = t8;
    goto b2;
b2:
    v9 = UINT64_C(128);
    v10 = (v8 < v9);
    if (v10) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v8 * 1);
    exsi_st_n(v12 + 0, 1, v5);
    v14 = UINT64_C(1);
    v15 = v8 + v14;
    t8 = v15;
    v8 = t8;
    goto b2;
b4:
    v17 = UINT64_C(0);
    v18 = UINT64_C(128);
    t20 = v17;
    v20 = t20;
    goto b5;
b5:
    v21 = (v20 < v18);
    if (v21) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v23 = exsi_add_u(v3, v20, 32);
    v24 = UINT64_C(65536);
    if (v23 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v23 * 1);
    v27 = exsi_norm_u(exsi_ld_n(v26 + 0, 1), 8);
    v28 = UINT64_C(128);
    if (v20 >= v28) exsrt_abortus(1);
    v30 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v20 * 1);
    exsi_st_n(v30 + 0, 1, v27);
    goto b8;
b7:
    __builtin_memcpy(v1, v4, 128);
    return;
b8:
    v33 = UINT64_C(1);
    v34 = exsi_norm_u(v20 + v33, 32);
    t20 = v34;
    v20 = t20;
    goto b5;
}

void exs_indicium_lege(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v27;
    uint64_t v28;
    unsigned char *v30;
    uint64_t v33;
    uint64_t v34;
    uint64_t t8;
    uint64_t t20;
    _Alignas(1) unsigned char s4[32];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = s4;
    v5 = UINT64_C(0);
    v6 = UINT64_C(0);
    t8 = v6;
    v8 = t8;
    goto b2;
b2:
    v9 = UINT64_C(32);
    v10 = (v8 < v9);
    if (v10) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v8 * 1);
    exsi_st_n(v12 + 0, 1, v5);
    v14 = UINT64_C(1);
    v15 = v8 + v14;
    t8 = v15;
    v8 = t8;
    goto b2;
b4:
    v17 = UINT64_C(0);
    v18 = UINT64_C(32);
    t20 = v17;
    v20 = t20;
    goto b5;
b5:
    v21 = (v20 < v18);
    if (v21) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v23 = exsi_add_u(v3, v20, 32);
    v24 = UINT64_C(65536);
    if (v23 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v23 * 1);
    v27 = exsi_norm_u(exsi_ld_n(v26 + 0, 1), 8);
    v28 = UINT64_C(32);
    if (v20 >= v28) exsrt_abortus(1);
    v30 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v20 * 1);
    exsi_st_n(v30 + 0, 1, v27);
    goto b8;
b7:
    __builtin_memcpy(v1, v4, 32);
    return;
b8:
    v33 = UINT64_C(1);
    v34 = exsi_norm_u(v20 + v33, 32);
    t20 = v34;
    v20 = t20;
    goto b5;
}

void exs_recordum_lege(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    unsigned char *v23;
    uint64_t v24;
    uint64_t v25;
    unsigned char *v27;
    uint64_t v30;
    uint64_t v31;
    uint64_t t17;
    _Alignas(1) unsigned char s4[8];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = s4;
    v5 = UINT64_C(0);
    exsi_st_n(v4 + 0, 1, v5);
    exsi_st_n(v4 + 1, 1, v5);
    exsi_st_n(v4 + 2, 1, v5);
    exsi_st_n(v4 + 3, 1, v5);
    exsi_st_n(v4 + 4, 1, v5);
    exsi_st_n(v4 + 5, 1, v5);
    exsi_st_n(v4 + 6, 1, v5);
    exsi_st_n(v4 + 7, 1, v5);
    v14 = UINT64_C(0);
    v15 = UINT64_C(8);
    t17 = v14;
    v17 = t17;
    goto b2;
b2:
    v18 = (v17 < v15);
    if (v18) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v20 = exsi_add_u(v3, v17, 32);
    v21 = UINT64_C(65536);
    if (v20 >= v21) exsrt_abortus(1);
    v23 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v20 * 1);
    v24 = exsi_norm_u(exsi_ld_n(v23 + 0, 1), 8);
    v25 = UINT64_C(8);
    if (v17 >= v25) exsrt_abortus(1);
    v27 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v17 * 1);
    exsi_st_n(v27 + 0, 1, v24);
    goto b5;
b4:
    __builtin_memcpy(v1, v4, 8);
    return;
b5:
    v30 = UINT64_C(1);
    v31 = exsi_norm_u(v17 + v30, 32);
    t17 = v31;
    v17 = t17;
    goto b2;
}

uint64_t exs_octo_lege(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v29;
    uint64_t v30;
    unsigned char *v32;
    uint64_t v34;
    uint64_t t16;
    _Alignas(1) unsigned char s3[8];
    _Alignas(1) unsigned char s32[8];
    v1 = p0;
    v2 = p1;
    v3 = s3;
    v4 = UINT64_C(0);
    exsi_st_n(v3 + 0, 1, v4);
    exsi_st_n(v3 + 1, 1, v4);
    exsi_st_n(v3 + 2, 1, v4);
    exsi_st_n(v3 + 3, 1, v4);
    exsi_st_n(v3 + 4, 1, v4);
    exsi_st_n(v3 + 5, 1, v4);
    exsi_st_n(v3 + 6, 1, v4);
    exsi_st_n(v3 + 7, 1, v4);
    v13 = UINT64_C(0);
    v14 = UINT64_C(8);
    t16 = v13;
    v16 = t16;
    goto b2;
b2:
    v17 = (v16 < v14);
    if (v17) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v19 = exsi_add_u(v2, v16, 32);
    v20 = UINT64_C(65536);
    if (v19 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    v23 = exsi_norm_u(exsi_ld_n(v22 + 0, 1), 8);
    v24 = UINT64_C(8);
    if (v16 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v16 * 1);
    exsi_st_n(v26 + 0, 1, v23);
    goto b5;
b4:
    v32 = s32;
    __builtin_memcpy(v32, v3, 8);
    v34 = exsi_ld_le(v32 + 0, 8);
    return v34;
b5:
    v29 = UINT64_C(1);
    v30 = exsi_norm_u(v16 + v29, 32);
    t16 = v30;
    v16 = t16;
    goto b2;
}

void exs_nomen_lege(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v27;
    uint64_t v28;
    unsigned char *v30;
    uint64_t v33;
    uint64_t v34;
    uint64_t t8;
    uint64_t t20;
    _Alignas(1) unsigned char s4[16];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = s4;
    v5 = UINT64_C(0);
    v6 = UINT64_C(0);
    t8 = v6;
    v8 = t8;
    goto b2;
b2:
    v9 = UINT64_C(16);
    v10 = (v8 < v9);
    if (v10) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v8 * 1);
    exsi_st_n(v12 + 0, 1, v5);
    v14 = UINT64_C(1);
    v15 = v8 + v14;
    t8 = v15;
    v8 = t8;
    goto b2;
b4:
    v17 = UINT64_C(0);
    v18 = UINT64_C(16);
    t20 = v17;
    v20 = t20;
    goto b5;
b5:
    v21 = (v20 < v18);
    if (v21) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v23 = exsi_add_u(v3, v20, 32);
    v24 = UINT64_C(65536);
    if (v23 >= v24) exsrt_abortus(1);
    v26 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v23 * 1);
    v27 = exsi_norm_u(exsi_ld_n(v26 + 0, 1), 8);
    v28 = UINT64_C(16);
    if (v20 >= v28) exsrt_abortus(1);
    v30 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v20 * 1);
    exsi_st_n(v30 + 0, 1, v27);
    goto b8;
b7:
    __builtin_memcpy(v1, v4, 16);
    return;
b8:
    v33 = UINT64_C(1);
    v34 = exsi_norm_u(v20 + v33, 32);
    t20 = v34;
    v20 = t20;
    goto b5;
}

uint64_t exs_caput_valet(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    unsigned char *v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v36;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v42;
    uint64_t v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    uint64_t v49;
    uint64_t v50;
    uint64_t v52;
    uint64_t v54;
    uint64_t v55;
    uint64_t v56;
    uint64_t v57;
    uint64_t v59;
    uint64_t v61;
    uint64_t v62;
    uint64_t v64;
    uint64_t v66;
    uint64_t v67;
    uint64_t v68;
    uint64_t v70;
    uint64_t v72;
    _Alignas(1) unsigned char s15[128];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(256);
    v5 = (v3 < v4);
    if (v5) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v7 = UINT64_C(0);
    return v7;
b3:
    v9 = UINT64_C(128);
    v10 = exsi_add_u(v2, v9, 32);
    v11 = (v10 > v3);
    if (v11) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v13 = UINT64_C(0);
    return v13;
b5:
    v15 = s15;
    exs_caput_lege(v15, v1, v2);
    v17 = exsi_norm_u(exsi_ld_be(v15 + 0, 4), 32);
    v18 = UINT64_C(1398031426);
    v19 = (v17 != v18);
    if (v19) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v21 = UINT64_C(0);
    return v21;
b7:
    v23 = exsi_norm_u(exsi_ld_le(v15 + 4, 4), 32);
    v24 = UINT64_C(3);
    v25 = (v23 != v24);
    if (v25) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v27 = UINT64_C(0);
    return v27;
b9:
    v29 = exsi_norm_u(exsi_ld_le(v15 + 72, 4), 32);
    v30 = UINT64_C(72);
    v31 = exs_redundantia32(v1, v2, v30);
    v32 = (v29 != v31);
    if (v32) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v34 = UINT64_C(0);
    return v34;
b11:
    v36 = exsi_norm_u(v3, 32);
    v37 = exsi_ld_le(v15 + 24, 8);
    v38 = (v37 > v36);
    if (v38) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v40 = UINT64_C(0);
    return v40;
b13:
    v42 = exsi_ld_le(v15 + 16, 8);
    v43 = exsi_ld_le(v15 + 24, 8);
    v44 = exsi_sub_u(v36, v43, 64);
    v45 = (v42 > v44);
    if (v45) {
        goto b14;
    } else {
        goto b15;
    }
b14:
    v47 = UINT64_C(0);
    return v47;
b15:
    v49 = exsi_ld_le(v15 + 48, 8);
    v50 = (v49 > v36);
    if (v50) {
        goto b16;
    } else {
        goto b17;
    }
b16:
    v52 = UINT64_C(0);
    return v52;
b17:
    v54 = exsi_ld_le(v15 + 40, 8);
    v55 = exsi_ld_le(v15 + 48, 8);
    v56 = exsi_sub_u(v36, v55, 64);
    v57 = (v54 > v56);
    if (v57) {
        goto b18;
    } else {
        goto b19;
    }
b18:
    v59 = UINT64_C(0);
    return v59;
b19:
    v61 = exsi_ld_le(v15 + 64, 8);
    v62 = (v61 > v36);
    if (v62) {
        goto b20;
    } else {
        goto b21;
    }
b20:
    v64 = UINT64_C(0);
    return v64;
b21:
    v66 = exsi_ld_le(v15 + 48, 8);
    v67 = UINT64_C(8);
    v68 = (v66 < v67);
    if (v68) {
        goto b22;
    } else {
        goto b23;
    }
b22:
    v70 = UINT64_C(0);
    return v70;
b23:
    v72 = UINT64_C(1);
    return v72;
}

uint64_t exs_caput_elige(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    unsigned char *v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v32;
    uint64_t v34;
    _Alignas(1) unsigned char s22[128];
    _Alignas(1) unsigned char s25[128];
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = exs_caput_valet(v1, v3, v2);
    v5 = UINT64_C(128);
    v6 = exs_caput_valet(v1, v5, v2);
    v7 = UINT64_C(0);
    v8 = (v4 == v7);
    if (v8) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v10 = UINT64_C(0);
    v11 = (v6 == v10);
    if (v11) {
        goto b4;
    } else {
        goto b5;
    }
b3:
    v17 = UINT64_C(0);
    v18 = (v6 == v17);
    if (v18) {
        goto b6;
    } else {
        goto b7;
    }
b4:
    v13 = UINT64_C(256);
    return v13;
b5:
    v15 = UINT64_C(128);
    return v15;
b6:
    v20 = UINT64_C(0);
    return v20;
b7:
    v22 = s22;
    v23 = UINT64_C(0);
    exs_caput_lege(v22, v1, v23);
    v25 = s25;
    v26 = UINT64_C(128);
    exs_caput_lege(v25, v1, v26);
    v28 = exsi_ld_le(v25 + 8, 8);
    v29 = exsi_ld_le(v22 + 8, 8);
    v30 = (v28 > v29);
    if (v30) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v32 = UINT64_C(128);
    return v32;
b9:
    v34 = UINT64_C(0);
    return v34;
}

uint64_t exs_indicem_numera(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(8);
    v5 = (v3 < v4);
    if (v5) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v7 = UINT64_C(65536);
    return v7;
b3:
    v9 = exs_octo_lege(v1, v2);
    v10 = UINT64_C(2048);
    v11 = exsi_norm_u(v10, 32);
    v12 = (v9 > v11);
    if (v12) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v14 = UINT64_C(65536);
    return v14;
b5:
    v16 = exsi_norm_u(v9, 32);
    v17 = UINT64_C(8);
    v18 = UINT64_C(32);
    v19 = exsi_mul_u(v16, v18, 32);
    v20 = exsi_add_u(v17, v19, 32);
    v21 = (v20 > v3);
    if (v21) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v23 = UINT64_C(65536);
    return v23;
b7:
    return v16;
}

uint64_t exs_indicem_proba(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t t8;
    _Alignas(1) unsigned char s11[32];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = exsi_norm_u(v4, 32);
    v6 = UINT64_C(0);
    t8 = v6;
    v8 = t8;
    goto b2;
b2:
    v9 = (v8 < v3);
    if (v9) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v11 = s11;
    v12 = UINT64_C(8);
    v13 = exsi_add_u(v2, v12, 32);
    v14 = UINT64_C(32);
    v15 = exsi_mul_u(v8, v14, 32);
    v16 = exsi_add_u(v13, v15, 32);
    exs_indicium_lege(v11, v1, v16);
    v18 = exsi_ld_le(v11 + 16, 8);
    v19 = UINT64_C(8);
    v20 = (v18 < v19);
    if (v20) {
        goto b6;
    } else {
        goto b7;
    }
b4:
    v40 = UINT64_C(0);
    return v40;
b5:
    v37 = UINT64_C(1);
    v38 = exsi_norm_u(v8 + v37, 32);
    t8 = v38;
    v8 = t8;
    goto b2;
b6:
    v22 = UINT64_C(1);
    return v22;
b7:
    v24 = exsi_norm_u(exsi_ld_le(v11 + 24, 4), 32);
    v25 = exsi_norm_u(v24, 32);
    v26 = (v25 > v5);
    if (v26) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v28 = UINT64_C(1);
    return v28;
b9:
    v30 = exsi_ld_le(v11 + 16, 8);
    v31 = exsi_sub_u(v5, v25, 64);
    v32 = (v30 > v31);
    if (v32) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v34 = UINT64_C(1);
    return v34;
b11:
    goto b5;
}

uint64_t exs_indicem_quaere(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3, uint64_t p4)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    unsigned char *v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v27;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v35;
    uint64_t v37;
    uint64_t v38;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v49;
    uint64_t v50;
    uint64_t t8;
    uint64_t t9;
    uint64_t t49;
    uint64_t t50;
    _Alignas(1) unsigned char s16[32];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = p4;
    v6 = UINT64_C(0);
    t9 = v3;
    t8 = v6;
    v9 = t9;
    v8 = t8;
    goto b2;
b2:
    v10 = (v8 < v9);
    if (v10) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v12 = exsi_sub_u(v9, v8, 32);
    v13 = UINT64_C(1);
    v14 = exsi_shr_u(v12, v13, 32);
    v15 = exsi_add_u(v8, v14, 32);
    v16 = s16;
    v17 = UINT64_C(8);
    v18 = exsi_add_u(v2, v17, 32);
    v19 = UINT64_C(32);
    v20 = exsi_mul_u(v15, v19, 32);
    v21 = exsi_add_u(v18, v20, 32);
    exs_indicium_lege(v16, v1, v21);
    v23 = exsi_ld_be(v16 + 0, 8);
    v24 = (v23 == v4);
    if (v24) {
        goto b5;
    } else {
        goto b6;
    }
b4:
    return v3;
b5:
    v26 = exsi_ld_be(v16 + 8, 8);
    v27 = (v26 == v5);
    if (v27) {
        goto b7;
    } else {
        goto b8;
    }
b6:
    v31 = exsi_ld_be(v16 + 0, 8);
    v32 = (v31 < v4);
    if (v32) {
        goto b9;
    } else {
        goto b10;
    }
b7:
    return v15;
b8:
    goto b6;
b9:
    v34 = UINT64_C(1);
    v35 = exsi_add_u(v15, v34, 32);
    t50 = v9;
    t49 = v35;
    v50 = t50;
    v49 = t49;
    goto b11;
b10:
    v37 = exsi_ld_be(v16 + 0, 8);
    v38 = (v37 > v4);
    if (v38) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    t9 = v50;
    t8 = v49;
    v9 = t9;
    v8 = t8;
    goto b2;
b12:
    t50 = v15;
    t49 = v8;
    v50 = t50;
    v49 = t49;
    goto b11;
b13:
    v41 = exsi_ld_be(v16 + 8, 8);
    v42 = (v41 < v5);
    if (v42) {
        goto b14;
    } else {
        goto b15;
    }
b14:
    v44 = UINT64_C(1);
    v45 = exsi_add_u(v15, v44, 32);
    t50 = v9;
    t49 = v45;
    v50 = t50;
    v49 = t49;
    goto b11;
b15:
    t50 = v15;
    t49 = v8;
    v50 = t50;
    v49 = t49;
    goto b11;
}

uint64_t exs_arbor_percurre(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    uint64_t v4;
    unsigned char *v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    unsigned char *v13;
    uint64_t v15;
    uint64_t v16;
    unsigned char *v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v26;
    uint64_t v28;
    uint64_t v29;
    unsigned char *v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    unsigned char *v39;
    uint64_t v41;
    uint64_t v42;
    unsigned char *v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    unsigned char *v52;
    uint64_t v54;
    uint64_t v55;
    unsigned char *v57;
    uint64_t v58;
    uint64_t v59;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    unsigned char *v65;
    uint64_t v67;
    uint64_t v68;
    uint64_t v70;
    uint64_t v71;
    uint64_t v72;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v76;
    uint64_t v78;
    uint64_t v79;
    uint64_t v80;
    uint64_t v82;
    uint64_t v83;
    uint64_t v84;
    uint64_t v86;
    uint64_t v87;
    uint64_t v88;
    uint64_t v89;
    uint64_t v91;
    uint64_t v93;
    uint64_t v94;
    uint64_t v95;
    uint64_t v96;
    uint64_t v97;
    uint64_t v98;
    uint64_t v100;
    uint64_t v102;
    uint64_t v103;
    uint64_t v104;
    uint64_t v105;
    uint64_t v106;
    uint64_t v108;
    uint64_t v110;
    uint64_t v111;
    uint64_t v112;
    uint64_t v114;
    unsigned char *v116;
    uint64_t v117;
    uint64_t v118;
    unsigned char *v120;
    unsigned char *v122;
    uint64_t v123;
    unsigned char *v125;
    uint64_t v127;
    unsigned char *v129;
    uint64_t v131;
    unsigned char *v133;
    uint64_t v135;
    uint64_t v136;
    unsigned char *v138;
    uint64_t v140;
    unsigned char *v142;
    uint64_t v144;
    uint64_t v145;
    unsigned char *v147;
    uint64_t v149;
    uint64_t v150;
    uint64_t v151;
    uint64_t v152;
    uint64_t v154;
    uint64_t v155;
    uint64_t v156;
    unsigned char *v158;
    uint64_t v159;
    uint64_t v160;
    unsigned char *v162;
    uint64_t v163;
    uint64_t v164;
    uint64_t v166;
    uint64_t v167;
    uint64_t v168;
    uint64_t v170;
    uint64_t v172;
    unsigned char *v174;
    uint64_t v175;
    uint64_t v176;
    unsigned char *v178;
    uint64_t v179;
    uint64_t v180;
    uint64_t v181;
    uint64_t v182;
    unsigned char *v184;
    uint64_t v185;
    unsigned char *v186;
    uint64_t v187;
    unsigned char *v189;
    uint64_t v191;
    uint64_t v192;
    uint64_t v193;
    unsigned char *v195;
    uint64_t v196;
    uint64_t v197;
    uint64_t v198;
    uint64_t v199;
    unsigned char *v201;
    uint64_t v203;
    uint64_t v205;
    uint64_t v206;
    uint64_t v207;
    uint64_t v209;
    uint64_t v211;
    uint64_t v212;
    unsigned char *v214;
    uint64_t v215;
    uint64_t v216;
    uint64_t v217;
    uint64_t v218;
    unsigned char *v220;
    uint64_t v221;
    uint64_t v222;
    uint64_t v223;
    uint64_t v225;
    uint64_t v226;
    uint64_t v227;
    uint64_t v229;
    uint64_t v231;
    uint64_t v232;
    uint64_t v233;
    uint64_t v234;
    uint64_t v235;
    uint64_t v236;
    uint64_t v238;
    uint64_t v240;
    uint64_t v241;
    uint64_t v242;
    uint64_t v244;
    unsigned char *v246;
    uint64_t v247;
    uint64_t v249;
    uint64_t v250;
    uint64_t v251;
    unsigned char *v253;
    uint64_t v254;
    uint64_t v255;
    unsigned char *v256;
    uint64_t v257;
    unsigned char *v259;
    uint64_t v261;
    unsigned char *v262;
    uint64_t v263;
    unsigned char *v265;
    uint64_t v267;
    unsigned char *v268;
    uint64_t v269;
    unsigned char *v271;
    uint64_t v273;
    uint64_t v274;
    uint64_t v276;
    uint64_t v277;
    uint64_t v279;
    uint64_t v281;
    uint64_t v282;
    uint64_t v283;
    uint64_t v284;
    uint64_t v286;
    uint64_t v288;
    uint64_t v289;
    uint64_t v290;
    uint64_t v291;
    uint64_t v292;
    uint64_t v293;
    uint64_t v294;
    uint64_t v296;
    uint64_t v298;
    uint64_t v299;
    uint64_t v300;
    uint64_t v301;
    uint64_t v303;
    uint64_t v305;
    uint64_t v306;
    uint64_t v307;
    unsigned char *v309;
    uint64_t v310;
    uint64_t v311;
    uint64_t v312;
    unsigned char *v314;
    uint64_t v318;
    uint64_t v319;
    uint64_t v320;
    uint64_t v321;
    uint64_t v325;
    uint64_t t9;
    uint64_t t22;
    uint64_t t35;
    uint64_t t48;
    uint64_t t61;
    uint64_t t78;
    uint64_t t82;
    uint64_t t86;
    uint64_t t103;
    uint64_t t110;
    uint64_t t117;
    uint64_t t281;
    uint64_t t292;
    uint64_t t318;
    uint64_t t319;
    _Alignas(4) unsigned char s5[4100];
    _Alignas(4) unsigned char s18[4100];
    _Alignas(4) unsigned char s31[4100];
    _Alignas(4) unsigned char s44[4100];
    _Alignas(4) unsigned char s57[4100];
    _Alignas(1) unsigned char s246[16];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = s5;
    v6 = UINT64_C(0);
    v7 = UINT64_C(0);
    t9 = v7;
    v9 = t9;
    goto b2;
b2:
    v10 = UINT64_C(1025);
    v11 = (v9 < v10);
    if (v11) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v13 = (unsigned char *)((uintptr_t)v5 + (uintptr_t)v9 * 4);
    exsi_st_n(v13 + 0, 4, v6);
    v15 = UINT64_C(1);
    v16 = v9 + v15;
    t9 = v16;
    v9 = t9;
    goto b2;
b4:
    v18 = s18;
    v19 = UINT64_C(0);
    v20 = UINT64_C(0);
    t22 = v20;
    v22 = t22;
    goto b5;
b5:
    v23 = UINT64_C(1025);
    v24 = (v22 < v23);
    if (v24) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v26 = (unsigned char *)((uintptr_t)v18 + (uintptr_t)v22 * 4);
    exsi_st_n(v26 + 0, 4, v19);
    v28 = UINT64_C(1);
    v29 = v22 + v28;
    t22 = v29;
    v22 = t22;
    goto b5;
b7:
    v31 = s31;
    v32 = UINT64_C(0);
    v33 = UINT64_C(0);
    t35 = v33;
    v35 = t35;
    goto b8;
b8:
    v36 = UINT64_C(1025);
    v37 = (v35 < v36);
    if (v37) {
        goto b9;
    } else {
        goto b10;
    }
b9:
    v39 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v35 * 4);
    exsi_st_n(v39 + 0, 4, v32);
    v41 = UINT64_C(1);
    v42 = v35 + v41;
    t35 = v42;
    v35 = t35;
    goto b8;
b10:
    v44 = s44;
    v45 = UINT64_C(0);
    v46 = UINT64_C(0);
    t48 = v46;
    v48 = t48;
    goto b11;
b11:
    v49 = UINT64_C(1025);
    v50 = (v48 < v49);
    if (v50) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v52 = (unsigned char *)((uintptr_t)v44 + (uintptr_t)v48 * 4);
    exsi_st_n(v52 + 0, 4, v45);
    v54 = UINT64_C(1);
    v55 = v48 + v54;
    t48 = v55;
    v48 = t48;
    goto b11;
b13:
    v57 = s57;
    v58 = UINT64_C(0);
    v59 = UINT64_C(0);
    t61 = v59;
    v61 = t61;
    goto b14;
b14:
    v62 = UINT64_C(1025);
    v63 = (v61 < v62);
    if (v63) {
        goto b15;
    } else {
        goto b16;
    }
b15:
    v65 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v61 * 4);
    exsi_st_n(v65 + 0, 4, v58);
    v67 = UINT64_C(1);
    v68 = v61 + v67;
    t61 = v68;
    v61 = t61;
    goto b14;
b16:
    v70 = UINT64_C(0);
    v71 = UINT64_C(1);
    v72 = UINT64_C(0);
    v73 = UINT64_C(0);
    v74 = UINT64_C(0);
    v75 = UINT64_C(1);
    v76 = UINT64_C(1);
    t117 = v73;
    t110 = v72;
    t103 = v71;
    t86 = v70;
    t82 = v74;
    t78 = v75;
    v117 = t117;
    v110 = t110;
    v103 = t103;
    v86 = t86;
    v82 = t82;
    v78 = t78;
    goto b17;
b17:
    v79 = UINT64_C(1);
    v80 = (v78 == v79);
    if (v80) {
        goto b18;
    } else {
        t319 = v76;
        v319 = t319;
        goto b19;
    }
b18:
    v83 = UINT64_C(0);
    v84 = (v82 == v83);
    if (v84) {
        goto b20;
    } else {
        goto b21;
    }
b19:
    v320 = UINT64_C(1);
    v321 = (v319 == v320);
    if (v321) {
        goto b53;
    } else {
        goto b54;
    }
b20:
    v87 = UINT64_C(8);
    v88 = exsi_add_u(v86, v87, 32);
    v89 = (v88 > v4);
    if (v89) {
        goto b22;
    } else {
        goto b23;
    }
b21:
    v154 = UINT64_C(1);
    v155 = exsi_sub_u(v110, v154, 32);
    v156 = UINT64_C(1025);
    if (v155 >= v156) exsrt_abortus(1);
    v158 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v155 * 4);
    v159 = exsi_norm_u(exsi_ld_n(v158 + 0, 4), 32);
    v160 = UINT64_C(1025);
    if (v155 >= v160) exsrt_abortus(1);
    v162 = (unsigned char *)((uintptr_t)v18 + (uintptr_t)v155 * 4);
    v163 = exsi_norm_u(exsi_ld_n(v162 + 0, 4), 32);
    v164 = (v159 < v163);
    if (v164) {
        goto b30;
    } else {
        goto b31;
    }
b22:
    v91 = UINT64_C(0);
    t319 = v91;
    v319 = t319;
    goto b19;
b23:
    v93 = exsi_add_u(v3, v86, 32);
    v94 = exs_octo_lege(v2, v93);
    v95 = UINT64_C(8);
    v96 = exsi_add_u(v86, v95, 32);
    v97 = UINT64_C(256);
    v98 = (v94 > v97);
    if (v98) {
        goto b24;
    } else {
        goto b25;
    }
b24:
    v100 = UINT64_C(0);
    t319 = v100;
    v319 = t319;
    goto b19;
b25:
    v102 = exsi_norm_u(v94, 32);
    v104 = exsi_add_u(v103, v102, 32);
    v105 = UINT64_C(2048);
    v106 = (v104 > v105);
    if (v106) {
        goto b26;
    } else {
        goto b27;
    }
b26:
    v108 = UINT64_C(0);
    t319 = v108;
    v319 = t319;
    goto b19;
b27:
    v111 = UINT64_C(1025);
    v112 = (v110 >= v111);
    if (v112) {
        goto b28;
    } else {
        goto b29;
    }
b28:
    v114 = UINT64_C(0);
    t319 = v114;
    v319 = t319;
    goto b19;
b29:
    v116 = (unsigned char *)((uintptr_t)v1 + 4);
    v118 = UINT64_C(2048);
    if (v117 >= v118) exsrt_abortus(1);
    v120 = (unsigned char *)((uintptr_t)v116 + (uintptr_t)v117 * 4);
    exsi_st_n(v120 + 0, 4, v103);
    v122 = (unsigned char *)((uintptr_t)v1 + 8196);
    v123 = UINT64_C(2048);
    if (v117 >= v123) exsrt_abortus(1);
    v125 = (unsigned char *)((uintptr_t)v122 + (uintptr_t)v117 * 4);
    exsi_st_n(v125 + 0, 4, v102);
    v127 = UINT64_C(1025);
    if (v110 >= v127) exsrt_abortus(1);
    v129 = (unsigned char *)((uintptr_t)v5 + (uintptr_t)v110 * 4);
    exsi_st_n(v129 + 0, 4, v117);
    v131 = UINT64_C(1025);
    if (v110 >= v131) exsrt_abortus(1);
    v133 = (unsigned char *)((uintptr_t)v18 + (uintptr_t)v110 * 4);
    exsi_st_n(v133 + 0, 4, v102);
    v135 = UINT64_C(0);
    v136 = UINT64_C(1025);
    if (v110 >= v136) exsrt_abortus(1);
    v138 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v110 * 4);
    exsi_st_n(v138 + 0, 4, v135);
    v140 = UINT64_C(1025);
    if (v110 >= v140) exsrt_abortus(1);
    v142 = (unsigned char *)((uintptr_t)v44 + (uintptr_t)v110 * 4);
    exsi_st_n(v142 + 0, 4, v103);
    v144 = UINT64_C(0);
    v145 = UINT64_C(1025);
    if (v110 >= v145) exsrt_abortus(1);
    v147 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v110 * 4);
    exsi_st_n(v147 + 0, 4, v144);
    v149 = exsi_add_u(v103, v102, 32);
    v150 = UINT64_C(1);
    v151 = exsi_add_u(v110, v150, 32);
    v152 = UINT64_C(1);
    t117 = v117;
    t110 = v151;
    t103 = v149;
    t86 = v96;
    t82 = v152;
    t78 = v78;
    v117 = t117;
    v110 = t110;
    v103 = t103;
    v86 = t86;
    v82 = t82;
    v78 = t78;
    goto b17;
b30:
    v166 = UINT64_C(1);
    v167 = exsi_add_u(v86, v166, 32);
    v168 = (v167 > v4);
    if (v168) {
        goto b32;
    } else {
        goto b33;
    }
b31:
    v205 = UINT64_C(1);
    v206 = exsi_add_u(v86, v205, 32);
    v207 = (v206 > v4);
    if (v207) {
        goto b34;
    } else {
        goto b35;
    }
b32:
    v170 = UINT64_C(0);
    t319 = v170;
    v319 = t319;
    goto b19;
b33:
    v172 = UINT64_C(1025);
    if (v155 >= v172) exsrt_abortus(1);
    v174 = (unsigned char *)((uintptr_t)v44 + (uintptr_t)v155 * 4);
    v175 = exsi_norm_u(exsi_ld_n(v174 + 0, 4), 32);
    v176 = UINT64_C(1025);
    if (v155 >= v176) exsrt_abortus(1);
    v178 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v155 * 4);
    v179 = exsi_norm_u(exsi_ld_n(v178 + 0, 4), 32);
    v180 = exsi_add_u(v175, v179, 32);
    v181 = exsi_add_u(v3, v86, 32);
    v182 = UINT64_C(65536);
    if (v181 >= v182) exsrt_abortus(1);
    v184 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v181 * 1);
    v185 = exsi_norm_u(exsi_ld_n(v184 + 0, 1), 8);
    v186 = (unsigned char *)((uintptr_t)v1 + 18436);
    v187 = UINT64_C(2048);
    if (v180 >= v187) exsrt_abortus(1);
    v189 = (unsigned char *)((uintptr_t)v186 + (uintptr_t)v180 * 1);
    exsi_st_n(v189 + 0, 1, v185);
    v191 = UINT64_C(1);
    v192 = exsi_add_u(v86, v191, 32);
    v193 = UINT64_C(1025);
    if (v155 >= v193) exsrt_abortus(1);
    v195 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v155 * 4);
    v196 = exsi_norm_u(exsi_ld_n(v195 + 0, 4), 32);
    v197 = UINT64_C(1);
    v198 = exsi_add_u(v196, v197, 32);
    v199 = UINT64_C(1025);
    if (v155 >= v199) exsrt_abortus(1);
    v201 = (unsigned char *)((uintptr_t)v31 + (uintptr_t)v155 * 4);
    exsi_st_n(v201 + 0, 4, v198);
    v203 = UINT64_C(0);
    t117 = v180;
    t110 = v110;
    t103 = v103;
    t86 = v192;
    t82 = v203;
    t78 = v78;
    v117 = t117;
    v110 = t110;
    v103 = t103;
    v86 = t86;
    v82 = t82;
    v78 = t78;
    goto b17;
b34:
    v209 = UINT64_C(0);
    t319 = v209;
    v319 = t319;
    goto b19;
b35:
    v211 = exsi_add_u(v3, v86, 32);
    v212 = UINT64_C(65536);
    if (v211 >= v212) exsrt_abortus(1);
    v214 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v211 * 1);
    v215 = exsi_norm_u(exsi_ld_n(v214 + 0, 1), 8);
    v216 = UINT64_C(1);
    v217 = exsi_add_u(v86, v216, 32);
    v218 = UINT64_C(1025);
    if (v155 >= v218) exsrt_abortus(1);
    v220 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v155 * 4);
    v221 = exsi_norm_u(exsi_ld_n(v220 + 0, 4), 32);
    v222 = UINT64_C(1);
    v223 = (v215 == v222);
    if (v223) {
        goto b36;
    } else {
        goto b37;
    }
b36:
    v225 = UINT64_C(8);
    v226 = exsi_add_u(v217, v225, 32);
    v227 = (v226 > v4);
    if (v227) {
        goto b38;
    } else {
        goto b39;
    }
b37:
    v276 = UINT64_C(0);
    v277 = (v215 != v276);
    if (v277) {
        goto b45;
    } else {
        t292 = v221;
        t281 = v217;
        v292 = t292;
        v281 = t281;
        goto b44;
    }
b38:
    v229 = UINT64_C(0);
    t319 = v229;
    v319 = t319;
    goto b19;
b39:
    v231 = exsi_add_u(v3, v217, 32);
    v232 = exs_octo_lege(v2, v231);
    v233 = UINT64_C(8);
    v234 = exsi_add_u(v217, v233, 32);
    v235 = UINT64_C(16);
    v236 = (v232 != v235);
    if (v236) {
        goto b40;
    } else {
        goto b41;
    }
b40:
    v238 = UINT64_C(0);
    t319 = v238;
    v319 = t319;
    goto b19;
b41:
    v240 = UINT64_C(16);
    v241 = exsi_add_u(v234, v240, 32);
    v242 = (v241 > v4);
    if (v242) {
        goto b42;
    } else {
        goto b43;
    }
b42:
    v244 = UINT64_C(0);
    t319 = v244;
    v319 = t319;
    goto b19;
b43:
    v246 = s246;
    v247 = exsi_add_u(v3, v234, 32);
    exs_nomen_lege(v246, v2, v247);
    v249 = UINT64_C(16);
    v250 = exsi_add_u(v234, v249, 32);
    v251 = UINT64_C(1025);
    if (v155 >= v251) exsrt_abortus(1);
    v253 = (unsigned char *)((uintptr_t)v5 + (uintptr_t)v155 * 4);
    v254 = exsi_norm_u(exsi_ld_n(v253 + 0, 4), 32);
    v255 = UINT64_C(1);
    v256 = (unsigned char *)((uintptr_t)v1 + 16388);
    v257 = UINT64_C(2048);
    if (v254 >= v257) exsrt_abortus(1);
    v259 = (unsigned char *)((uintptr_t)v256 + (uintptr_t)v254 * 1);
    exsi_st_n(v259 + 0, 1, v255);
    v261 = exsi_ld_be(v246 + 0, 8);
    v262 = (unsigned char *)((uintptr_t)v1 + 20484);
    v263 = UINT64_C(2048);
    if (v254 >= v263) exsrt_abortus(1);
    v265 = (unsigned char *)((uintptr_t)v262 + (uintptr_t)v254 * 8);
    exsi_st_n(v265 + 0, 8, v261);
    v267 = exsi_ld_be(v246 + 8, 8);
    v268 = (unsigned char *)((uintptr_t)v1 + 36868);
    v269 = UINT64_C(2048);
    if (v254 >= v269) exsrt_abortus(1);
    v271 = (unsigned char *)((uintptr_t)v268 + (uintptr_t)v254 * 8);
    exsi_st_n(v271 + 0, 8, v267);
    v273 = UINT64_C(1);
    v274 = exsi_add_u(v221, v273, 32);
    t292 = v274;
    t281 = v250;
    v292 = t292;
    v281 = t281;
    goto b44;
b44:
    v282 = UINT64_C(8);
    v283 = exsi_add_u(v281, v282, 32);
    v284 = (v283 > v4);
    if (v284) {
        goto b46;
    } else {
        goto b47;
    }
b45:
    v279 = UINT64_C(0);
    t319 = v279;
    v319 = t319;
    goto b19;
b46:
    v286 = UINT64_C(0);
    t319 = v286;
    v319 = t319;
    goto b19;
b47:
    v288 = exsi_add_u(v3, v281, 32);
    v289 = exs_octo_lege(v2, v288);
    v290 = UINT64_C(8);
    v291 = exsi_add_u(v281, v290, 32);
    v293 = exsi_norm_u(v292, 32);
    v294 = (v289 != v293);
    if (v294) {
        goto b48;
    } else {
        goto b49;
    }
b48:
    v296 = UINT64_C(0);
    t319 = v296;
    v319 = t319;
    goto b19;
b49:
    v298 = UINT64_C(1);
    v299 = exsi_sub_u(v110, v298, 32);
    v300 = UINT64_C(0);
    v301 = (v299 == v300);
    if (v301) {
        goto b50;
    } else {
        goto b51;
    }
b50:
    v303 = UINT64_C(0);
    t318 = v303;
    v318 = t318;
    goto b52;
b51:
    v305 = UINT64_C(1);
    v306 = exsi_sub_u(v299, v305, 32);
    v307 = UINT64_C(1025);
    if (v306 >= v307) exsrt_abortus(1);
    v309 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v306 * 4);
    v310 = exsi_norm_u(exsi_ld_n(v309 + 0, 4), 32);
    v311 = exsi_add_u(v310, v292, 32);
    v312 = UINT64_C(1025);
    if (v306 >= v312) exsrt_abortus(1);
    v314 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v306 * 4);
    exsi_st_n(v314 + 0, 4, v311);
    t318 = v78;
    v318 = t318;
    goto b52;
b52:
    t117 = v117;
    t110 = v299;
    t103 = v103;
    t86 = v291;
    t82 = v82;
    t78 = v318;
    v117 = t117;
    v110 = t110;
    v103 = t103;
    v86 = t86;
    v82 = t82;
    v78 = t78;
    goto b17;
b53:
    exsi_st_n(v1 + 0, 4, v103);
    goto b54;
b54:
    v325 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    return v325;
}

uint64_t exs_arbor_descende(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    unsigned char *v7;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v10;
    uint64_t v11;
    unsigned char *v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    unsigned char *v24;
    uint64_t v25;
    uint64_t v26;
    unsigned char *v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v32;
    uint64_t v34;
    uint64_t v36;
    uint64_t v37;
    uint64_t v41;
    uint64_t v42;
    uint64_t v43;
    uint64_t t16;
    uint64_t t17;
    uint64_t t41;
    uint64_t t42;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = (unsigned char *)((uintptr_t)v1 + 4);
    v5 = UINT64_C(2048);
    if (v2 >= v5) exsrt_abortus(1);
    v7 = (unsigned char *)((uintptr_t)v4 + (uintptr_t)v2 * 4);
    v8 = exsi_norm_u(exsi_ld_n(v7 + 0, 4), 32);
    v9 = UINT64_C(0);
    v10 = (unsigned char *)((uintptr_t)v1 + 8196);
    v11 = UINT64_C(2048);
    if (v2 >= v11) exsrt_abortus(1);
    v13 = (unsigned char *)((uintptr_t)v10 + (uintptr_t)v2 * 4);
    v14 = exsi_norm_u(exsi_ld_n(v13 + 0, 4), 32);
    t17 = v14;
    t16 = v9;
    v17 = t17;
    v16 = t16;
    goto b2;
b2:
    v18 = (v16 < v17);
    if (v18) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v20 = exsi_sub_u(v17, v16, 32);
    v21 = UINT64_C(1);
    v22 = exsi_shr_u(v20, v21, 32);
    v23 = exsi_add_u(v16, v22, 32);
    v24 = (unsigned char *)((uintptr_t)v1 + 18436);
    v25 = exsi_add_u(v8, v23, 32);
    v26 = UINT64_C(2048);
    if (v25 >= v26) exsrt_abortus(1);
    v28 = (unsigned char *)((uintptr_t)v24 + (uintptr_t)v25 * 1);
    v29 = exsi_norm_u(exsi_ld_n(v28 + 0, 1), 8);
    v30 = (v29 == v3);
    if (v30) {
        goto b5;
    } else {
        goto b6;
    }
b4:
    v43 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    return v43;
b5:
    v32 = exsi_add_u(v8, v23, 32);
    return v32;
b6:
    v34 = (v29 < v3);
    if (v34) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v36 = UINT64_C(1);
    v37 = exsi_add_u(v23, v36, 32);
    t42 = v17;
    t41 = v37;
    v42 = t42;
    v41 = t41;
    goto b9;
b8:
    t42 = v23;
    t41 = v16;
    v42 = t42;
    v41 = t41;
    goto b9;
b9:
    t17 = v42;
    t16 = v41;
    v17 = t17;
    v16 = t16;
    goto b2;
}

uint64_t exs_clavem_quaere(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    unsigned char *v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v38;
    uint64_t v41;
    uint64_t v42;
    uint64_t t23;
    uint64_t t29;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    v5 = UINT64_C(0);
    v6 = (v4 == v5);
    if (v6) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v8 = UINT64_C(0);
    return v8;
b3:
    v10 = UINT64_C(0);
    v11 = (v3 == v10);
    if (v11) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v13 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    return v13;
b5:
    v15 = UINT64_C(1024);
    v16 = (v3 > v15);
    if (v16) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v18 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    return v18;
b7:
    v20 = UINT64_C(0);
    v21 = UINT64_C(0);
    t29 = v20;
    t23 = v21;
    v29 = t29;
    v23 = t23;
    goto b8;
b8:
    v24 = (v23 < v3);
    if (v24) {
        goto b9;
    } else {
        goto b10;
    }
b9:
    v26 = UINT64_C(1);
    v27 = exsi_sub_u(v3, v26, 32);
    v28 = exsi_sub_u(v27, v23, 32);
    v30 = UINT64_C(1024);
    if (v28 >= v30) exsrt_abortus(1);
    v32 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v28 * 1);
    v33 = exsi_norm_u(exsi_ld_n(v32 + 0, 1), 8);
    v34 = exs_arbor_descende(v1, v29, v33);
    v35 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    v36 = (v34 >= v35);
    if (v36) {
        goto b12;
    } else {
        goto b13;
    }
b10:
    return v29;
b11:
    v41 = UINT64_C(1);
    v42 = exsi_norm_u(v23 + v41, 32);
    t29 = v34;
    t23 = v42;
    v29 = t29;
    v23 = t23;
    goto b8;
b12:
    v38 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    return v38;
b13:
    goto b11;
}

uint64_t exs_documentum_proba(unsigned char *p0, uint64_t p1, unsigned char *p2)
{
    unsigned char *v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    unsigned char *v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v39;
    uint64_t v41;
    uint64_t v42;
    uint64_t v43;
    uint64_t v44;
    uint64_t v46;
    uint64_t v48;
    _Alignas(1) unsigned char s25[8];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exsi_norm_u(v2, 32);
    v5 = exsi_ld_le(v3 + 16, 8);
    v6 = UINT64_C(8);
    v7 = (v5 < v6);
    if (v7) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v9 = UINT64_C(1);
    return v9;
b3:
    v11 = exsi_norm_u(exsi_ld_le(v3 + 24, 4), 32);
    v12 = exsi_norm_u(v11, 32);
    v13 = (v12 > v4);
    if (v13) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v15 = UINT64_C(1);
    return v15;
b5:
    v17 = exsi_ld_le(v3 + 16, 8);
    v18 = exsi_sub_u(v4, v12, 64);
    v19 = (v17 > v18);
    if (v19) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v21 = UINT64_C(1);
    return v21;
b7:
    v23 = exsi_ld_le(v3 + 16, 8);
    v24 = exsi_norm_u(v23, 32);
    v25 = s25;
    v26 = UINT64_C(8);
    v27 = exsi_sub_u(v24, v26, 32);
    exs_recordum_lege(v25, v1, v27);
    v29 = exsi_norm_u(exsi_ld_le(v25 + 0, 4), 32);
    v30 = exsi_norm_u(exsi_ld_le(v3 + 24, 4), 32);
    v31 = (v29 != v30);
    if (v31) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v33 = UINT64_C(1);
    return v33;
b9:
    v35 = exsi_norm_u(exsi_ld_le(v25 + 4, 4), 32);
    v36 = exsi_norm_u(exsi_ld_le(v3 + 28, 4), 32);
    v37 = (v35 != v36);
    if (v37) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v39 = UINT64_C(1);
    return v39;
b11:
    v41 = exsi_norm_u(exsi_ld_le(v3 + 24, 4), 32);
    v42 = exs_redundantia32(v1, v24, v41);
    v43 = exsi_norm_u(exsi_ld_le(v3 + 28, 4), 32);
    v44 = (v42 != v43);
    if (v44) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v46 = UINT64_C(2);
    return v46;
b13:
    v48 = UINT64_C(0);
    return v48;
}

uint64_t exs_documentum_quaere(unsigned char *p0, unsigned char *p1, uint64_t p2, uint64_t p3, unsigned char *p4, uint64_t p5)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    uint64_t v4;
    unsigned char *v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v12;
    uint64_t v13;
    unsigned char *v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    unsigned char *v21;
    uint64_t v22;
    unsigned char *v24;
    uint64_t v25;
    unsigned char *v26;
    uint64_t v27;
    unsigned char *v29;
    uint64_t v30;
    uint64_t v31;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = p4;
    v6 = p5;
    v7 = exs_clavem_quaere(v1, v5, v6);
    v8 = exsi_norm_u(exsi_ld_n(v1 + 0, 4), 32);
    v9 = (v7 >= v8);
    if (v9) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    return v4;
b3:
    v12 = (unsigned char *)((uintptr_t)v1 + 16388);
    v13 = UINT64_C(2048);
    if (v7 >= v13) exsrt_abortus(1);
    v15 = (unsigned char *)((uintptr_t)v12 + (uintptr_t)v7 * 1);
    v16 = exsi_norm_u(exsi_ld_n(v15 + 0, 1), 8);
    v17 = UINT64_C(0);
    v18 = (v16 == v17);
    if (v18) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    return v4;
b5:
    v21 = (unsigned char *)((uintptr_t)v1 + 20484);
    v22 = UINT64_C(2048);
    if (v7 >= v22) exsrt_abortus(1);
    v24 = (unsigned char *)((uintptr_t)v21 + (uintptr_t)v7 * 8);
    v25 = exsi_ld_n(v24 + 0, 8);
    v26 = (unsigned char *)((uintptr_t)v1 + 36868);
    v27 = UINT64_C(2048);
    if (v7 >= v27) exsrt_abortus(1);
    v29 = (unsigned char *)((uintptr_t)v26 + (uintptr_t)v7 * 8);
    v30 = exsi_ld_n(v29 + 0, 8);
    v31 = exs_indicem_quaere(v2, v3, v4, v25, v30);
    return v31;
}

void exs_suffixum_percurre(unsigned char *p0, unsigned char *p1, unsigned char *p2, uint64_t p3)
{
    unsigned char *v1;
    unsigned char *v2;
    unsigned char *v3;
    uint64_t v4;
    unsigned char *v5;
    uint64_t v6;
    unsigned char *v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    unsigned char *v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    unsigned char *v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    unsigned char *v35;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    unsigned char *v44;
    uint64_t v47;
    uint64_t v48;
    uint64_t v49;
    uint64_t v51;
    uint64_t v52;
    uint64_t v53;
    unsigned char *v55;
    uint64_t v56;
    unsigned char *v57;
    uint64_t v58;
    unsigned char *v60;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    unsigned char *v71;
    uint64_t v72;
    uint64_t v73;
    unsigned char *v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v79;
    unsigned char *v82;
    uint64_t v83;
    unsigned char *v85;
    uint64_t v86;
    unsigned char *v87;
    uint64_t v88;
    unsigned char *v90;
    uint64_t v91;
    uint64_t v92;
    uint64_t v94;
    uint64_t v95;
    uint64_t v97;
    uint64_t v98;
    uint64_t v99;
    uint64_t v100;
    uint64_t v101;
    uint64_t v102;
    uint64_t v103;
    uint64_t v107;
    unsigned char *v109;
    uint64_t v111;
    uint64_t v112;
    uint64_t v114;
    uint64_t v115;
    uint64_t t12;
    uint64_t t31;
    uint64_t t47;
    uint64_t t94;
    uint64_t t101;
    _Alignas(1) unsigned char s5[260];
    _Alignas(4) unsigned char s27[8192];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = s5;
    v6 = UINT64_C(0);
    exsi_st_n(v5 + 0, 4, v6);
    v8 = (unsigned char *)((uintptr_t)v5 + 4);
    v9 = UINT64_C(0);
    v10 = UINT64_C(0);
    t12 = v10;
    v12 = t12;
    goto b2;
b2:
    v13 = UINT64_C(64);
    v14 = (v12 < v13);
    if (v14) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v16 = (unsigned char *)((uintptr_t)v8 + (uintptr_t)v12 * 4);
    exsi_st_n(v16 + 0, 4, v9);
    v18 = UINT64_C(1);
    v19 = v12 + v18;
    t12 = v19;
    v12 = t12;
    goto b2;
b4:
    v21 = exs_clavem_quaere(v2, v3, v4);
    v22 = exsi_norm_u(exsi_ld_n(v2 + 0, 4), 32);
    v23 = (v21 >= v22);
    if (v23) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    __builtin_memcpy(v1, v5, 260);
    return;
b6:
    v27 = s27;
    v28 = UINT64_C(0);
    v29 = UINT64_C(0);
    t31 = v29;
    v31 = t31;
    goto b7;
b7:
    v32 = UINT64_C(2048);
    v33 = (v31 < v32);
    if (v33) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v35 = (unsigned char *)((uintptr_t)v27 + (uintptr_t)v31 * 4);
    exsi_st_n(v35 + 0, 4, v28);
    v37 = UINT64_C(1);
    v38 = v31 + v37;
    t31 = v38;
    v31 = t31;
    goto b7;
b9:
    v40 = UINT64_C(1);
    v41 = UINT64_C(0);
    v42 = UINT64_C(2048);
    if (v41 >= v42) exsrt_abortus(1);
    v44 = (unsigned char *)((uintptr_t)v27 + (uintptr_t)v41 * 4);
    exsi_st_n(v44 + 0, 4, v21);
    t47 = v40;
    v47 = t47;
    goto b10;
b10:
    v48 = UINT64_C(0);
    v49 = (v47 > v48);
    if (v49) {
        goto b11;
    } else {
        goto b12;
    }
b11:
    v51 = UINT64_C(1);
    v52 = exsi_sub_u(v47, v51, 32);
    v53 = UINT64_C(2048);
    if (v52 >= v53) exsrt_abortus(1);
    v55 = (unsigned char *)((uintptr_t)v27 + (uintptr_t)v52 * 4);
    v56 = exsi_norm_u(exsi_ld_n(v55 + 0, 4), 32);
    v57 = (unsigned char *)((uintptr_t)v2 + 16388);
    v58 = UINT64_C(2048);
    if (v56 >= v58) exsrt_abortus(1);
    v60 = (unsigned char *)((uintptr_t)v57 + (uintptr_t)v56 * 1);
    v61 = exsi_norm_u(exsi_ld_n(v60 + 0, 1), 8);
    v62 = UINT64_C(1);
    v63 = (v61 == v62);
    if (v63) {
        goto b13;
    } else {
        goto b14;
    }
b12:
    __builtin_memcpy(v1, v5, 260);
    return;
b13:
    v65 = exsi_norm_u(exsi_ld_n(v5 + 0, 4), 32);
    v66 = UINT64_C(64);
    v67 = (v65 >= v66);
    if (v67) {
        goto b15;
    } else {
        goto b16;
    }
b14:
    v82 = (unsigned char *)((uintptr_t)v2 + 8196);
    v83 = UINT64_C(2048);
    if (v56 >= v83) exsrt_abortus(1);
    v85 = (unsigned char *)((uintptr_t)v82 + (uintptr_t)v56 * 4);
    v86 = exsi_norm_u(exsi_ld_n(v85 + 0, 4), 32);
    v87 = (unsigned char *)((uintptr_t)v2 + 4);
    v88 = UINT64_C(2048);
    if (v56 >= v88) exsrt_abortus(1);
    v90 = (unsigned char *)((uintptr_t)v87 + (uintptr_t)v56 * 4);
    v91 = exsi_norm_u(exsi_ld_n(v90 + 0, 4), 32);
    v92 = UINT64_C(0);
    t101 = v52;
    t94 = v92;
    v101 = t101;
    v94 = t94;
    goto b17;
b15:
    __builtin_memcpy(v1, v5, 260);
    return;
b16:
    v71 = (unsigned char *)((uintptr_t)v5 + 4);
    v72 = exsi_norm_u(exsi_ld_n(v5 + 0, 4), 32);
    v73 = UINT64_C(64);
    if (v72 >= v73) exsrt_abortus(1);
    v75 = (unsigned char *)((uintptr_t)v71 + (uintptr_t)v72 * 4);
    exsi_st_n(v75 + 0, 4, v56);
    v77 = exsi_norm_u(exsi_ld_n(v5 + 0, 4), 32);
    v78 = UINT64_C(1);
    v79 = exsi_add_u(v77, v78, 32);
    exsi_st_n(v5 + 0, 4, v79);
    goto b14;
b17:
    v95 = (v94 < v86);
    if (v95) {
        goto b18;
    } else {
        goto b19;
    }
b18:
    v97 = UINT64_C(1);
    v98 = exsi_sub_u(v86, v97, 32);
    v99 = exsi_sub_u(v98, v94, 32);
    v100 = exsi_add_u(v91, v99, 32);
    v102 = UINT64_C(2048);
    v103 = (v101 >= v102);
    if (v103) {
        goto b21;
    } else {
        goto b22;
    }
b19:
    t47 = v101;
    v47 = t47;
    goto b10;
b20:
    v114 = UINT64_C(1);
    v115 = exsi_norm_u(v94 + v114, 32);
    t101 = v112;
    t94 = v115;
    v101 = t101;
    v94 = t94;
    goto b17;
b21:
    __builtin_memcpy(v1, v5, 260);
    return;
b22:
    v107 = UINT64_C(2048);
    if (v101 >= v107) exsrt_abortus(1);
    v109 = (unsigned char *)((uintptr_t)v27 + (uintptr_t)v101 * 4);
    exsi_st_n(v109 + 0, 4, v100);
    v111 = UINT64_C(1);
    v112 = exsi_add_u(v101, v111, 32);
    goto b20;
}

