#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_multiplica_modulo(uint64_t p0, uint64_t p1);
uint64_t exs_inverte_dextrorsum(uint64_t p0, uint64_t p1);
uint64_t exs_misce_furore(uint64_t p0);
uint64_t exs_demisce_furore(uint64_t p0);
uint64_t exs_semina_furore(uint64_t p0, uint64_t p1);
uint64_t exs_desemina_furore(uint64_t p0, uint64_t p1);
uint64_t exs_compone_plano(uint64_t p0, uint64_t p1);
uint64_t exs_semina_plano(uint64_t p0, uint64_t p1, uint64_t p2);
uint64_t exs_desemina_plano(uint64_t p0, uint64_t p1, unsigned char *p2);
uint64_t exs_xs(uint64_t p0);
uint64_t exs_proximus(unsigned char *p0);
uint64_t exs_infra(unsigned char *p0, uint64_t p1);
uint64_t exs_muri_circum(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_passabile(unsigned char *p0, uint64_t p1);
uint64_t exs_apertum(unsigned char *p0, uint64_t p1);
uint64_t exs_asperge(unsigned char *p0, unsigned char *p1);
uint64_t exs_leniga(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_hori(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3);
uint64_t exs_vert(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3);
uint64_t exs_empuja(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_fig_dungeon_prune(unsigned char *p0, uint64_t p1);
uint64_t exs_fig_dungeon_chunk(unsigned char *p0, unsigned char *p1, uint64_t p2);
uint64_t exs_fig_dungeon_crc32(unsigned char *p0);

uint64_t exs_multiplica_modulo(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(32);
    v4 = exsi_shl_u(v1, v3, 64);
    v5 = UINT64_C(32);
    v6 = exsi_shr_u(v4, v5, 64);
    v7 = UINT64_C(32);
    v8 = exsi_shr_u(v1, v7, 64);
    v9 = UINT64_C(32);
    v10 = exsi_shl_u(v2, v9, 64);
    v11 = UINT64_C(32);
    v12 = exsi_shr_u(v10, v11, 64);
    v13 = UINT64_C(32);
    v14 = exsi_shr_u(v2, v13, 64);
    v15 = exsi_mul_u(v8, v12, 64);
    v16 = UINT64_C(32);
    v17 = exsi_shl_u(v15, v16, 64);
    v18 = UINT64_C(32);
    v19 = exsi_shr_u(v17, v18, 64);
    v20 = exsi_mul_u(v6, v14, 64);
    v21 = UINT64_C(32);
    v22 = exsi_shl_u(v20, v21, 64);
    v23 = UINT64_C(32);
    v24 = exsi_shr_u(v22, v23, 64);
    v25 = exsi_add_u(v19, v24, 64);
    v26 = exsi_mul_u(v6, v12, 64);
    v27 = UINT64_C(32);
    v28 = exsi_shl_u(v25, v27, 64);
    v29 = v26 + v28;
    return v29;
}

uint64_t exs_inverte_dextrorsum(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t t6;
    uint64_t t9;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = UINT64_C(2);
    t9 = v1;
    t6 = v3;
    v9 = t9;
    v6 = t6;
    goto b2;
b2:
    v7 = (v6 < v4);
    if (v7) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = exsi_shr_u(v9, v2, 64);
    v11 = v1 ^ v10;
    goto b5;
b4:
    return v9;
b5:
    v13 = UINT64_C(1);
    v14 = v6 + v13;
    t9 = v11;
    t6 = v14;
    v9 = t9;
    v6 = t6;
    goto b2;
}

uint64_t exs_misce_furore(uint64_t p0)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    v1 = p0;
    v2 = UINT64_C(30);
    v3 = exsi_shr_u(v1, v2, 64);
    v4 = v1 ^ v3;
    v5 = UINT64_C(13787848793156543929);
    v6 = exs_multiplica_modulo(v4, v5);
    v7 = UINT64_C(27);
    v8 = exsi_shr_u(v6, v7, 64);
    v9 = v6 ^ v8;
    v10 = UINT64_C(10723151780598845931);
    v11 = exs_multiplica_modulo(v9, v10);
    v12 = UINT64_C(31);
    v13 = exsi_shr_u(v11, v12, 64);
    v14 = v11 ^ v13;
    return v14;
}

uint64_t exs_demisce_furore(uint64_t p0)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    v1 = p0;
    v2 = UINT64_C(31);
    v3 = exs_inverte_dextrorsum(v1, v2);
    v4 = UINT64_C(3573116690164977347);
    v5 = exs_multiplica_modulo(v3, v4);
    v6 = UINT64_C(27);
    v7 = exs_inverte_dextrorsum(v5, v6);
    v8 = UINT64_C(10871156337175269513);
    v9 = exs_multiplica_modulo(v7, v8);
    v10 = UINT64_C(30);
    v11 = exs_inverte_dextrorsum(v9, v10);
    return v11;
}

uint64_t exs_semina_furore(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(11400714819323198485);
    v4 = exs_multiplica_modulo(v2, v3);
    v5 = v1 + v4;
    v6 = exs_misce_furore(v5);
    return v6;
}

uint64_t exs_desemina_furore(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(17428512612931826493);
    v4 = exs_demisce_furore(v1);
    v5 = v4 - v2;
    v6 = exs_multiplica_modulo(v5, v3);
    return v6;
}

uint64_t exs_compone_plano(uint64_t p0, uint64_t p1)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    v1 = p0;
    v2 = p1;
    v3 = exsi_norm_u(v2, 32);
    v4 = UINT64_C(32);
    v5 = exsi_shl_u(v3, v4, 64);
    v6 = exsi_norm_u(v1, 32);
    v7 = v5 | v6;
    return v7;
}

uint64_t exs_semina_plano(uint64_t p0, uint64_t p1, uint64_t p2)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exs_compone_plano(v2, v3);
    v5 = exs_semina_furore(v1, v4);
    return v5;
}

uint64_t exs_desemina_plano(uint64_t p0, uint64_t p1, unsigned char *p2)
{
    uint64_t v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    unsigned char *v9;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    unsigned char *v17;
    uint64_t v19;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exs_desemina_furore(v1, v2);
    v5 = exsi_norm_u(v4, 32);
    v6 = UINT64_C(0);
    v7 = UINT64_C(2);
    if (v6 >= v7) exsrt_abortus(1);
    v9 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v6 * 4);
    exsi_st_n(v9 + 0, 4, v5);
    v11 = UINT64_C(32);
    v12 = exsi_shr_u(v4, v11, 64);
    v13 = exsi_norm_u(v12, 32);
    v14 = UINT64_C(1);
    v15 = UINT64_C(2);
    if (v14 >= v15) exsrt_abortus(1);
    v17 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v14 * 4);
    exsi_st_n(v17 + 0, 4, v13);
    v19 = UINT64_C(0);
    return v19;
}

uint64_t exs_xs(uint64_t p0)
{
    uint64_t v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    v1 = p0;
    v2 = UINT64_C(13);
    v3 = exsi_shl_u(v1, v2, 64);
    v4 = v1 ^ v3;
    v5 = UINT64_C(7);
    v6 = exsi_shr_u(v4, v5, 64);
    v7 = v4 ^ v6;
    v8 = UINT64_C(17);
    v9 = exsi_shl_u(v7, v8, 64);
    v10 = v7 ^ v9;
    return v10;
}

uint64_t exs_proximus(unsigned char *p0)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    v1 = p0;
    v2 = exsi_ld_n(v1 + 0, 8);
    v3 = exs_xs(v2);
    exsi_st_n(v1 + 0, 8, v3);
    v5 = exsi_ld_n(v1 + 8, 8);
    v6 = UINT64_C(1);
    v7 = exsi_add_u(v5, v6, 64);
    exsi_st_n(v1 + 8, 8, v7);
    v9 = exsi_ld_n(v1 + 0, 8);
    return v9;
}

uint64_t exs_infra(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    v1 = p0;
    v2 = p1;
    v3 = exs_proximus(v1);
    v4 = UINT64_C(32);
    v5 = exsi_shr_u(v3, v4, 64);
    v6 = exsi_mul_u(v5, v2, 64);
    v7 = UINT64_C(32);
    v8 = exsi_shr_u(v6, v7, 64);
    return v8;
}

uint64_t exs_muri_circum(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    unsigned char *v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v45;
    uint64_t v46;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    uint64_t v52;
    uint64_t v53;
    uint64_t t11;
    uint64_t t17;
    uint64_t t26;
    uint64_t t39;
    uint64_t t48;
    uint64_t t49;
    uint64_t t50;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = exsi_add_u(v2, v3, 64);
    v5 = UINT64_C(65);
    v6 = exsi_sub_u(v4, v5, 64);
    v7 = UINT64_C(0);
    v8 = UINT64_C(0);
    v9 = UINT64_C(3);
    t48 = v7;
    t11 = v8;
    v48 = t48;
    v11 = t11;
    goto b2;
b2:
    v12 = (v11 < v9);
    if (v12) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v14 = UINT64_C(0);
    v15 = UINT64_C(3);
    t39 = v48;
    t17 = v14;
    v39 = t39;
    v17 = t17;
    goto b6;
b4:
    return v48;
b5:
    v52 = UINT64_C(1);
    v53 = v11 + v52;
    t48 = v39;
    t11 = v53;
    v48 = t48;
    v11 = t11;
    goto b2;
b6:
    v18 = (v17 < v15);
    if (v18) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v20 = UINT64_C(1);
    v21 = (v11 != v20);
    if (v21) {
        t26 = v21;
        v26 = t26;
        goto b11;
    } else {
        goto b10;
    }
b8:
    goto b5;
b9:
    v45 = UINT64_C(1);
    v46 = v17 + v45;
    t39 = v49;
    t17 = v46;
    v39 = t39;
    v17 = t17;
    goto b6;
b10:
    v23 = UINT64_C(1);
    v24 = (v17 != v23);
    t26 = v24;
    v26 = t26;
    goto b11;
b11:
    if (v26) {
        goto b12;
    } else {
        t49 = v39;
        v49 = t49;
        goto b13;
    }
b12:
    v28 = UINT64_C(64);
    v29 = exsi_mul_u(v11, v28, 64);
    v30 = exsi_add_u(v6, v29, 64);
    v31 = exsi_add_u(v30, v17, 64);
    v32 = UINT64_C(12288);
    if (v31 >= v32) exsrt_abortus(1);
    v34 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v31 * 1);
    v35 = exsi_norm_u(exsi_ld_n(v34 + 0, 1), 8);
    v36 = UINT64_C(0);
    v37 = (v35 == v36);
    if (v37) {
        goto b14;
    } else {
        t50 = v39;
        v50 = t50;
        goto b15;
    }
b13:
    goto b9;
b14:
    v40 = UINT64_C(1);
    v41 = exsi_add_u(v39, v40, 64);
    t50 = v41;
    v50 = t50;
    goto b15;
b15:
    t49 = v50;
    v49 = t49;
    goto b13;
}

uint64_t exs_passabile(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    unsigned char *v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v12;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(12288);
    if (v2 >= v3) exsrt_abortus(1);
    v5 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v2 * 1);
    v6 = exsi_norm_u(exsi_ld_n(v5 + 0, 1), 8);
    v7 = UINT64_C(0);
    v8 = (v6 != v7);
    if (v8) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v10 = UINT64_C(1);
    return v10;
b3:
    v12 = UINT64_C(0);
    return v12;
}

uint64_t exs_apertum(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v10;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = exs_muri_circum(v1, v3, v2);
    v5 = UINT64_C(3);
    v6 = (v4 <= v5);
    if (v6) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v8 = UINT64_C(1);
    return v8;
b3:
    v10 = UINT64_C(0);
    return v10;
}

uint64_t exs_asperge(unsigned char *p0, unsigned char *p1)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    unsigned char *v21;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v38;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    uint64_t v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v47;
    uint64_t v49;
    uint64_t v50;
    uint64_t v52;
    uint64_t v54;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    unsigned char *v65;
    uint64_t v68;
    uint64_t v69;
    uint64_t v71;
    uint64_t v72;
    uint64_t v74;
    uint64_t v75;
    uint64_t t7;
    uint64_t t13;
    uint64_t t31;
    uint64_t t38;
    uint64_t t40;
    uint64_t t58;
    uint64_t t59;
    uint64_t t60;
    uint64_t t71;
    uint64_t t72;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = UINT64_C(1);
    v5 = UINT64_C(63);
    t71 = v3;
    t7 = v4;
    v71 = t71;
    v7 = t7;
    goto b2;
b2:
    v8 = (v7 < v5);
    if (v8) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(1);
    v11 = UINT64_C(63);
    t40 = v71;
    t13 = v10;
    v40 = t40;
    v13 = t13;
    goto b6;
b4:
    return v71;
b5:
    v74 = UINT64_C(1);
    v75 = v7 + v74;
    t71 = v40;
    t7 = v75;
    v71 = t71;
    v7 = t7;
    goto b2;
b6:
    v14 = (v13 < v11);
    if (v14) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v16 = UINT64_C(64);
    v17 = exsi_mul_u(v7, v16, 64);
    v18 = exsi_add_u(v17, v13, 64);
    v19 = UINT64_C(12288);
    if (v18 >= v19) exsrt_abortus(1);
    v21 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v18 * 1);
    v22 = exsi_norm_u(exsi_ld_n(v21 + 0, 1), 8);
    v23 = UINT64_C(0);
    v24 = exs_muri_circum(v1, v23, v18);
    v25 = UINT64_C(0);
    v26 = (v22 == v25);
    if (v26) {
        goto b10;
    } else {
        t31 = v24;
        v31 = t31;
        goto b11;
    }
b8:
    goto b5;
b9:
    v68 = UINT64_C(1);
    v69 = v13 + v68;
    t40 = v72;
    t13 = v69;
    v40 = t40;
    v13 = t13;
    goto b6;
b10:
    v28 = UINT64_C(1);
    v29 = exsi_add_u(v24, v28, 64);
    t31 = v29;
    v31 = t31;
    goto b11;
b11:
    v32 = UINT64_C(0);
    v33 = (v31 > v32);
    if (v33) {
        goto b12;
    } else {
        t38 = v33;
        v38 = t38;
        goto b13;
    }
b12:
    v35 = UINT64_C(9);
    v36 = (v31 < v35);
    t38 = v36;
    v38 = t38;
    goto b13;
b13:
    if (v38) {
        goto b14;
    } else {
        t72 = v40;
        t58 = v22;
        v72 = t72;
        v58 = t58;
        goto b15;
    }
b14:
    v41 = UINT64_C(1);
    v42 = exsi_add_u(v40, v41, 64);
    v43 = exs_proximus(v2);
    v44 = UINT64_C(62);
    v45 = exsi_shr_u(v43, v44, 64);
    v46 = UINT64_C(0);
    v47 = (v45 == v46);
    if (v47) {
        goto b16;
    } else {
        t59 = v22;
        v59 = t59;
        goto b17;
    }
b15:
    v61 = UINT64_C(4096);
    v62 = exsi_add_u(v61, v18, 64);
    v63 = UINT64_C(12288);
    if (v62 >= v63) exsrt_abortus(1);
    v65 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v62 * 1);
    exsi_st_n(v65 + 0, 1, v58);
    goto b9;
b16:
    v49 = UINT64_C(0);
    v50 = (v22 == v49);
    if (v50) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    t72 = v42;
    t58 = v59;
    v72 = t72;
    v58 = t58;
    goto b15;
b18:
    v52 = UINT64_C(1);
    t60 = v52;
    v60 = t60;
    goto b20;
b19:
    v54 = UINT64_C(0);
    t60 = v54;
    v60 = t60;
    goto b20;
b20:
    t59 = v60;
    v59 = t59;
    goto b17;
}

uint64_t exs_leniga(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    unsigned char *v27;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    unsigned char *v37;
    uint64_t v40;
    uint64_t v41;
    unsigned char *v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    unsigned char *v48;
    uint64_t v52;
    uint64_t v53;
    uint64_t v56;
    uint64_t v57;
    uint64_t v59;
    uint64_t t7;
    uint64_t t13;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(1);
    v5 = UINT64_C(63);
    t7 = v4;
    v7 = t7;
    goto b2;
b2:
    v8 = (v7 < v5);
    if (v8) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(1);
    v11 = UINT64_C(63);
    t13 = v10;
    v13 = t13;
    goto b6;
b4:
    v59 = UINT64_C(0);
    return v59;
b5:
    v56 = UINT64_C(1);
    v57 = v7 + v56;
    t7 = v57;
    v7 = t7;
    goto b2;
b6:
    v14 = (v13 < v11);
    if (v14) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v16 = UINT64_C(64);
    v17 = exsi_mul_u(v7, v16, 64);
    v18 = exsi_add_u(v17, v13, 64);
    v19 = exs_muri_circum(v1, v2, v18);
    v20 = UINT64_C(5);
    v21 = (v19 >= v20);
    if (v21) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    goto b5;
b9:
    v52 = UINT64_C(1);
    v53 = v13 + v52;
    t13 = v53;
    v13 = t13;
    goto b6;
b10:
    v23 = UINT64_C(0);
    v24 = exsi_add_u(v3, v18, 64);
    v25 = UINT64_C(12288);
    if (v24 >= v25) exsrt_abortus(1);
    v27 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v24 * 1);
    exsi_st_n(v27 + 0, 1, v23);
    goto b12;
b11:
    v30 = UINT64_C(3);
    v31 = (v19 <= v30);
    if (v31) {
        goto b13;
    } else {
        goto b14;
    }
b12:
    goto b9;
b13:
    v33 = UINT64_C(1);
    v34 = exsi_add_u(v3, v18, 64);
    v35 = UINT64_C(12288);
    if (v34 >= v35) exsrt_abortus(1);
    v37 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v34 * 1);
    exsi_st_n(v37 + 0, 1, v33);
    goto b12;
b14:
    v40 = exsi_add_u(v2, v18, 64);
    v41 = UINT64_C(12288);
    if (v40 >= v41) exsrt_abortus(1);
    v43 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v40 * 1);
    v44 = exsi_norm_u(exsi_ld_n(v43 + 0, 1), 8);
    v45 = exsi_add_u(v3, v18, 64);
    v46 = UINT64_C(12288);
    if (v45 >= v46) exsrt_abortus(1);
    v48 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v45 * 1);
    exsi_st_n(v48 + 0, 1, v44);
    goto b12;
}

uint64_t exs_hori(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t t8;
    uint64_t t9;
    uint64_t t13;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = (v3 > v4);
    if (v5) {
        goto b2;
    } else {
        t9 = v4;
        t8 = v3;
        v9 = t9;
        v8 = t8;
        goto b3;
    }
b2:
    t9 = v3;
    t8 = v4;
    v9 = t9;
    v8 = t8;
    goto b3;
b3:
    v10 = UINT64_C(1);
    v11 = exsi_add_u(v9, v10, 64);
    t13 = v8;
    v13 = t13;
    goto b4;
b4:
    v14 = (v13 < v11);
    if (v14) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v16 = UINT64_C(1);
    v17 = UINT64_C(64);
    v18 = exsi_mul_u(v2, v17, 64);
    v19 = exsi_add_u(v18, v13, 64);
    v20 = UINT64_C(12288);
    if (v19 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    exsi_st_n(v22 + 0, 1, v16);
    goto b7;
b6:
    v28 = UINT64_C(0);
    return v28;
b7:
    v25 = UINT64_C(1);
    v26 = v13 + v25;
    t13 = v26;
    v13 = t13;
    goto b4;
}

uint64_t exs_vert(unsigned char *p0, uint64_t p1, uint64_t p2, uint64_t p3)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v8;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t t8;
    uint64_t t9;
    uint64_t t13;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = p3;
    v5 = (v3 > v4);
    if (v5) {
        goto b2;
    } else {
        t9 = v4;
        t8 = v3;
        v9 = t9;
        v8 = t8;
        goto b3;
    }
b2:
    t9 = v3;
    t8 = v4;
    v9 = t9;
    v8 = t8;
    goto b3;
b3:
    v10 = UINT64_C(1);
    v11 = exsi_add_u(v9, v10, 64);
    t13 = v8;
    v13 = t13;
    goto b4;
b4:
    v14 = (v13 < v11);
    if (v14) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v16 = UINT64_C(1);
    v17 = UINT64_C(64);
    v18 = exsi_mul_u(v13, v17, 64);
    v19 = exsi_add_u(v18, v2, 64);
    v20 = UINT64_C(12288);
    if (v19 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    exsi_st_n(v22 + 0, 1, v16);
    goto b7;
b6:
    v28 = UINT64_C(0);
    return v28;
b7:
    v25 = UINT64_C(1);
    v26 = v13 + v25;
    t13 = v26;
    v13 = t13;
    goto b4;
}

uint64_t exs_empuja(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    unsigned char *v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    unsigned char *v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    unsigned char *v23;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    unsigned char *v34;
    uint64_t v36;
    uint64_t v37;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(12288);
    if (v3 >= v4) exsrt_abortus(1);
    v6 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v3 * 1);
    v7 = exsi_norm_u(exsi_ld_n(v6 + 0, 1), 8);
    v8 = UINT64_C(1);
    v9 = (v7 == v8);
    if (v9) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v11 = UINT64_C(4);
    v12 = UINT64_C(12288);
    if (v3 >= v12) exsrt_abortus(1);
    v14 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v3 * 1);
    exsi_st_n(v14 + 0, 1, v11);
    v16 = exsi_norm_u(v3, 8);
    v17 = UINT64_C(4096);
    v18 = UINT64_C(2);
    v19 = exsi_mul_u(v18, v2, 64);
    v20 = exsi_add_u(v17, v19, 64);
    v21 = UINT64_C(12288);
    if (v20 >= v21) exsrt_abortus(1);
    v23 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v20 * 1);
    exsi_st_n(v23 + 0, 1, v16);
    v25 = UINT64_C(8);
    v26 = exsi_shr_u(v3, v25, 64);
    v27 = exsi_norm_u(v26, 8);
    v28 = UINT64_C(4097);
    v29 = UINT64_C(2);
    v30 = exsi_mul_u(v29, v2, 64);
    v31 = exsi_add_u(v28, v30, 64);
    v32 = UINT64_C(12288);
    if (v31 >= v32) exsrt_abortus(1);
    v34 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v31 * 1);
    exsi_st_n(v34 + 0, 1, v27);
    v36 = UINT64_C(1);
    v37 = exsi_add_u(v2, v36, 64);
    return v37;
b3:
    return v2;
}

uint64_t exs_fig_dungeon_prune(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    unsigned char *v5;
    uint64_t v6;
    uint64_t v7;
    uint64_t v8;
    uint64_t v10;
    uint64_t v12;
    uint64_t v13;
    unsigned char *v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v19;
    unsigned char *v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    unsigned char *v29;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    uint64_t v43;
    unsigned char *v45;
    uint64_t v46;
    uint64_t v47;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    uint64_t v51;
    uint64_t v52;
    unsigned char *v54;
    uint64_t v55;
    uint64_t v56;
    uint64_t v57;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    uint64_t v68;
    uint64_t v69;
    uint64_t v70;
    uint64_t v71;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v80;
    unsigned char *v82;
    uint64_t v83;
    uint64_t v84;
    uint64_t v85;
    uint64_t v87;
    uint64_t v88;
    unsigned char *v90;
    uint64_t v93;
    unsigned char *v95;
    uint64_t v96;
    uint64_t v97;
    uint64_t v98;
    uint64_t v100;
    uint64_t v101;
    unsigned char *v103;
    uint64_t v105;
    uint64_t v106;
    uint64_t v107;
    uint64_t v110;
    uint64_t v111;
    uint64_t v113;
    uint64_t t33;
    uint64_t t77;
    uint64_t t105;
    uint64_t t113;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(12288);
    if (v2 >= v3) exsrt_abortus(1);
    v5 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v2 * 1);
    v6 = exsi_norm_u(exsi_ld_n(v5 + 0, 1), 8);
    v7 = UINT64_C(1);
    v8 = (v6 != v7);
    if (v8) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v10 = UINT64_C(4097);
    return v10;
b3:
    v12 = UINT64_C(4);
    v13 = UINT64_C(12288);
    if (v2 >= v13) exsrt_abortus(1);
    v15 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v2 * 1);
    exsi_st_n(v15 + 0, 1, v12);
    v17 = exsi_norm_u(v2, 8);
    v18 = UINT64_C(4096);
    v19 = UINT64_C(12288);
    if (v18 >= v19) exsrt_abortus(1);
    v21 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v18 * 1);
    exsi_st_n(v21 + 0, 1, v17);
    v23 = UINT64_C(8);
    v24 = exsi_shr_u(v2, v23, 64);
    v25 = exsi_norm_u(v24, 8);
    v26 = UINT64_C(4097);
    v27 = UINT64_C(12288);
    if (v26 >= v27) exsrt_abortus(1);
    v29 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v26 * 1);
    exsi_st_n(v29 + 0, 1, v25);
    v31 = UINT64_C(1);
    t33 = v31;
    v33 = t33;
    goto b4;
b4:
    v34 = UINT64_C(0);
    v35 = (v33 > v34);
    if (v35) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v37 = UINT64_C(1);
    v38 = exsi_sub_u(v33, v37, 64);
    v39 = UINT64_C(4096);
    v40 = UINT64_C(2);
    v41 = exsi_mul_u(v40, v38, 64);
    v42 = exsi_add_u(v39, v41, 64);
    v43 = UINT64_C(12288);
    if (v42 >= v43) exsrt_abortus(1);
    v45 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v42 * 1);
    v46 = exsi_norm_u(exsi_ld_n(v45 + 0, 1), 8);
    v47 = exsi_norm_u(v46, 8);
    v48 = UINT64_C(4097);
    v49 = UINT64_C(2);
    v50 = exsi_mul_u(v49, v38, 64);
    v51 = exsi_add_u(v48, v50, 64);
    v52 = UINT64_C(12288);
    if (v51 >= v52) exsrt_abortus(1);
    v54 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v51 * 1);
    v55 = exsi_norm_u(exsi_ld_n(v54 + 0, 1), 8);
    v56 = exsi_norm_u(v55, 8);
    v57 = UINT64_C(8);
    v58 = exsi_shl_u(v56, v57, 64);
    v59 = exsi_add_u(v47, v58, 64);
    v60 = UINT64_C(64);
    v61 = exsi_sub_u(v59, v60, 64);
    v62 = exs_empuja(v1, v38, v61);
    v63 = UINT64_C(64);
    v64 = exsi_add_u(v59, v63, 64);
    v65 = exs_empuja(v1, v62, v64);
    v66 = UINT64_C(1);
    v67 = exsi_sub_u(v59, v66, 64);
    v68 = exs_empuja(v1, v65, v67);
    v69 = UINT64_C(1);
    v70 = exsi_add_u(v59, v69, 64);
    v71 = exs_empuja(v1, v68, v70);
    t33 = v71;
    v33 = t33;
    goto b4;
b6:
    v73 = UINT64_C(0);
    v74 = UINT64_C(0);
    v75 = UINT64_C(4096);
    t105 = v73;
    t77 = v74;
    v105 = t105;
    v77 = t77;
    goto b7;
b7:
    v78 = (v77 < v75);
    if (v78) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v80 = UINT64_C(12288);
    if (v77 >= v80) exsrt_abortus(1);
    v82 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v77 * 1);
    v83 = exsi_norm_u(exsi_ld_n(v82 + 0, 1), 8);
    v84 = UINT64_C(4);
    v85 = (v83 == v84);
    if (v85) {
        goto b11;
    } else {
        goto b12;
    }
b9:
    return v105;
b10:
    v110 = UINT64_C(1);
    v111 = v77 + v110;
    t105 = v113;
    t77 = v111;
    v105 = t105;
    v77 = t77;
    goto b7;
b11:
    v87 = UINT64_C(1);
    v88 = UINT64_C(12288);
    if (v77 >= v88) exsrt_abortus(1);
    v90 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v77 * 1);
    exsi_st_n(v90 + 0, 1, v87);
    t113 = v105;
    v113 = t113;
    goto b13;
b12:
    v93 = UINT64_C(12288);
    if (v77 >= v93) exsrt_abortus(1);
    v95 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v77 * 1);
    v96 = exsi_norm_u(exsi_ld_n(v95 + 0, 1), 8);
    v97 = UINT64_C(1);
    v98 = (v96 == v97);
    if (v98) {
        goto b14;
    } else {
        t113 = v105;
        v113 = t113;
        goto b13;
    }
b13:
    goto b10;
b14:
    v100 = UINT64_C(0);
    v101 = UINT64_C(12288);
    if (v77 >= v101) exsrt_abortus(1);
    v103 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v77 * 1);
    exsi_st_n(v103 + 0, 1, v100);
    v106 = UINT64_C(1);
    v107 = exsi_add_u(v105, v106, 64);
    t113 = v107;
    v113 = t113;
    goto b13;
}

uint64_t exs_fig_dungeon_chunk(unsigned char *p0, unsigned char *p1, uint64_t p2)
{
    unsigned char *v1;
    unsigned char *v2;
    uint64_t v3;
    unsigned char *v4;
    uint64_t v5;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    uint64_t v21;
    unsigned char *v23;
    uint64_t v26;
    uint64_t v27;
    unsigned char *v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    unsigned char *v37;
    uint64_t v39;
    uint64_t v40;
    unsigned char *v42;
    uint64_t v43;
    uint64_t v44;
    uint64_t v46;
    uint64_t v47;
    uint64_t v48;
    unsigned char *v50;
    uint64_t v52;
    uint64_t v53;
    unsigned char *v55;
    uint64_t v56;
    uint64_t v57;
    uint64_t v59;
    uint64_t v60;
    uint64_t v61;
    unsigned char *v63;
    uint64_t v65;
    uint64_t v66;
    unsigned char *v68;
    uint64_t v69;
    uint64_t v70;
    uint64_t v72;
    uint64_t v73;
    uint64_t v74;
    unsigned char *v76;
    uint64_t v78;
    uint64_t v79;
    unsigned char *v81;
    uint64_t v82;
    uint64_t v83;
    uint64_t v85;
    uint64_t v86;
    uint64_t v87;
    unsigned char *v89;
    uint64_t v91;
    uint64_t v92;
    uint64_t v94;
    uint64_t v95;
    uint64_t v96;
    unsigned char *v98;
    uint64_t v100;
    uint64_t v101;
    uint64_t v102;
    unsigned char *v104;
    uint64_t v106;
    uint64_t v108;
    uint64_t v109;
    uint64_t v110;
    uint64_t v112;
    uint64_t v113;
    uint64_t v115;
    uint64_t v116;
    uint64_t v118;
    unsigned char *v120;
    uint64_t v121;
    uint64_t v122;
    unsigned char *v124;
    uint64_t v125;
    uint64_t v126;
    uint64_t v127;
    uint64_t v128;
    unsigned char *v130;
    uint64_t v131;
    uint64_t v132;
    unsigned char *v134;
    uint64_t v135;
    uint64_t v136;
    uint64_t v137;
    uint64_t v141;
    uint64_t v142;
    uint64_t v144;
    uint64_t v145;
    unsigned char *v147;
    uint64_t v148;
    uint64_t v149;
    unsigned char *v151;
    uint64_t v152;
    uint64_t v153;
    uint64_t v155;
    uint64_t v156;
    uint64_t v157;
    uint64_t v158;
    uint64_t v159;
    uint64_t v160;
    uint64_t v161;
    uint64_t v162;
    uint64_t v163;
    uint64_t v164;
    unsigned char *v166;
    uint64_t v167;
    uint64_t v168;
    uint64_t v169;
    unsigned char *v171;
    uint64_t v173;
    unsigned char *v175;
    uint64_t v176;
    uint64_t v177;
    unsigned char *v179;
    uint64_t v181;
    uint64_t v182;
    unsigned char *v184;
    uint64_t v186;
    unsigned char *v188;
    uint64_t v190;
    unsigned char *v192;
    uint64_t v195;
    uint64_t v196;
    uint64_t v197;
    uint64_t v198;
    uint64_t v199;
    uint64_t v200;
    uint64_t v201;
    uint64_t v202;
    uint64_t v203;
    uint64_t v204;
    unsigned char *v206;
    uint64_t v207;
    uint64_t v208;
    unsigned char *v210;
    uint64_t v212;
    unsigned char *v214;
    uint64_t v215;
    uint64_t v216;
    uint64_t v217;
    unsigned char *v219;
    uint64_t v221;
    unsigned char *v223;
    uint64_t v225;
    uint64_t v226;
    unsigned char *v228;
    uint64_t v230;
    unsigned char *v232;
    uint64_t v235;
    unsigned char *v237;
    uint64_t v239;
    uint64_t v240;
    unsigned char *v242;
    uint64_t v243;
    uint64_t v244;
    uint64_t v246;
    uint64_t v247;
    uint64_t v248;
    unsigned char *v250;
    uint64_t v252;
    uint64_t v253;
    unsigned char *v255;
    uint64_t v256;
    uint64_t v257;
    uint64_t v259;
    uint64_t v260;
    uint64_t v261;
    unsigned char *v263;
    uint64_t v265;
    uint64_t v266;
    uint64_t v268;
    uint64_t v269;
    uint64_t v271;
    uint64_t v272;
    uint64_t v274;
    uint64_t v275;
    unsigned char *v277;
    uint64_t v278;
    uint64_t v279;
    uint64_t v280;
    uint64_t v281;
    uint64_t v282;
    uint64_t v283;
    uint64_t v284;
    unsigned char *v286;
    uint64_t v287;
    uint64_t v288;
    uint64_t v289;
    uint64_t v290;
    uint64_t v291;
    uint64_t v292;
    unsigned char *v294;
    uint64_t v295;
    uint64_t v296;
    uint64_t v297;
    uint64_t v298;
    unsigned char *v300;
    uint64_t v301;
    uint64_t v302;
    uint64_t v303;
    uint64_t v304;
    uint64_t v305;
    uint64_t v306;
    uint64_t v307;
    unsigned char *v309;
    uint64_t v310;
    uint64_t v311;
    uint64_t v312;
    uint64_t v313;
    unsigned char *v315;
    uint64_t v316;
    uint64_t v317;
    uint64_t v318;
    uint64_t v319;
    uint64_t v320;
    uint64_t v321;
    uint64_t v322;
    uint64_t v324;
    uint64_t v325;
    uint64_t v327;
    uint64_t v329;
    uint64_t v330;
    uint64_t v332;
    uint64_t v333;
    uint64_t v334;
    uint64_t v335;
    uint64_t v336;
    unsigned char *v338;
    uint64_t v341;
    uint64_t v342;
    uint64_t v345;
    uint64_t v346;
    uint64_t v348;
    uint64_t v349;
    uint64_t v350;
    uint64_t v351;
    unsigned char *v353;
    uint64_t v355;
    uint64_t v356;
    uint64_t v357;
    uint64_t v358;
    unsigned char *v360;
    uint64_t v363;
    uint64_t v364;
    uint64_t v366;
    uint64_t v367;
    uint64_t v368;
    uint64_t v370;
    uint64_t v371;
    uint64_t v373;
    uint64_t v374;
    uint64_t v375;
    uint64_t v376;
    uint64_t v378;
    uint64_t v379;
    uint64_t v380;
    uint64_t v382;
    uint64_t v383;
    uint64_t v384;
    uint64_t v387;
    uint64_t v388;
    uint64_t v390;
    uint64_t v391;
    uint64_t v393;
    uint64_t v394;
    uint64_t v396;
    uint64_t v397;
    uint64_t v398;
    unsigned char *v400;
    uint64_t v401;
    uint64_t v402;
    unsigned char *v404;
    uint64_t v407;
    uint64_t v408;
    uint64_t v410;
    uint64_t v411;
    uint64_t v413;
    uint64_t v414;
    uint64_t v416;
    unsigned char *v418;
    uint64_t v419;
    uint64_t v420;
    unsigned char *v422;
    uint64_t v423;
    uint64_t v424;
    unsigned char *v426;
    uint64_t v427;
    uint64_t v428;
    unsigned char *v430;
    uint64_t v431;
    uint64_t v432;
    unsigned char *v434;
    uint64_t v435;
    uint64_t v436;
    unsigned char *v438;
    uint64_t v439;
    uint64_t v440;
    uint64_t v441;
    uint64_t v442;
    uint64_t v443;
    uint64_t v444;
    uint64_t v446;
    uint64_t v447;
    uint64_t v449;
    uint64_t v450;
    uint64_t v453;
    uint64_t v454;
    uint64_t v456;
    uint64_t v457;
    unsigned char *v459;
    uint64_t v460;
    uint64_t v461;
    uint64_t v462;
    uint64_t v463;
    uint64_t v464;
    unsigned char *v466;
    uint64_t v467;
    uint64_t v468;
    uint64_t v469;
    uint64_t v470;
    uint64_t v471;
    uint64_t v473;
    uint64_t v474;
    uint64_t v476;
    uint64_t v477;
    uint64_t v479;
    uint64_t v480;
    uint64_t v482;
    uint64_t v483;
    uint64_t v484;
    uint64_t v485;
    unsigned char *v487;
    uint64_t v488;
    uint64_t v489;
    uint64_t v490;
    uint64_t v492;
    uint64_t v493;
    uint64_t v494;
    uint64_t v495;
    uint64_t v496;
    uint64_t v497;
    uint64_t v498;
    uint64_t v499;
    uint64_t v500;
    uint64_t v501;
    uint64_t v502;
    uint64_t v503;
    uint64_t v504;
    uint64_t v505;
    uint64_t v507;
    uint64_t v508;
    uint64_t v510;
    uint64_t v512;
    uint64_t v513;
    uint64_t v515;
    uint64_t v517;
    uint64_t v518;
    uint64_t v520;
    uint64_t v522;
    uint64_t v523;
    uint64_t v524;
    uint64_t v525;
    uint64_t v526;
    uint64_t v528;
    uint64_t v529;
    uint64_t v530;
    uint64_t v531;
    uint64_t v532;
    uint64_t v534;
    uint64_t v536;
    uint64_t v537;
    unsigned char *v539;
    uint64_t v543;
    uint64_t v544;
    uint64_t v546;
    uint64_t v547;
    uint64_t v549;
    uint64_t v551;
    uint64_t v552;
    uint64_t v554;
    uint64_t v556;
    uint64_t v557;
    uint64_t v559;
    uint64_t v561;
    uint64_t v562;
    uint64_t v563;
    uint64_t v564;
    uint64_t v565;
    uint64_t v567;
    uint64_t v568;
    uint64_t v569;
    uint64_t v570;
    uint64_t v571;
    uint64_t v573;
    uint64_t v575;
    uint64_t v576;
    unsigned char *v578;
    uint64_t v584;
    uint64_t v585;
    uint64_t v588;
    uint64_t v589;
    uint64_t v591;
    uint64_t v592;
    uint64_t v594;
    uint64_t v595;
    uint64_t v597;
    uint64_t v598;
    uint64_t v599;
    uint64_t v600;
    uint64_t v601;
    uint64_t v602;
    uint64_t v604;
    uint64_t v605;
    uint64_t v607;
    uint64_t v609;
    uint64_t v610;
    uint64_t v612;
    uint64_t v614;
    uint64_t v615;
    uint64_t v617;
    uint64_t v619;
    uint64_t v620;
    uint64_t v621;
    uint64_t v622;
    unsigned char *v624;
    uint64_t v625;
    uint64_t v626;
    uint64_t v627;
    uint64_t v629;
    uint64_t v630;
    uint64_t v631;
    uint64_t v632;
    uint64_t v634;
    uint64_t v635;
    unsigned char *v637;
    uint64_t v643;
    uint64_t v644;
    uint64_t v646;
    uint64_t v647;
    uint64_t v648;
    unsigned char *v650;
    uint64_t v652;
    uint64_t v653;
    unsigned char *v655;
    uint64_t v657;
    uint64_t v658;
    unsigned char *v660;
    uint64_t v662;
    uint64_t v663;
    uint64_t v664;
    uint64_t v666;
    uint64_t v667;
    uint64_t v669;
    unsigned char *v671;
    uint64_t v672;
    uint64_t v673;
    uint64_t v674;
    uint64_t v676;
    uint64_t v677;
    uint64_t v678;
    uint64_t v681;
    uint64_t v682;
    uint64_t v684;
    uint64_t t17;
    uint64_t t33;
    uint64_t t46;
    uint64_t t59;
    uint64_t t72;
    uint64_t t85;
    uint64_t t108;
    uint64_t t115;
    uint64_t t127;
    uint64_t t144;
    uint64_t t246;
    uint64_t t259;
    uint64_t t271;
    uint64_t t324;
    uint64_t t329;
    uint64_t t370;
    uint64_t t393;
    uint64_t t413;
    uint64_t t473;
    uint64_t t479;
    uint64_t t510;
    uint64_t t515;
    uint64_t t520;
    uint64_t t534;
    uint64_t t549;
    uint64_t t554;
    uint64_t t559;
    uint64_t t573;
    uint64_t t594;
    uint64_t t607;
    uint64_t t612;
    uint64_t t617;
    uint64_t t666;
    uint64_t t676;
    uint64_t t684;
    _Alignas(1) unsigned char s4[16];
    _Alignas(8) unsigned char s29[96];
    _Alignas(8) unsigned char s42[96];
    _Alignas(8) unsigned char s55[96];
    _Alignas(8) unsigned char s68[96];
    _Alignas(8) unsigned char s81[96];
    _Alignas(8) unsigned char s242[96];
    _Alignas(8) unsigned char s255[96];
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = s4;
    v5 = UINT64_C(0);
    exsi_st_n(v4 + 0, 8, v3);
    exsi_st_n(v4 + 8, 8, v5);
    v8 = UINT64_C(0);
    v9 = (v3 == v8);
    if (v9) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v11 = UINT64_C(11400714819323198485);
    exsi_st_n(v4 + 0, 8, v11);
    goto b3;
b3:
    v14 = UINT64_C(0);
    v15 = UINT64_C(8192);
    t17 = v14;
    v17 = t17;
    goto b4;
b4:
    v18 = (v17 < v15);
    if (v18) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v20 = UINT64_C(0);
    v21 = UINT64_C(12288);
    if (v17 >= v21) exsrt_abortus(1);
    v23 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v17 * 1);
    exsi_st_n(v23 + 0, 1, v20);
    goto b7;
b6:
    v29 = s29;
    v30 = UINT64_C(0);
    v31 = UINT64_C(0);
    t33 = v31;
    v33 = t33;
    goto b8;
b7:
    v26 = UINT64_C(1);
    v27 = v17 + v26;
    t17 = v27;
    v17 = t17;
    goto b4;
b8:
    v34 = UINT64_C(12);
    v35 = (v33 < v34);
    if (v35) {
        goto b9;
    } else {
        goto b10;
    }
b9:
    v37 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v33 * 8);
    exsi_st_n(v37 + 0, 8, v30);
    v39 = UINT64_C(1);
    v40 = v33 + v39;
    t33 = v40;
    v33 = t33;
    goto b8;
b10:
    v42 = s42;
    v43 = UINT64_C(0);
    v44 = UINT64_C(0);
    t46 = v44;
    v46 = t46;
    goto b11;
b11:
    v47 = UINT64_C(12);
    v48 = (v46 < v47);
    if (v48) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v50 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v46 * 8);
    exsi_st_n(v50 + 0, 8, v43);
    v52 = UINT64_C(1);
    v53 = v46 + v52;
    t46 = v53;
    v46 = t46;
    goto b11;
b13:
    v55 = s55;
    v56 = UINT64_C(0);
    v57 = UINT64_C(0);
    t59 = v57;
    v59 = t59;
    goto b14;
b14:
    v60 = UINT64_C(12);
    v61 = (v59 < v60);
    if (v61) {
        goto b15;
    } else {
        goto b16;
    }
b15:
    v63 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v59 * 8);
    exsi_st_n(v63 + 0, 8, v56);
    v65 = UINT64_C(1);
    v66 = v59 + v65;
    t59 = v66;
    v59 = t59;
    goto b14;
b16:
    v68 = s68;
    v69 = UINT64_C(0);
    v70 = UINT64_C(0);
    t72 = v70;
    v72 = t72;
    goto b17;
b17:
    v73 = UINT64_C(12);
    v74 = (v72 < v73);
    if (v74) {
        goto b18;
    } else {
        goto b19;
    }
b18:
    v76 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v72 * 8);
    exsi_st_n(v76 + 0, 8, v69);
    v78 = UINT64_C(1);
    v79 = v72 + v78;
    t72 = v79;
    v72 = t72;
    goto b17;
b19:
    v81 = s81;
    v82 = UINT64_C(0);
    v83 = UINT64_C(0);
    t85 = v83;
    v85 = t85;
    goto b20;
b20:
    v86 = UINT64_C(12);
    v87 = (v85 < v86);
    if (v87) {
        goto b21;
    } else {
        goto b22;
    }
b21:
    v89 = (unsigned char *)((uintptr_t)v81 + (uintptr_t)v85 * 8);
    exsi_st_n(v89 + 0, 8, v82);
    v91 = UINT64_C(1);
    v92 = v85 + v91;
    t85 = v92;
    v85 = t85;
    goto b20;
b22:
    v94 = UINT64_C(64);
    v95 = UINT64_C(0);
    v96 = UINT64_C(12);
    if (v95 >= v96) exsrt_abortus(1);
    v98 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v95 * 8);
    exsi_st_n(v98 + 0, 8, v94);
    v100 = UINT64_C(64);
    v101 = UINT64_C(0);
    v102 = UINT64_C(12);
    if (v101 >= v102) exsrt_abortus(1);
    v104 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v101 * 8);
    exsi_st_n(v104 + 0, 8, v100);
    v106 = UINT64_C(1);
    t108 = v106;
    v108 = t108;
    goto b23;
b23:
    v109 = UINT64_C(12);
    v110 = (v108 < v109);
    if (v110) {
        goto b24;
    } else {
        goto b25;
    }
b24:
    v112 = UINT64_C(0);
    v113 = UINT64_C(1);
    t127 = v112;
    t115 = v113;
    v127 = t127;
    v115 = t115;
    goto b26;
b25:
    v242 = s242;
    v243 = UINT64_C(0);
    v244 = UINT64_C(0);
    t246 = v244;
    v246 = t246;
    goto b35;
b26:
    v116 = (v115 < v108);
    if (v116) {
        goto b27;
    } else {
        goto b28;
    }
b27:
    v118 = UINT64_C(12);
    if (v115 >= v118) exsrt_abortus(1);
    v120 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v115 * 8);
    v121 = exsi_ld_n(v120 + 0, 8);
    v122 = UINT64_C(12);
    if (v115 >= v122) exsrt_abortus(1);
    v124 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v115 * 8);
    v125 = exsi_ld_n(v124 + 0, 8);
    v126 = exsi_mul_u(v121, v125, 64);
    v128 = UINT64_C(12);
    if (v127 >= v128) exsrt_abortus(1);
    v130 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v127 * 8);
    v131 = exsi_ld_n(v130 + 0, 8);
    v132 = UINT64_C(12);
    if (v127 >= v132) exsrt_abortus(1);
    v134 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v127 * 8);
    v135 = exsi_ld_n(v134 + 0, 8);
    v136 = exsi_mul_u(v131, v135, 64);
    v137 = (v126 > v136);
    if (v137) {
        goto b30;
    } else {
        t144 = v127;
        v144 = t144;
        goto b31;
    }
b28:
    v145 = UINT64_C(12);
    if (v127 >= v145) exsrt_abortus(1);
    v147 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v127 * 8);
    v148 = exsi_ld_n(v147 + 0, 8);
    v149 = UINT64_C(12);
    if (v127 >= v149) exsrt_abortus(1);
    v151 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v127 * 8);
    v152 = exsi_ld_n(v151 + 0, 8);
    v153 = (v148 >= v152);
    if (v153) {
        goto b32;
    } else {
        goto b33;
    }
b29:
    v141 = UINT64_C(1);
    v142 = v115 + v141;
    t127 = v144;
    t115 = v142;
    v127 = t127;
    v115 = t115;
    goto b26;
b30:
    t144 = v115;
    v144 = t144;
    goto b31;
b31:
    goto b29;
b32:
    v155 = UINT64_C(3);
    v156 = exsi_div_u(v148, v155, 64);
    v157 = UINT64_C(2);
    v158 = exsi_mul_u(v157, v156, 64);
    v159 = exsi_sub_u(v148, v158, 64);
    v160 = UINT64_C(1);
    v161 = exsi_add_u(v159, v160, 64);
    v162 = exs_infra(v4, v161);
    v163 = exsi_add_u(v156, v162, 64);
    v164 = UINT64_C(12);
    if (v127 >= v164) exsrt_abortus(1);
    v166 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v127 * 8);
    v167 = exsi_ld_n(v166 + 0, 8);
    v168 = exsi_add_u(v167, v163, 64);
    v169 = UINT64_C(12);
    if (v108 >= v169) exsrt_abortus(1);
    v171 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v108 * 8);
    exsi_st_n(v171 + 0, 8, v168);
    v173 = UINT64_C(12);
    if (v127 >= v173) exsrt_abortus(1);
    v175 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v127 * 8);
    v176 = exsi_ld_n(v175 + 0, 8);
    v177 = UINT64_C(12);
    if (v108 >= v177) exsrt_abortus(1);
    v179 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v108 * 8);
    exsi_st_n(v179 + 0, 8, v176);
    v181 = exsi_sub_u(v148, v163, 64);
    v182 = UINT64_C(12);
    if (v108 >= v182) exsrt_abortus(1);
    v184 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v108 * 8);
    exsi_st_n(v184 + 0, 8, v181);
    v186 = UINT64_C(12);
    if (v108 >= v186) exsrt_abortus(1);
    v188 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v108 * 8);
    exsi_st_n(v188 + 0, 8, v152);
    v190 = UINT64_C(12);
    if (v127 >= v190) exsrt_abortus(1);
    v192 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v127 * 8);
    exsi_st_n(v192 + 0, 8, v163);
    goto b34;
b33:
    v195 = UINT64_C(3);
    v196 = exsi_div_u(v152, v195, 64);
    v197 = UINT64_C(2);
    v198 = exsi_mul_u(v197, v196, 64);
    v199 = exsi_sub_u(v152, v198, 64);
    v200 = UINT64_C(1);
    v201 = exsi_add_u(v199, v200, 64);
    v202 = exs_infra(v4, v201);
    v203 = exsi_add_u(v196, v202, 64);
    v204 = UINT64_C(12);
    if (v127 >= v204) exsrt_abortus(1);
    v206 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v127 * 8);
    v207 = exsi_ld_n(v206 + 0, 8);
    v208 = UINT64_C(12);
    if (v108 >= v208) exsrt_abortus(1);
    v210 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v108 * 8);
    exsi_st_n(v210 + 0, 8, v207);
    v212 = UINT64_C(12);
    if (v127 >= v212) exsrt_abortus(1);
    v214 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v127 * 8);
    v215 = exsi_ld_n(v214 + 0, 8);
    v216 = exsi_add_u(v215, v203, 64);
    v217 = UINT64_C(12);
    if (v108 >= v217) exsrt_abortus(1);
    v219 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v108 * 8);
    exsi_st_n(v219 + 0, 8, v216);
    v221 = UINT64_C(12);
    if (v108 >= v221) exsrt_abortus(1);
    v223 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v108 * 8);
    exsi_st_n(v223 + 0, 8, v148);
    v225 = exsi_sub_u(v152, v203, 64);
    v226 = UINT64_C(12);
    if (v108 >= v226) exsrt_abortus(1);
    v228 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v108 * 8);
    exsi_st_n(v228 + 0, 8, v225);
    v230 = UINT64_C(12);
    if (v127 >= v230) exsrt_abortus(1);
    v232 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v127 * 8);
    exsi_st_n(v232 + 0, 8, v203);
    goto b34;
b34:
    v235 = UINT64_C(12);
    if (v108 >= v235) exsrt_abortus(1);
    v237 = (unsigned char *)((uintptr_t)v81 + (uintptr_t)v108 * 8);
    exsi_st_n(v237 + 0, 8, v127);
    v239 = UINT64_C(1);
    v240 = exsi_add_u(v108, v239, 64);
    t108 = v240;
    v108 = t108;
    goto b23;
b35:
    v247 = UINT64_C(12);
    v248 = (v246 < v247);
    if (v248) {
        goto b36;
    } else {
        goto b37;
    }
b36:
    v250 = (unsigned char *)((uintptr_t)v242 + (uintptr_t)v246 * 8);
    exsi_st_n(v250 + 0, 8, v243);
    v252 = UINT64_C(1);
    v253 = v246 + v252;
    t246 = v253;
    v246 = t246;
    goto b35;
b37:
    v255 = s255;
    v256 = UINT64_C(0);
    v257 = UINT64_C(0);
    t259 = v257;
    v259 = t259;
    goto b38;
b38:
    v260 = UINT64_C(12);
    v261 = (v259 < v260);
    if (v261) {
        goto b39;
    } else {
        goto b40;
    }
b39:
    v263 = (unsigned char *)((uintptr_t)v255 + (uintptr_t)v259 * 8);
    exsi_st_n(v263 + 0, 8, v256);
    v265 = UINT64_C(1);
    v266 = v259 + v265;
    t259 = v266;
    v259 = t259;
    goto b38;
b40:
    v268 = UINT64_C(0);
    v269 = UINT64_C(12);
    t271 = v268;
    v271 = t271;
    goto b41;
b41:
    v272 = (v271 < v269);
    if (v272) {
        goto b42;
    } else {
        goto b43;
    }
b42:
    v274 = UINT64_C(4);
    v275 = UINT64_C(12);
    if (v271 >= v275) exsrt_abortus(1);
    v277 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v271 * 8);
    v278 = exsi_ld_n(v277 + 0, 8);
    v279 = UINT64_C(5);
    v280 = exsi_sub_u(v278, v279, 64);
    v281 = exs_infra(v4, v280);
    v282 = exsi_add_u(v274, v281, 64);
    v283 = UINT64_C(4);
    v284 = UINT64_C(12);
    if (v271 >= v284) exsrt_abortus(1);
    v286 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v271 * 8);
    v287 = exsi_ld_n(v286 + 0, 8);
    v288 = UINT64_C(5);
    v289 = exsi_sub_u(v287, v288, 64);
    v290 = exs_infra(v4, v289);
    v291 = exsi_add_u(v283, v290, 64);
    v292 = UINT64_C(12);
    if (v271 >= v292) exsrt_abortus(1);
    v294 = (unsigned char *)((uintptr_t)v29 + (uintptr_t)v271 * 8);
    v295 = exsi_ld_n(v294 + 0, 8);
    v296 = UINT64_C(1);
    v297 = exsi_add_u(v295, v296, 64);
    v298 = UINT64_C(12);
    if (v271 >= v298) exsrt_abortus(1);
    v300 = (unsigned char *)((uintptr_t)v55 + (uintptr_t)v271 * 8);
    v301 = exsi_ld_n(v300 + 0, 8);
    v302 = UINT64_C(1);
    v303 = exsi_sub_u(v301, v302, 64);
    v304 = exsi_sub_u(v303, v282, 64);
    v305 = exs_infra(v4, v304);
    v306 = exsi_add_u(v297, v305, 64);
    v307 = UINT64_C(12);
    if (v271 >= v307) exsrt_abortus(1);
    v309 = (unsigned char *)((uintptr_t)v42 + (uintptr_t)v271 * 8);
    v310 = exsi_ld_n(v309 + 0, 8);
    v311 = UINT64_C(1);
    v312 = exsi_add_u(v310, v311, 64);
    v313 = UINT64_C(12);
    if (v271 >= v313) exsrt_abortus(1);
    v315 = (unsigned char *)((uintptr_t)v68 + (uintptr_t)v271 * 8);
    v316 = exsi_ld_n(v315 + 0, 8);
    v317 = UINT64_C(1);
    v318 = exsi_sub_u(v316, v317, 64);
    v319 = exsi_sub_u(v318, v291, 64);
    v320 = exs_infra(v4, v319);
    v321 = exsi_add_u(v312, v320, 64);
    v322 = exsi_add_u(v321, v291, 64);
    t324 = v321;
    v324 = t324;
    goto b45;
b43:
    v366 = exs_asperge(v1, v4);
    v367 = UINT64_C(0);
    v368 = UINT64_C(4);
    t370 = v367;
    v370 = t370;
    goto b53;
b44:
    v363 = UINT64_C(1);
    v364 = v271 + v363;
    t271 = v364;
    v271 = t271;
    goto b41;
b45:
    v325 = (v324 < v322);
    if (v325) {
        goto b46;
    } else {
        goto b47;
    }
b46:
    v327 = exsi_add_u(v306, v282, 64);
    t329 = v306;
    v329 = t329;
    goto b49;
b47:
    v348 = UINT64_C(1);
    v349 = exsi_shr_u(v282, v348, 64);
    v350 = exsi_add_u(v306, v349, 64);
    v351 = UINT64_C(12);
    if (v271 >= v351) exsrt_abortus(1);
    v353 = (unsigned char *)((uintptr_t)v242 + (uintptr_t)v271 * 8);
    exsi_st_n(v353 + 0, 8, v350);
    v355 = UINT64_C(1);
    v356 = exsi_shr_u(v291, v355, 64);
    v357 = exsi_add_u(v321, v356, 64);
    v358 = UINT64_C(12);
    if (v271 >= v358) exsrt_abortus(1);
    v360 = (unsigned char *)((uintptr_t)v255 + (uintptr_t)v271 * 8);
    exsi_st_n(v360 + 0, 8, v357);
    goto b44;
b48:
    v345 = UINT64_C(1);
    v346 = v324 + v345;
    t324 = v346;
    v324 = t324;
    goto b45;
b49:
    v330 = (v329 < v327);
    if (v330) {
        goto b50;
    } else {
        goto b51;
    }
b50:
    v332 = UINT64_C(1);
    v333 = UINT64_C(64);
    v334 = exsi_mul_u(v324, v333, 64);
    v335 = exsi_add_u(v334, v329, 64);
    v336 = UINT64_C(12288);
    if (v335 >= v336) exsrt_abortus(1);
    v338 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v335 * 1);
    exsi_st_n(v338 + 0, 1, v332);
    goto b52;
b51:
    goto b48;
b52:
    v341 = UINT64_C(1);
    v342 = v329 + v341;
    t329 = v342;
    v329 = t329;
    goto b49;
b53:
    v371 = (v370 < v368);
    if (v371) {
        goto b54;
    } else {
        goto b55;
    }
b54:
    v373 = UINT64_C(2);
    v374 = exsi_rem_u(v370, v373, 64);
    v375 = UINT64_C(0);
    v376 = (v374 == v375);
    if (v376) {
        goto b57;
    } else {
        goto b58;
    }
b55:
    v390 = UINT64_C(0);
    v391 = UINT64_C(4096);
    t393 = v390;
    v393 = t393;
    goto b60;
b56:
    v387 = UINT64_C(1);
    v388 = v370 + v387;
    t370 = v388;
    v370 = t370;
    goto b53;
b57:
    v378 = UINT64_C(4096);
    v379 = UINT64_C(0);
    v380 = exs_leniga(v1, v378, v379);
    (void)v380;
    goto b59;
b58:
    v382 = UINT64_C(0);
    v383 = UINT64_C(4096);
    v384 = exs_leniga(v1, v382, v383);
    (void)v384;
    goto b59;
b59:
    goto b56;
b60:
    v394 = (v393 < v391);
    if (v394) {
        goto b61;
    } else {
        goto b62;
    }
b61:
    v396 = UINT64_C(4096);
    v397 = exsi_add_u(v396, v393, 64);
    v398 = UINT64_C(12288);
    if (v397 >= v398) exsrt_abortus(1);
    v400 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v397 * 1);
    v401 = exsi_norm_u(exsi_ld_n(v400 + 0, 1), 8);
    v402 = UINT64_C(12288);
    if (v393 >= v402) exsrt_abortus(1);
    v404 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v393 * 1);
    exsi_st_n(v404 + 0, 1, v401);
    goto b63;
b62:
    v410 = UINT64_C(1);
    v411 = UINT64_C(12);
    t413 = v410;
    v413 = t413;
    goto b64;
b63:
    v407 = UINT64_C(1);
    v408 = v393 + v407;
    t393 = v408;
    v393 = t393;
    goto b60;
b64:
    v414 = (v413 < v411);
    if (v414) {
        goto b65;
    } else {
        goto b66;
    }
b65:
    v416 = UINT64_C(12);
    if (v413 >= v416) exsrt_abortus(1);
    v418 = (unsigned char *)((uintptr_t)v242 + (uintptr_t)v413 * 8);
    v419 = exsi_ld_n(v418 + 0, 8);
    v420 = UINT64_C(12);
    if (v413 >= v420) exsrt_abortus(1);
    v422 = (unsigned char *)((uintptr_t)v255 + (uintptr_t)v413 * 8);
    v423 = exsi_ld_n(v422 + 0, 8);
    v424 = UINT64_C(12);
    if (v413 >= v424) exsrt_abortus(1);
    v426 = (unsigned char *)((uintptr_t)v81 + (uintptr_t)v413 * 8);
    v427 = exsi_ld_n(v426 + 0, 8);
    v428 = UINT64_C(12);
    if (v427 >= v428) exsrt_abortus(1);
    v430 = (unsigned char *)((uintptr_t)v242 + (uintptr_t)v427 * 8);
    v431 = exsi_ld_n(v430 + 0, 8);
    v432 = UINT64_C(12);
    if (v413 >= v432) exsrt_abortus(1);
    v434 = (unsigned char *)((uintptr_t)v81 + (uintptr_t)v413 * 8);
    v435 = exsi_ld_n(v434 + 0, 8);
    v436 = UINT64_C(12);
    if (v435 >= v436) exsrt_abortus(1);
    v438 = (unsigned char *)((uintptr_t)v255 + (uintptr_t)v435 * 8);
    v439 = exsi_ld_n(v438 + 0, 8);
    v440 = exs_proximus(v4);
    v441 = UINT64_C(63);
    v442 = exsi_shr_u(v440, v441, 64);
    v443 = UINT64_C(0);
    v444 = (v442 == v443);
    if (v444) {
        goto b68;
    } else {
        goto b69;
    }
b66:
    v456 = UINT64_C(0);
    v457 = UINT64_C(12);
    if (v456 >= v457) exsrt_abortus(1);
    v459 = (unsigned char *)((uintptr_t)v255 + (uintptr_t)v456 * 8);
    v460 = exsi_ld_n(v459 + 0, 8);
    v461 = UINT64_C(64);
    v462 = exsi_mul_u(v460, v461, 64);
    v463 = UINT64_C(0);
    v464 = UINT64_C(12);
    if (v463 >= v464) exsrt_abortus(1);
    v466 = (unsigned char *)((uintptr_t)v242 + (uintptr_t)v463 * 8);
    v467 = exsi_ld_n(v466 + 0, 8);
    v468 = exsi_add_u(v462, v467, 64);
    v469 = exs_fig_dungeon_prune(v1, v468);
    v470 = UINT64_C(1);
    v471 = UINT64_C(63);
    t473 = v470;
    v473 = t473;
    goto b71;
b67:
    v453 = UINT64_C(1);
    v454 = v413 + v453;
    t413 = v454;
    v413 = t413;
    goto b64;
b68:
    v446 = exs_hori(v1, v423, v419, v431);
    (void)v446;
    v447 = exs_vert(v1, v431, v423, v439);
    (void)v447;
    goto b70;
b69:
    v449 = exs_vert(v1, v419, v423, v439);
    (void)v449;
    v450 = exs_hori(v1, v439, v419, v431);
    (void)v450;
    goto b70;
b70:
    goto b67;
b71:
    v474 = (v473 < v471);
    if (v474) {
        goto b72;
    } else {
        goto b73;
    }
b72:
    v476 = UINT64_C(1);
    v477 = UINT64_C(63);
    t479 = v476;
    v479 = t479;
    goto b75;
b73:
    v591 = UINT64_C(0);
    v592 = UINT64_C(10);
    t594 = v591;
    v594 = t594;
    goto b105;
b74:
    v588 = UINT64_C(1);
    v589 = v473 + v588;
    t473 = v589;
    v473 = t473;
    goto b71;
b75:
    v480 = (v479 < v477);
    if (v480) {
        goto b76;
    } else {
        goto b77;
    }
b76:
    v482 = UINT64_C(64);
    v483 = exsi_mul_u(v473, v482, 64);
    v484 = exsi_add_u(v483, v479, 64);
    v485 = UINT64_C(12288);
    if (v484 >= v485) exsrt_abortus(1);
    v487 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v484 * 1);
    v488 = exsi_norm_u(exsi_ld_n(v487 + 0, 1), 8);
    v489 = UINT64_C(1);
    v490 = (v488 == v489);
    if (v490) {
        goto b79;
    } else {
        goto b80;
    }
b77:
    goto b74;
b78:
    v584 = UINT64_C(1);
    v585 = v479 + v584;
    t479 = v585;
    v479 = t479;
    goto b75;
b79:
    v492 = UINT64_C(64);
    v493 = exsi_sub_u(v484, v492, 64);
    v494 = exs_passabile(v1, v493);
    v495 = UINT64_C(64);
    v496 = exsi_add_u(v484, v495, 64);
    v497 = exs_passabile(v1, v496);
    v498 = UINT64_C(1);
    v499 = exsi_sub_u(v484, v498, 64);
    v500 = exs_passabile(v1, v499);
    v501 = UINT64_C(1);
    v502 = exsi_add_u(v484, v501, 64);
    v503 = exs_passabile(v1, v502);
    v504 = UINT64_C(0);
    v505 = (v500 == v504);
    if (v505) {
        goto b81;
    } else {
        t510 = v505;
        v510 = t510;
        goto b82;
    }
b80:
    goto b78;
b81:
    v507 = UINT64_C(0);
    v508 = (v503 == v507);
    t510 = v508;
    v510 = t510;
    goto b82;
b82:
    if (v510) {
        goto b83;
    } else {
        t515 = v510;
        v515 = t515;
        goto b84;
    }
b83:
    v512 = UINT64_C(1);
    v513 = (v494 == v512);
    t515 = v513;
    v515 = t515;
    goto b84;
b84:
    if (v515) {
        goto b85;
    } else {
        t520 = v515;
        v520 = t520;
        goto b86;
    }
b85:
    v517 = UINT64_C(1);
    v518 = (v497 == v517);
    t520 = v518;
    v520 = t520;
    goto b86;
b86:
    if (v520) {
        goto b87;
    } else {
        goto b88;
    }
b87:
    v522 = UINT64_C(64);
    v523 = exsi_sub_u(v484, v522, 64);
    v524 = exs_apertum(v1, v523);
    v525 = UINT64_C(1);
    v526 = (v524 == v525);
    if (v526) {
        t534 = v526;
        v534 = t534;
        goto b90;
    } else {
        goto b89;
    }
b88:
    v543 = UINT64_C(0);
    v544 = (v494 == v543);
    if (v544) {
        goto b94;
    } else {
        t549 = v544;
        v549 = t549;
        goto b95;
    }
b89:
    v528 = UINT64_C(64);
    v529 = exsi_add_u(v484, v528, 64);
    v530 = exs_apertum(v1, v529);
    v531 = UINT64_C(1);
    v532 = (v530 == v531);
    t534 = v532;
    v534 = t534;
    goto b90;
b90:
    if (v534) {
        goto b91;
    } else {
        goto b92;
    }
b91:
    v536 = UINT64_C(2);
    v537 = UINT64_C(12288);
    if (v484 >= v537) exsrt_abortus(1);
    v539 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v484 * 1);
    exsi_st_n(v539 + 0, 1, v536);
    goto b92;
b92:
    goto b93;
b93:
    goto b80;
b94:
    v546 = UINT64_C(0);
    v547 = (v497 == v546);
    t549 = v547;
    v549 = t549;
    goto b95;
b95:
    if (v549) {
        goto b96;
    } else {
        t554 = v549;
        v554 = t554;
        goto b97;
    }
b96:
    v551 = UINT64_C(1);
    v552 = (v500 == v551);
    t554 = v552;
    v554 = t554;
    goto b97;
b97:
    if (v554) {
        goto b98;
    } else {
        t559 = v554;
        v559 = t559;
        goto b99;
    }
b98:
    v556 = UINT64_C(1);
    v557 = (v503 == v556);
    t559 = v557;
    v559 = t559;
    goto b99;
b99:
    if (v559) {
        goto b100;
    } else {
        goto b93;
    }
b100:
    v561 = UINT64_C(1);
    v562 = exsi_sub_u(v484, v561, 64);
    v563 = exs_apertum(v1, v562);
    v564 = UINT64_C(1);
    v565 = (v563 == v564);
    if (v565) {
        t573 = v565;
        v573 = t573;
        goto b102;
    } else {
        goto b101;
    }
b101:
    v567 = UINT64_C(1);
    v568 = exsi_add_u(v484, v567, 64);
    v569 = exs_apertum(v1, v568);
    v570 = UINT64_C(1);
    v571 = (v569 == v570);
    t573 = v571;
    v573 = t573;
    goto b102;
b102:
    if (v573) {
        goto b103;
    } else {
        goto b104;
    }
b103:
    v575 = UINT64_C(2);
    v576 = UINT64_C(12288);
    if (v484 >= v576) exsrt_abortus(1);
    v578 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v484 * 1);
    exsi_st_n(v578 + 0, 1, v575);
    goto b104;
b104:
    goto b93;
b105:
    v595 = (v594 < v592);
    if (v595) {
        goto b106;
    } else {
        goto b107;
    }
b106:
    v597 = UINT64_C(64);
    v598 = exs_infra(v4, v597);
    v599 = UINT64_C(64);
    v600 = exs_infra(v4, v599);
    v601 = UINT64_C(1);
    v602 = (v598 >= v601);
    if (v602) {
        goto b109;
    } else {
        t607 = v602;
        v607 = t607;
        goto b110;
    }
b107:
    v646 = exsi_ld_n(v4 + 8, 8);
    v647 = UINT64_C(0);
    v648 = UINT64_C(3);
    if (v647 >= v648) exsrt_abortus(1);
    v650 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v647 * 8);
    exsi_st_n(v650 + 0, 8, v646);
    v652 = UINT64_C(1);
    v653 = UINT64_C(3);
    if (v652 >= v653) exsrt_abortus(1);
    v655 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v652 * 8);
    exsi_st_n(v655 + 0, 8, v366);
    v657 = UINT64_C(2);
    v658 = UINT64_C(3);
    if (v657 >= v658) exsrt_abortus(1);
    v660 = (unsigned char *)((uintptr_t)v2 + (uintptr_t)v657 * 8);
    exsi_st_n(v660 + 0, 8, v469);
    v662 = UINT64_C(0);
    v663 = UINT64_C(0);
    v664 = UINT64_C(4096);
    t676 = v662;
    t666 = v663;
    v676 = t676;
    v666 = t666;
    goto b121;
b108:
    v643 = UINT64_C(1);
    v644 = v594 + v643;
    t594 = v644;
    v594 = t594;
    goto b105;
b109:
    v604 = UINT64_C(62);
    v605 = (v598 <= v604);
    t607 = v605;
    v607 = t607;
    goto b110;
b110:
    if (v607) {
        goto b111;
    } else {
        t612 = v607;
        v612 = t612;
        goto b112;
    }
b111:
    v609 = UINT64_C(1);
    v610 = (v600 >= v609);
    t612 = v610;
    v612 = t612;
    goto b112;
b112:
    if (v612) {
        goto b113;
    } else {
        t617 = v612;
        v617 = t617;
        goto b114;
    }
b113:
    v614 = UINT64_C(62);
    v615 = (v600 <= v614);
    t617 = v615;
    v617 = t617;
    goto b114;
b114:
    if (v617) {
        goto b115;
    } else {
        goto b116;
    }
b115:
    v619 = UINT64_C(64);
    v620 = exsi_mul_u(v600, v619, 64);
    v621 = exsi_add_u(v620, v598, 64);
    v622 = UINT64_C(12288);
    if (v621 >= v622) exsrt_abortus(1);
    v624 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v621 * 1);
    v625 = exsi_norm_u(exsi_ld_n(v624 + 0, 1), 8);
    v626 = UINT64_C(1);
    v627 = (v625 == v626);
    if (v627) {
        goto b117;
    } else {
        goto b118;
    }
b116:
    goto b108;
b117:
    v629 = UINT64_C(0);
    v630 = exs_muri_circum(v1, v629, v621);
    v631 = UINT64_C(0);
    v632 = (v630 == v631);
    if (v632) {
        goto b119;
    } else {
        goto b120;
    }
b118:
    goto b116;
b119:
    v634 = UINT64_C(3);
    v635 = UINT64_C(12288);
    if (v621 >= v635) exsrt_abortus(1);
    v637 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v621 * 1);
    exsi_st_n(v637 + 0, 1, v634);
    goto b120;
b120:
    goto b118;
b121:
    v667 = (v666 < v664);
    if (v667) {
        goto b122;
    } else {
        goto b123;
    }
b122:
    v669 = UINT64_C(12288);
    if (v666 >= v669) exsrt_abortus(1);
    v671 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v666 * 1);
    v672 = exsi_norm_u(exsi_ld_n(v671 + 0, 1), 8);
    v673 = UINT64_C(0);
    v674 = (v672 != v673);
    if (v674) {
        goto b125;
    } else {
        t684 = v676;
        v684 = t684;
        goto b126;
    }
b123:
    return v676;
b124:
    v681 = UINT64_C(1);
    v682 = v666 + v681;
    t676 = v684;
    t666 = v682;
    v676 = t676;
    v666 = t666;
    goto b121;
b125:
    v677 = UINT64_C(1);
    v678 = exsi_add_u(v676, v677, 64);
    t684 = v678;
    v684 = t684;
    goto b126;
b126:
    goto b124;
}

uint64_t exs_fig_dungeon_crc32(unsigned char *p0)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    unsigned char *v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v34;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v42;
    uint64_t v43;
    uint64_t v45;
    uint64_t v46;
    uint64_t t6;
    uint64_t t9;
    uint64_t t19;
    uint64_t t22;
    uint64_t t40;
    v1 = p0;
    v2 = UINT64_C(4294967295);
    v3 = UINT64_C(0);
    v4 = UINT64_C(4096);
    t9 = v2;
    t6 = v3;
    v9 = t9;
    v6 = t6;
    goto b2;
b2:
    v7 = (v6 < v4);
    if (v7) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v10 = UINT64_C(12288);
    if (v6 >= v10) exsrt_abortus(1);
    v12 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v6 * 1);
    v13 = exsi_norm_u(exsi_ld_n(v12 + 0, 1), 8);
    v14 = exsi_norm_u(exsi_norm_u(v13, 8), 32);
    v15 = v9 ^ v14;
    v16 = UINT64_C(0);
    v17 = UINT64_C(8);
    t22 = v15;
    t19 = v16;
    v22 = t22;
    v19 = t19;
    goto b6;
b4:
    v45 = UINT64_C(4294967295);
    v46 = v9 ^ v45;
    return v46;
b5:
    v42 = UINT64_C(1);
    v43 = v6 + v42;
    t9 = v22;
    t6 = v43;
    v9 = t9;
    v6 = t6;
    goto b2;
b6:
    v20 = (v19 < v17);
    if (v20) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v23 = UINT64_C(1);
    v24 = v22 & v23;
    v25 = UINT64_C(1);
    v26 = (v24 == v25);
    if (v26) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    goto b5;
b9:
    v37 = UINT64_C(1);
    v38 = v19 + v37;
    t22 = v40;
    t19 = v38;
    v22 = t22;
    v19 = t19;
    goto b6;
b10:
    v28 = UINT64_C(1);
    v29 = exsi_shr_u(v22, v28, 32);
    v30 = UINT64_C(3988292384);
    v31 = v29 ^ v30;
    t40 = v31;
    v40 = t40;
    goto b12;
b11:
    v33 = UINT64_C(1);
    v34 = exsi_shr_u(v22, v33, 32);
    t40 = v34;
    v40 = t40;
    goto b12;
b12:
    goto b9;
}

