// SPDX-License-Identifier: MIT
//
// GENERATED by tools/schema/level_vocab.py from tools/schema/level_vocab.json.
// Do not edit. nix/checks/level-vocab.nix regenerates this and diffs it.

export const LIMITS = {
  brushes: 256,
  faces: 1536,
  spawns: 64,
  classnames: 32,
  coord: 32767,
};

// size = arrow length or box half-extent, in world units.
// shape: 'arrow' | 'box' | 'cylinder' | 'diamond' | 'wireframe'
export const ENTITY_PALETTE = {
  info_player_start: { color: 0x44ff44, size: 24, shape: 'arrow', label: 'START' },
  info_enemy:        { color: 0xff4444, size: 24, shape: 'arrow', label: 'ENEMY' },
  info_heavy:        { color: 0x8b0000, size: 32, shape: 'arrow', label: 'HEAVY' },
  info_health:       { color: 0x00cc44, size: 6, shape: 'box', label: 'HP' },
  info_ammo:         { color: 0xffd700, size: 6, shape: 'box', label: 'AMMO' },
  info_armor:        { color: 0x4488ff, size: 6, shape: 'box', label: 'ARM' },
  info_npc:          { color: 0x88ccff, size: 10, shape: 'cylinder', label: 'NPC' },
  info_key_door:     { color: 0xff3333, size: 14, shape: 'box', label: 'DOOR' },
  info_alien:        { color: 0x99ff66, size: 22, shape: 'arrow', label: 'ALIEN' },
  info_barrel:       { color: 0xff8800, size: 8, shape: 'cylinder', label: 'BARREL' },
  info_chest:        { color: 0x8b4513, size: 12, shape: 'box', label: 'CHEST' },
  info_droid:        { color: 0xc0c0c0, size: 20, shape: 'box', label: 'DROID' },
  info_key_red:      { color: 0xff4444, size: 6, shape: 'diamond', label: 'KEY' },
  info_switch:       { color: 0x00f5d4, size: 6, shape: 'box', label: 'SW' },
  info_trigger:      { color: 0xff00ff, size: 0, shape: 'wireframe', label: 'TRIG' },
};

export const KNOWN_CLASSNAMES = Object.keys(ENTITY_PALETTE);

// Typed epair forms. 'generic' epairs remain available below these.
export const EPAIR_SCHEMAS = {
  info_npc: [
    { key: 'dialogue', label: 'dialogue', type: 'text', default: '...' },
  ],
  info_key_door: [
    { key: 'key_id', label: 'key_id', type: 'number', default: 1 },
  ],
  info_alien: [
    { key: 'speed', label: 'speed', type: 'number', default: 10 },
    { key: 'path', label: 'path', type: 'select', options: [{ value: 'approach', label: 'approach' }, { value: 'approach_late', label: 'approach late' }], default: 'approach' },
  ],
  info_chest: [
    { key: 'contents', label: 'contents', type: 'select', options: [{ value: '1', label: 'key_red' }, { value: '0', label: '(none)' }], default: '0' },
  ],
  info_droid: [
    { key: 'radius', label: 'orbit radius', type: 'number', default: 30 },
    { key: 'phase', label: 'orbit phase°', type: 'number', default: 0 },
  ],
  info_switch: [
    { key: 'target_door', label: 'target_door', type: 'door_select', default: 0 },
  ],
  info_trigger: [
    { key: 'mins', label: 'mins', type: 'vec3', default: '0 0 0' },
    { key: 'maxs', label: 'maxs', type: 'vec3', default: '0 0 0' },
    { key: 'event_id', label: 'event_id', type: 'number', default: 0 },
    { key: 'type', label: 'type', type: 'select', options: [{ value: '0', label: 'once' }, { value: '1', label: 'multiple' }, { value: '2', label: 'push' }], default: '0' },
  ],
};

// The canonical 6-face corner table, as data. 0 = mins, 1 = maxs, per axis.
export const AABB_FACE_CORNERS = [
  [[0, 0, 0], [0, 1, 0], [0, 0, 1]], // -X
  [[1, 0, 0], [1, 0, 1], [1, 1, 0]], // +X
  [[0, 0, 0], [0, 0, 1], [1, 0, 0]], // -Y
  [[0, 1, 0], [1, 1, 0], [0, 1, 1]], // +Y
  [[0, 0, 0], [1, 0, 0], [0, 1, 0]], // -Z
  [[0, 0, 1], [0, 1, 1], [1, 0, 1]], // +Z
];

export const AABB_FACE_NAMES = ["-X", "+X", "-Y", "+Y", "-Z", "+Z"];
