// SPDX-License-Identifier: MPL-2.0
//
// pm_lab_gen.h — GENERATED by PetaByte-Madness/tools/dank_lab_gen.py.
// Do not edit.
//
// Regenerate:
//   python3 PetaByte-Madness/tools/dank_lab_gen.py \
//       --emit-header PetaByte-Madness/src/pm_lab_gen.h
//
// Every value is in WORLD units: this generator authors in
// centimetres and the runtime is 64 units to the metre, so the
// factor 0.64 is already applied here and NO call site should
// apply it again. See the generator's emit_header comment for the
// hand-derived literals this replaces and why they were a hazard.

#ifndef PM_LAB_GEN_H
#define PM_LAB_GEN_H

// ── The room, MEASURED from the built mesh ──────────────────────────
// Not from the envelope constants: the shell is built from RX/RZ/RY but
// the hall and the dock run well outside it, and the collision has to
// match what is actually drawn.
#define PM_LAB_X0   (-451.8f)
#define PM_LAB_X1   (179.2f)
#define PM_LAB_Y0   (0.0f)
#define PM_LAB_Y1   (160.0f)
#define PM_LAB_Z0   (-147.2f)
#define PM_LAB_Z1   (171.5f)

// The main room's own envelope, without the hall and dock. This is the
// volume a camera framing "the lab" should stay inside.
#define PM_LAB_ROOM_HALF_X  (179.2f)
#define PM_LAB_ROOM_HALF_Z  (147.2f)
#define PM_LAB_CEILING      (160.0f)

// ── The doorway out, and what is beyond it ──────────────────────────
#define PM_LAB_DOOR_Z0   (7.7f)
#define PM_LAB_DOOR_Z1   (81.9f)
#define PM_LAB_DOOR_Y    (126.7f)
#define PM_LAB_HALL_X    (-396.8f)  // far end of the corridor
#define PM_LAB_TRUNK_X   (-448.0f)  // submersible hatch face
#define PM_LAB_COLLAR_Y  (62.7f)
#define PM_LAB_COLLAR_Z  (44.8f)
#define PM_LAB_COLLAR_R  (33.3f)

// ── The MRI scanner ────────────────────────────────────────────────
// The fixture the whole intro is about. pm_intake.c used to restate
// its centre as POS_MRI_X (-70.0f * CM).
#define PM_MRI_X       (-44.8f)
#define PM_MRI_Y       (69.1f)  // bore axis height
#define PM_MRI_Z_FACE  (-35.2f)  // the end he walks up to
#define PM_MRI_Z_BACK  (-142.1f)
#define PM_MRI_R_OUT   (58.9f)  // shell radius; clearance to keep
#define PM_MRI_R_BORE  (21.8f)  // the hole he goes into
// Centre of the bore mouth: where a camera should look, and where a
// walk-up path should end.
#define PM_MRI_MOUTH_Z (-35.2f)

// ── The desk ───────────────────────────────────────────────────────
#define PM_DESK_X   (113.9f)  // workstations(): STOOL_X
#define PM_DESK_Z   (21.8f)  // workstations(): STOOL_Z
#define PM_DESK_SEAT_Y (32.0f)  // the stool's top face

// ── The authored light rig ─────────────────────────────────────────
// This generator bakes vertex lighting from a 12-fixture rig and then
// throws the rig away — the OBJ carries the result, not the sources.
// The runtime lit this room with ONE directional light plus
// kiln_engine.c's generic "avoid pure black" ambient of 45, which is a
// bootstrap default and not an exposure anyone chose for a flooded
// station. Publishing the rig lets pm_env.c derive its key and fill
// from the light the room was actually authored under.
//
// Positions are world units; colour is 0-255; radius is world units;
// intensity is the generator's own 0..~1 scalar. Sorted brightest
// first (intensity / distance falls off, so the strongest fixtures
// come first) because KilnScene carries only
// KILN_SCENE_MAX_LIGHTS of them and the consumer takes a prefix.
#define PM_LAB_LIGHT_COUNT 12

// { x, y, z, r, g, b, radius, intensity }
#define PM_LAB_LIGHT_TABLE \
    {    -44.8f,    64.0f,    -32.0f,  70, 210, 235,   169.6f, 1.05f }, \
    {   -422.4f,    62.7f,     44.8f, 248, 186,  96,   192.0f, 1.05f }, \
    {    -61.4f,   137.0f,    -29.4f, 188, 214, 198,   211.2f, 0.95f }, \
    {    148.5f,    71.7f,     12.8f,  74, 226, 150,   128.0f, 0.80f }, \
    {   -115.2f,    83.2f,    121.6f, 104, 236, 132,   112.0f, 0.78f }, \
    {     75.5f,   139.5f,     61.4f, 188, 214, 198,   192.0f, 0.72f }, \
    {    -76.8f,   112.0f,    142.1f,  34, 104, 118,   169.6f, 0.72f }, \
    {     38.4f,   112.0f,    142.1f,  34, 104, 118,   169.6f, 0.72f }, \
    {    -76.8f,    83.2f,    121.6f, 104, 236, 132,   105.6f, 0.66f }, \
    {   -211.2f,   119.0f,     44.8f, 188, 214, 198,   134.4f, 0.60f }, \
    {    154.9f,    97.3f,    115.2f, 236, 100,  60,    96.0f, 0.50f }, \
    {   -358.4f,   119.0f,     44.8f, 188, 214, 198,   121.6f, 0.34f },

// The generator's own ambient floor: "dank teal, never fully black".
// Emitted as 0-255 to match KilnScene.ambient.
#define PM_LAB_AMBIENT_R 15
#define PM_LAB_AMBIENT_G 21
#define PM_LAB_AMBIENT_B 23

#endif // PM_LAB_GEN_H
