// SPDX-License-Identifier: MPL-2.0
//
// pm_lab.h — the playable lab, before the transformation.
//
// The one section of the intro the player drives. He walks Horner around
// the station in first person, reads what is lying about, and activates
// the MRI when he decides to — it is not a timer and not a trigger volume.
// A man doing this to himself has to press the button.
//
// ── First person, and why that is the right call here ──────────────────
// The opening cinematic shows Horner in third person and then flies the
// camera into his head (pm_demo's LAB_CINE shot ends there; pm_lab_enter
// picks up from that exact eye). From then until the beach you never see
// his body — which is what makes the reveal land, because the first time
// you see what he became, it is killing someone with it.
//
// It is also the cheap answer: kiln_fpscam, kiln_clip and the whole
// first-person path are already built and working in this ROM.
//
// ── Readables are actors, not a special case ───────────────────────────
// Every readable is a KILN_ACTOR_CAT_PROP actor, which kiln_context_scan
// already reports as KILN_CTX_USE. So "what does A do right now" is the
// engine's existing answer, and pm_lab only decides what USE means for
// the profile under the cursor: a note opens kiln_dialogue, the MRI ends
// the section.
//
// ── The collision is hand-authored ─────────────────────────────────────
// dank_lab.obj is geometry, not brushes — there is no collision mesh in
// the drop and kiln_map only reads Quake .map files. The lab is a box with
// a few obstacles, so six brushes plus a handful of blockers is both
// cheaper and more predictable than deriving collision from 1,538
// triangles. If the lab ever gets complicated enough that this stops
// being true, author it as a .map and use kiln_map instead.

#ifndef PM_LAB_H
#define PM_LAB_H

#include <kiln/kiln_actor.h>
#include <kiln/kiln_clip.h>   // KilnBrush, for pm_lab_brushes below
#include <kiln/kiln_fpscam.h>

// Generated by dank_lab_gen.py --emit-header: the room's measured extents, the
// scanner's position and clearance, the desk, and the light rig the vertex
// colours were baked under. Everything below derives from it rather than
// restating it.
#include "pm_lab_gen.h"
#include <kiln/kiln_input.h>
#include <kiln/kiln_engine.h>

// ── The room's real extents, DERIVED ────────────────────────────────────
// Every one of these used to be a literal, hand-computed from
// dank_lab_gen.py's constants with the multiply written out in a comment
// ("STOOL_X (178) * 0.64"). They are now derived from pm_lab_gen.h, which that
// generator emits by MEASURING the mesh it just built.
//
// The names are kept so no call site changes, and because they still mean the
// same thing: the extents of what is actually drawn, shared so pm_demo.c's
// LAB_CINE camera, pm_intake.c's intake camera and this room's own collision
// cannot disagree. What changes is that they can no longer drift from the
// geometry — which is not a hypothetical: pm_models.h records
// PM_ISLAND_HALF_W, a literal derived exactly this way, silently drifting from
// the island's real radius the moment the island was regenerated, and every
// camera keyed off it being wrong afterwards.
//
// Regenerate with:
//   python3 PetaByte-Madness/tools/dank_lab_gen.py \
//       --emit-header PetaByte-Madness/src/pm_lab_gen.h
// nix/checks/pm-gen-headers.nix fails if that is out of date, or if the
// generator and the committed dank_lab.obj stop agreeing about the room's size.
#define PM_LAB_REAL_X0   PM_LAB_X0
#define PM_LAB_REAL_X1   PM_LAB_X1
#define PM_LAB_REAL_Y0   PM_LAB_Y0
#define PM_LAB_REAL_Y1   PM_LAB_Y1
#define PM_LAB_REAL_Z0   PM_LAB_Z0
#define PM_LAB_REAL_Z1   PM_LAB_Z1

// ── Set dressing near the MRI, shared across every screen that shows it ─
// The desk is the generator's own stool position; the seat height likewise, so
// "sit him on it" no longer means "type 96 cm and hope".
#define PM_LAB_DESK_X    PM_DESK_X
#define PM_LAB_DESK_Y    (PM_DESK_SEAT_Y + 29.4f)  // hip above the seat face
#define PM_LAB_DESK_Z    PM_DESK_Z

// ── Where Horner's model origin is ──────────────────────────────────────
// His ROOT BONE, not his feet — ph_rig_export.py rebases the mesh onto the
// root pivot on the way out, and its header says why at length. So the Y a
// caller passes when drawing PM_MODEL_HORNER is his HIP height, and standing
// on the floor is this value, not zero.
//
// 96 cm is ph_rig.py's JOINTS[0] root pivot; 0.64 is the world scale (cm ->
// m -> baseScale 64), the same conversion pm_intake.c's CM macro applies and
// the same one PM_LAB_REAL_* is derived through. nix/checks/pm-rigs.nix
// asserts this equals the origin height the rig JSON declares, so the two
// cannot drift.
//
// It cost a bug worth remembering: drawn feet-first at this value, he stood
// 96 cm off the floor with his head through the ceiling for the whole intake,
// and the only symptom was cutscene cameras aimed at him photographing empty
// room. Two call sites disagreed by exactly this number and neither was
// obviously wrong on its own.
#define PM_HORNER_HIP_Y  (96.0f * 0.64f)

// The arms are the one thing here with no generator counterpart — they are
// tools/blender/lab_arms.py's own model, placed by hand. But the CONSTRAINT on
// where they can go is the scanner's shell radius, so that part is derived: far
// enough off the bore axis to clear it, on the wall side.
#define PM_LAB_ARMS_X    (PM_MRI_X + PM_MRI_R_OUT)   // just clear of the shell
#define PM_LAB_ARMS_Y     (89.6f)   // high on the wall, reaching down to table height
#define PM_LAB_ARMS_Z      (0.0f)

/** The lab's actor profiles, appended after the demons'. Handed to
 *  pm_actors_table, which is what kiln_actor_system_init actually sees. */
const KilnActorProfile *pm_lab_profiles(void);
int pm_lab_profile_count(void);

/** Give `cam` the player's body: the AABB and the movement constants, both
 *  sized for this world's 64 units per metre. Does NOT position the camera
 *  or touch the clip world — callers follow it with kiln_fpscam_snap.
 *
 *  Every first-person screen must go through this. PM_SCREEN_LAB gets it
 *  via pm_lab_enter; PM_SCREEN_PLAY calls it directly, because the two used
 *  to hold separate copies of these numbers at two different world scales
 *  and the gameplay one was wrong. See the definition. */
void pm_lab_body(KilnFpsCam *cam);

/** Eye height above the feet, in world units — what to add to a floor-level
 *  spawn point to get the position kiln_fpscam_snap wants. */
float pm_lab_eye_height(void);

/** Install the lab's clip world, spawn its props, and place the player at
 *  `eye` looking along `yaw` — the pose the opening cinematic's camera
 *  finished on, so the cut into first person does not jump. */
void pm_lab_enter(KilnFpsCam *cam, fm_vec3_t eye, float yaw);

/** Despawn the lab's props and drop its clip world. */
void pm_lab_leave(void);

/** One frame of the playable lab. Returns 1 on the frame the player
 *  activates the MRI, which is what ends the section. */
int pm_lab_update(KilnFpsCam *cam, const KilnInput *in, float dt);

/** Draw the lab. Call inside the 3D pass. */
void pm_lab_draw3d(void);

/** Draw the prompt and any open dialogue. Call inside the GUI pass. */
void pm_lab_draw2d(int screen_w, int screen_h);

/** Where the opening cinematic should leave the camera — the eye position
 *  pm_lab_enter expects. Exposed so pm_demo's LAB_CINE shot ends exactly
 *  here rather than somewhere approximately like it. */
fm_vec3_t pm_lab_start_eye(void);
float     pm_lab_start_yaw(void);

/** The hand-authored collision brushes, for pm_debug's spatial overlay to
 *  draw as wireframe boxes. Read-only; `count` receives how many.
 *
 *  Worth exposing because these are the one part of this room that has no
 *  visual representation at all. The geometry is dank_lab.obj and the
 *  collision is six boxes plus blockers typed into this file against that
 *  model's bounding box — the header comment above says so, and pm_lab.c's
 *  own `// TUNE:` note admits the positions were derived from the bbox rather
 *  than from looking at the room. Until they can be drawn, "is the blocker on
 *  the bench it is meant to be on" is a question only a player walking into it
 *  can answer. */
const KilnBrush *pm_lab_brushes(uint16_t *count);

#endif // PM_LAB_H
