// SPDX-License-Identifier: MPL-2.0
//
// pm_world_gen.h — GENERATED by tools/blender/pm_world.py. Do not edit.
//
// Regenerate:  python3 tools/blender/pm_world.py --emit-header \
//                  PetaByte-Madness/src/pm_world_gen.h
//
// Every value is in WORLD units (the generator authors in metres and
// the exporter multiplies by 64). These exist so no camera key, no
// collision brush and no spawn point has to restate a dimension that
// the geometry already defines — which is how this game ended up with
// a shot opening behind a wall and a flyover flying through a ridge.

#ifndef PM_WORLD_GEN_H
#define PM_WORLD_GEN_H

// ── The island ─────────────────────────────────────────────────────
#define PM_ISLAND_RADIUS   19011.2f  // to the wobbled coastline
#define PM_LAND_RADIUS     13825.9f  // where terrain crosses sea level
#define PM_ISLAND_TOP      1644.8f  // highest point, incl. the tower
#define PM_ISLAND_BOTTOM   -192.0f  // the underwater skirt
#define PM_FIELD_RADIUS    5376.0f  // the flat walkable middle
#define PM_FIELD_Y         153.6f  // its height above sea level
#define PM_GATE_RADIUS     7936.0f
#define PM_SHORE_RADIUS    10112.0f

// Where vegetation sits: the band between the plazas and the strand,
// at the height the terrain actually is there.
#define PM_PALM_RADIUS     9024.0f
#define PM_PALM_Y          144.0f

// ── The six dungeon gates ──────────────────────────────────────────
// x, y, z and the compass bearing they face, so a room transition or
// a spawn can be placed at one by index rather than by measurement.
#define PM_GATE_COUNT 6
#define PM_GATE_TABLE { \
    {    7936.0f,   153.6f,       0.0f,    0.0f }, \
    {    3968.0f,   153.6f,    6872.8f,   60.0f }, \
    {   -3968.0f,   153.6f,    6872.8f,  120.0f }, \
    {   -7936.0f,   153.6f,       0.0f,  180.0f }, \
    {   -3968.0f,   153.6f,   -6872.8f,  240.0f }, \
    {    3968.0f,   153.6f,   -6872.8f,  300.0f }, \
}

// ── The island's own procedural lab (unused) ─────────────────────────
// The interior box of THIS generator's procedural build_lab(), which
// is not what ships as PM_MODEL_LAB — that's dank_lab.obj, whose real
// extents live in PetaByte-Madness/src/pm_lab.h (PM_LAB_REAL_*) and are
// what pm_lab.c's collision and pm_demo's/pm_intake's cameras actually
// use. These describe a room nothing currently draws.
//
// PM_WORLD_LAB_*, NOT PM_LAB_*. These used to be spelled PM_LAB_X0..Z1,
// which is exactly what dank_lab_gen.py emits into pm_lab_gen.h — with
// DIFFERENT numbers (-329.6 here against -451.8 there). Five files
// include both headers, so which room PM_LAB_REAL_X0 described came down
// to include order, silently, with only a -Wmacro-redefined warning
// nobody reads in a build that ships -Wno-error. Two generators must not
// publish the same name; the one whose room nothing draws is the one
// that gives it up.
#define PM_WORLD_LAB_X0  -329.6f
#define PM_WORLD_LAB_X1  329.6f
#define PM_WORLD_LAB_Y0  -35.2f
#define PM_WORLD_LAB_Y1  185.6f
#define PM_WORLD_LAB_Z0  -1097.6f
#define PM_WORLD_LAB_Z1  201.6f

#endif // PM_WORLD_GEN_H
