// SPDX-License-Identifier: MPL-2.0
//
// pm_world_gen.h — GENERATED by tools/blender/pm_world.py. Do not edit.
//
// Regenerate:  python3 tools/blender/pm_world.py --emit-header \
//                  PetaByte-Madness/src/pm_world_gen.h
//
// Every value is in WORLD units (the generator authors in metres and
// the exporter multiplies by 64). These exist so no camera key, no
// collision brush and no spawn point has to restate a dimension that
// the geometry already defines — which is how this game ended up with
// a shot opening behind a wall and a flyover flying through a ridge.

#ifndef PM_WORLD_GEN_H
#define PM_WORLD_GEN_H

// ── The island ─────────────────────────────────────────────────────
#define PM_ISLAND_RADIUS   6465.5f  // to the wobbled coastline
#define PM_ISLAND_TOP      2368.0f  // highest point, incl. the tower
#define PM_ISLAND_BOTTOM   -384.0f  // the underwater skirt
#define PM_FIELD_RADIUS    2688.0f  // the flat walkable middle
#define PM_FIELD_Y         448.0f  // its height above sea level
#define PM_GATE_RADIUS     3968.0f
#define PM_SHORE_RADIUS    5056.0f

// Where vegetation sits: the band between the plazas and the strand,
// at the height the terrain actually is there.
#define PM_PALM_RADIUS     4512.0f
#define PM_PALM_Y          422.4f

// ── The six dungeon gates ──────────────────────────────────────────
// x, y, z and the compass bearing they face, so a room transition or
// a spawn can be placed at one by index rather than by measurement.
#define PM_GATE_COUNT 6
#define PM_GATE_TABLE { \
    {    3968.0f,   448.0f,       0.0f,    0.0f }, \
    {    1984.0f,   448.0f,    3436.4f,   60.0f }, \
    {   -1984.0f,   448.0f,    3436.4f,  120.0f }, \
    {   -3968.0f,   448.0f,       0.0f,  180.0f }, \
    {   -1984.0f,   448.0f,   -3436.4f,  240.0f }, \
    {    1984.0f,   448.0f,   -3436.4f,  300.0f }, \
}

// ── The lab ────────────────────────────────────────────────────────
// The interior box, for pm_lab.c's collision brushes and pm_demo's
// interior shot. A camera key outside these is outside the room.
#define PM_LAB_X0  -329.6f
#define PM_LAB_X1  329.6f
#define PM_LAB_Y0  -35.2f
#define PM_LAB_Y1  185.6f
#define PM_LAB_Z0  -1097.6f
#define PM_LAB_Z1  201.6f

#endif // PM_WORLD_GEN_H
