/* SPDX-License-Identifier: MIT
 *
 * GENERATED by tools/schema/level_vocab.py from tools/schema/level_vocab.json.
 * Do not edit. nix/checks/level-vocab.nix regenerates this and diffs it.
 *
 * The classname ORDER here is a wire format: the .FRG v2 tail stores
 * `u8 classname` as an index into it (Forge/src/forge_io.c, and
 * tools/forge/frg.py). Reordering silently reinterprets every level
 * already saved to an SD card. Append, or bump FRG_VERSION on both sides.
 *
 * The EPAIR SLOT COUNT is a wire format too -- the same tail stores
 * `u16 epair[FORGE_VOCAB_EPAIR_COUNT]` positionally. The KEY of a slot
 * depends on the classname (that classname's own numeric epairs first,
 * then the generic count/delay/speed), so the tables below are indexed
 * by classname x slot rather than by slot alone. That
 * is what makes info_key_door's required `key_id` reachable from a
 * controller at all; it used to be three global keys for every class.
 *
 * Tables live inside `static inline` accessors rather than at file scope:
 * a file-scope `static const` table in a header is unused in every TU that
 * does not touch it, and this tree compiles at -Werror under both gcc and
 * emcc.
 */
#ifndef FORGE_VOCAB_GEN_H
#define FORGE_VOCAB_GEN_H

#define FORGE_VOCAB_CLASSNAME_COUNT 8
#define FORGE_VOCAB_EPAIR_COUNT     3
#define FORGE_VOCAB_FACE_COUNT      6

static inline const char *forge_vocab_classname(int i)
{
    static const char *const T[FORGE_VOCAB_CLASSNAME_COUNT] = {
        "info_player_start",
        "info_enemy",
        "info_heavy",
        "info_health",
        "info_ammo",
        "info_armor",
        "info_npc",
        "info_key_door",
    };
    return T[(i % FORGE_VOCAB_CLASSNAME_COUNT + FORGE_VOCAB_CLASSNAME_COUNT) % FORGE_VOCAB_CLASSNAME_COUNT];
}

/* `c` is a classname index, `i` a slot 0..FORGE_VOCAB_EPAIR_COUNT-1.
 * Both are wrapped rather than asserted: this header is included by
 * forge_io.c's LOADER, which reads both out of a file on an SD card.
 */
static inline int forge_vocab_epair_slot(int c, int i)
{
    c = (c % FORGE_VOCAB_CLASSNAME_COUNT + FORGE_VOCAB_CLASSNAME_COUNT) % FORGE_VOCAB_CLASSNAME_COUNT;
    i = (i % FORGE_VOCAB_EPAIR_COUNT + FORGE_VOCAB_EPAIR_COUNT) % FORGE_VOCAB_EPAIR_COUNT;
    return c * FORGE_VOCAB_EPAIR_COUNT + i;
}

static inline const char *forge_vocab_epair_key(int c, int i)
{
    static const char *const T[FORGE_VOCAB_CLASSNAME_COUNT * FORGE_VOCAB_EPAIR_COUNT] = {
        "count", "delay", "speed",  /* info_player_start */
        "count", "delay", "speed",  /* info_enemy */
        "count", "delay", "speed",  /* info_heavy */
        "count", "delay", "speed",  /* info_health */
        "count", "delay", "speed",  /* info_ammo */
        "count", "delay", "speed",  /* info_armor */
        "count", "delay", "speed",  /* info_npc */
        "key_id", "count", "delay",  /* info_key_door */
    };
    return T[forge_vocab_epair_slot(c, i)];
}

/* The value a freshly placed entity starts that slot at. A required
 * epair seeded to 0 would be emitted as an authored 0 or omitted
 * entirely -- both of which are the WARN this table exists to end. */
static inline int forge_vocab_epair_default(int c, int i)
{
    static const short T[FORGE_VOCAB_CLASSNAME_COUNT * FORGE_VOCAB_EPAIR_COUNT] = {
        0, 0, 0,  /* info_player_start */
        0, 0, 0,  /* info_enemy */
        0, 0, 0,  /* info_heavy */
        0, 0, 0,  /* info_health */
        0, 0, 0,  /* info_ammo */
        0, 0, 0,  /* info_armor */
        0, 0, 0,  /* info_npc */
        1, 0, 0,  /* info_key_door */
    };
    return T[forge_vocab_epair_slot(c, i)];
}

/* Required epairs are written to the .map even at 0: the validator
 * warns on ABSENCE, and an author who never touched the field is
 * exactly the case that warning was firing on. */
static inline int forge_vocab_epair_required(int c, int i)
{
    static const unsigned char T[FORGE_VOCAB_CLASSNAME_COUNT * FORGE_VOCAB_EPAIR_COUNT] = {
        0, 0, 0,  /* info_player_start */
        0, 0, 0,  /* info_enemy */
        0, 0, 0,  /* info_heavy */
        0, 0, 0,  /* info_health */
        0, 0, 0,  /* info_ammo */
        0, 0, 0,  /* info_armor */
        0, 0, 0,  /* info_npc */
        1, 0, 0,  /* info_key_door */
    };
    return T[forge_vocab_epair_slot(c, i)];
}

static inline const char *forge_vocab_face_name(int f)
{
    static const char *const T[FORGE_VOCAB_FACE_COUNT] = {
        "-X",
        "+X",
        "-Y",
        "+Y",
        "-Z",
        "+Z",
    };
    return T[f];
}

/* Corner `pt` (0..2) of face `f`, selecting per axis from mn/mx.
 * A loop over the GENERATED selector, not over axes -- which is what
 * Forge/src/forge_io.c's standing warning about re-deriving the winding
 * by hand was protecting. */
static inline void forge_vocab_aabb_corner(int f, int pt,
                                           const int mn[3],
                                           const int mx[3], int out[3])
{
    static const unsigned char SEL[FORGE_VOCAB_FACE_COUNT][3][3] = {
        { { 0, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } },  /* -X */
        { { 1, 0, 0 }, { 1, 0, 1 }, { 1, 1, 0 } },  /* +X */
        { { 0, 0, 0 }, { 0, 0, 1 }, { 1, 0, 0 } },  /* -Y */
        { { 0, 1, 0 }, { 1, 1, 0 }, { 0, 1, 1 } },  /* +Y */
        { { 0, 0, 0 }, { 1, 0, 0 }, { 0, 1, 0 } },  /* -Z */
        { { 0, 0, 1 }, { 0, 1, 1 }, { 1, 0, 1 } },  /* +Z */
    };
    for (int a = 0; a < 3; a++)
        out[a] = SEL[f][pt][a] ? mx[a] : mn[a];
}

#endif /* FORGE_VOCAB_GEN_H */
