# SPDX-License-Identifier: MIT
#
# nix/checks/kiln-font.nix — the host font is libdragon's font.
#
# plat/host/include/kiln_host_font.h is generated by tools/font_extract.py out
# of libdragon's own rdpq_font_builtin.c, so that host text lays out exactly as
# console text does. A generated header checked into the tree is only as good
# as its regeneration discipline (see nix/checks/pm-gen-headers.nix, which
# exists for the same reason), so this regenerates it and diffs.
#
# It then asserts the invariants a diff CANNOT catch — that the font is still
# monospaced, that every printable ASCII codepoint has a glyph, and that each
# glyph has both fill and outline pixels, which is what proves the 2bpp layer
# decode picked the right half. See the check's C for why that last one matters:
# the wrong half yields glyphs that are recognisable but built out of their
# slot-mate's pixels.
{ pkgs, libdragonSrc, platHost, fontTool }:

pkgs.runCommand "check-kiln-font"
{
  nativeBuildInputs = [ pkgs.gcc pkgs.python3 ];
  meta.description = "the extracted builtin font is current and still monospaced";
}
  ''
    set -euo pipefail

    python3 ${fontTool} \
      --builtin ${libdragonSrc}/src/rdpq/rdpq_font_builtin.c \
      --emit-header regenerated.h

    if ! diff -u ${platHost}/include/kiln_host_font.h regenerated.h; then
      echo ""
      echo "FAILED: plat/host/include/kiln_host_font.h is stale."
      echo "Regenerate it:"
      echo "  python3 tools/font_extract.py \\"
      echo "    --builtin \$(nix eval --raw .#libdragon.src)/src/rdpq/rdpq_font_builtin.c \\"
      echo "    --emit-header plat/host/include/kiln_host_font.h"
      echo ""
      echo "If libdragon changed the font, look at the diff before committing it:"
      echo "  python3 tools/font_extract.py --builtin ... --verify"
      exit 1
    fi
    echo "generated font header is current"

    gcc -O1 -std=gnu11 -Wall -Wextra -Werror \
        -I${platHost}/include -o font_check ${./kiln-font-check.c}
    ./font_check

    mkdir -p $out && touch $out/ok
  ''
