# SPDX-License-Identifier: MPL-2.0
#
# nix/checks/pm-cine.nix — the cinematic camera validator, on the host.
#
# Same idea as nix/checks/kiln-logic.nix, pointed at the game rather than the
# engine: PetaByte-Madness/src/pm_cine_lint.c and pm_camkey.h are pure
# arithmetic over caller-owned structs, touching nothing of libdragon or Tiny3D
# beyond the `fm_vec3_t` TYPE, so the real sources compile natively against
# nix/checks/stub/ and can be asserted on in seconds.
#
# ── Why the validator is worth gating ──────────────────────────────────
# Every camera bug PetaByte Madness has had was a static property of a keyframe
# table sitting next to a dimension its generators already publish, and every
# one was found by building a ROM and looking at it. pm_demo.h's own comments
# list them: an eye 69 units behind the lab's back wall, an eye at 1,400 units
# INSIDE the island's footprint rendering black (which read as "the ROM is
# broken" and sent the hunt somewhere else entirely), an orbit chord dipping
# through the ridges, and a frustum default that "cost six shots their
# geometry".
#
# ── What this checks, and what it deliberately does not ────────────────
# It checks THE DETECTOR, in both directions. The real key tables cannot leave
# the ROM build — pm_demo.c needs libdragon and Tiny3D, and FLYOVER_KEYS is not
# even a compile-time constant (flyover_build_keys fills it during `setup`) — so
# the `PM_CINE_LINT=1` ROM inspects the real data where it lives, and this
# checks that the thing doing the inspecting works.
#
# That split matters: a report generated by an unverified detector is worse than
# no report, because it reads as authoritative. Here every hard-failure flag has
# a table that trips exactly it and nothing else, and the clean table has to
# come back with zero.
#
# ── The registry guard ─────────────────────────────────────────────────
# The second half has nothing to do with C. pm_cine.h's PM_SHOT_LIST is an
# X-macro naming every cinematic in the game, and it is what the lint ROM walks
# and what the transport can jump to. A shot missing from it is invisible to
# both — silently, and in exactly the way a hand-kept parallel table always
# fails. This codebase has had that drift twice (PM_SCREEN_LIST and
# PM_MODEL_LIST exist because of it, and one drift was a NULL format string at
# boot on every debug build), so the list is checked against the definitions
# rather than trusted.
{ pkgs, pmSrc, engineSrc, hostMath, platHost }:

pkgs.runCommand "check-pm-cine"
{
  nativeBuildInputs = [ pkgs.gcc ];
  meta.description =
    "PetaByte Madness' cinematic camera validator, asserted on the host";
}
  ''
    set -euo pipefail

    # The host headers must come FIRST on the include path so <t3d/t3dmath.h>
    # resolves to plat/host/include and <fgeom.h> to nix/host-math.nix's
    # natively-built copy of libdragon's REAL fast math (fm_vec3_t used to be
    # a hand-copy under ./stub; it is not any more, so the validator now
    # measures the curve with the console's own arithmetic). The game sources
    # are then compiled
    # completely unmodified, which is the property that makes this a test of the
    # game rather than of a fork of it.
    #
    # -Werror is a free second opinion for the same reason kiln-logic.nix gives:
    # PetaByte-Madness/Makefile builds with -Wno-error to survive third-party
    # header noise, so nothing else in this project ever compiles this file
    # strictly.
    # Both the curve and the validator now live in the engine (kiln_camkey.h,
    # kiln_camlint.{h,c}); pm_camkey.h and pm_cine_lint.h are shims so the game's
    # own sources and pm-cine-check.c compile untouched. `engine/src` (not
    # src/kiln) is on the include path so the <kiln/...> spelling the ROM build
    # uses resolves here too — one spelling, both consumers.
    #
    # This still compiles the REAL validator, which is the property that matters:
    # the check would be worthless against a copy.
    gcc -O1 -std=gnu11 -Wall -Wextra -Werror \
        -I${./stub} -I${platHost}/include -I${hostMath}/include \
        -I${pmSrc}/src -I${engineSrc}/src \
        -o pmcine_check \
        ${./pm-cine-check.c} \
        ${engineSrc}/src/kiln/kiln_camlint.c \
        -lm

    ./pmcine_check

    # ── The registry must name every shot ──────────────────────────────
    # Definitions look like `const PMDemoShot pm_intake_shot = {` or
    # `const PMDemoShot pm_demo_reel[] = {`. The reel is an array, so it is
    # matched by name and its ENTRIES are what PM_SHOT_LIST carries; everything
    # else must appear by its own symbol.
    echo
    echo "registry: every PMDemoShot must be in PM_SHOT_LIST"

    list=$(sed -n '/define PM_SHOT_LIST/,/^$/p' ${pmSrc}/src/pm_cine.h)
    if [ -z "$list" ]; then
      echo "  FAIL  PM_SHOT_LIST not found in pm_cine.h"
      exit 1
    fi

    missing=0
    for sym in $(grep -rhoE '^const PMDemoShot (pm_[a-z_]+)' ${pmSrc}/src \
                 | awk '{print $3}' | sort -u); do
      if printf '%s' "$list" | grep -q "$sym"; then
        echo "  ok    $sym"
      else
        echo "  FAIL  $sym is defined but absent from PM_SHOT_LIST"
        missing=1
      fi
    done
    [ "$missing" -eq 0 ]

    # And the reel's entries, which are addressed by index rather than by name.
    reel=$(grep -c '{ \.name = ' ${pmSrc}/src/pm_demo.c || true)
    listed=$(printf '%s' "$list" | grep -c 'pm_demo_reel\[' || true)
    echo "  reel: $reel shots defined, $listed listed"
    if [ "$reel" -ne "$listed" ]; then
      echo "  FAIL  pm_demo_reel has $reel entries but PM_SHOT_LIST names $listed"
      exit 1
    fi

    echo
    echo "pm_cine check PASSED"
    mkdir -p $out && touch $out/ok
  ''
