#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# index.py — write dsp/instruments/INDEX.md from catalogue.json and each
# instrument's own header line, so the table can never disagree with the code.
#
# usage: index.py <catalogue.json> <dsp/instruments dir>     (prints to stdout)
#
# nix/instruments.nix regenerates it and diffs against the committed copy, the
# same shape as nix/checks/level-vocab.nix. Edit the instrument's first comment
# line or the catalogue; never INDEX.md.
import json
import os
import re
import sys

FAMILY_TITLES = [
    ("strings", "Plucked strings"),
    ("keys", "Keys"),
    ("mallets", "Mallets, bells and tuned percussion"),
    ("synth", "Synthesisers"),
    ("bass", "Bass"),
    ("retro", "Retro: 8- and 16-bit"),
    ("drums", "Drums"),
    ("sfx", "Sound effects"),
    ("ambient", "Ambient beds"),
]


def blurb(dsp_dir, name):
    lines = open(os.path.join(dsp_dir, name + ".dsp")).read().split("\n")
    i = next(k for k, l in enumerate(lines) if l.startswith("// %s \u2014 " % name))
    text = lines[i].split("\u2014", 1)[1].strip()
    # The first sentence may wrap over several comment lines, up to the blank one.
    j = i + 1
    while not re.search(r"[a-z)]\.(\s|$)", text) and j < len(lines) and lines[j].startswith("// "):
        text += " " + lines[j][3:].strip()
        j += 1
    text = re.split(r"(?<=[a-z)])\.(?:\s|$)", text)[0].rstrip(".")
    return text[0].upper() + text[1:] + "."


def main():
    cat = json.load(open(sys.argv[1]))
    insts = cat["instruments"]
    d = sys.argv[2]
    out = []
    w = out.append
    w("<!-- SPDX-License-Identifier: GPL-3.0-only -->")
    w("<!-- GENERATED by tools/instruments/index.py from catalogue.json and each .dsp header.")
    w("     Do not edit: nix/instruments.nix diffs this file against a fresh run. -->")
    w("")
    w("# Instrument index")
    w("")
    w("%d instruments at %d Hz. **Live** voices are linked into a ROM and synthesised on the"
      % (len(insts), cat["sampleRate"]))
    w("VR4300 (they passed `nix/faust.nix`'s no-libm, no-double and cycle-budget gates); every")
    w("instrument can be **baked** to a VADPCM `.wav64` by `mkBakedInstrument`. `ref` is the")
    w("pitch the baked asset is rendered at; `out` is the mixer channels a baked asset costs.")
    w("")
    for fam, title in FAMILY_TITLES:
        rows = sorted(n for n, i in insts.items() if i["family"] == fam)
        if not rows:
            continue
        w("## %s" % title)
        w("")
        w("| instrument | ref | live | out | what it is |")
        w("|---|---|---|---|---|")
        for n in rows:
            i = insts[n]
            ref = ("%g Hz" % i["freq"]) if i.get("freqParam", True) else "—"
            live = "%d" % i["budget"] if i.get("live") else "—"
            ch = 2 if i.get("stereo") else 1
            w("| `%s` | %s | %s | %d | %s |" % (n, ref, live, ch, blurb(d, n)))
        w("")
    w("`live` is the declared cycle budget per sample at %d Hz (the static weighted estimate of" % cat["sampleRate"])
    w("`nix/faust.nix`; profile with `TICKS` on hardware for the real number).")
    print("\n".join(out))


main()
