// SPDX-License-Identifier: MIT
// GENERATED by tools/poser/gen_lag.py from tools/blender/goblin.py's LAG — do not edit.
// nix/checks/poser-lag.nix regenerates it and fails on any difference.
//
// Frames each floppy bone trails the body by. Left and right differ on purpose.
export const LAG = {
  "ear_l": 3,
  "ear_r": 4,
  "nose": 2,
  "jaw": 2,
  "hand_l": 2,
  "hand_r": 3,
  "forearm_l": 1,
  "forearm_r": 1,
};
