# SPDX-License-Identifier: MPL-2.0
"""pm_props.py — PetaByte Madness' OBJ-sourced models.

    blender --background --factory-startup -noaudio --python pm_props.py \
        -- --model island --out build/island.gltf

One script with a MODELS table, the same shape goblin.py and models.py use,
because every one of these is the same three steps: read an OBJ, colour it,
decimate if it is too heavy for the console. The parsing lives in objkit.py
(no `bpy`, testable with a bare python3); this file is only the Blender half.

── Scale: 1 Blender unit = 1 metre, always ────────────────────────────────
Every model here is scaled to its real size in metres, taken from the drop's
own specs — docs/LOACH_spec.md gives the sub as 2.86 m long, the guards are
people, the centaur came out of its generator in centimetres. Normalising on
metres means the flake's `baseScale` is a single meaningful dial (world units
per metre) instead of a per-model fudge factor, and it means a wrong number is
visible as "that submarine is the size of a car" rather than as a silent
mismatch between two models that were never in the same room until now.

── The submarine is deliberately oversized ────────────────────────────────
LOACH_spec.md describes a one-person boat: 2.86 m, "crew 1, seated, knees up".
The centaur is a 2.5 m wide-and-low quadruped and does not fit in that by any
reading. The intro needs him to climb out of it, so the sub is scaled up until
he does. Chosen over modelling a variant hull: it costs one number, and the
spec's proportions — the tank hull, the dished ends, the two mismatched
battery pods — all survive being bigger.
"""

import math
import os
import sys

import bpy

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import m64lib as m  # noqa: E402
import objkit  # noqa: E402

# Paths below are relative to the assets directory, which arrives as
# `--assets <dir>`. It is a DIRECTORY rather than one file per model because
# loach.obj needs its loach.mtl sibling to resolve, and a Nix store path for a
# single file has no siblings. Defaults to the in-repo location so the script
# still runs by hand from the repo root.
DEFAULT_ASSETS = "PetaByte-Madness/assets"


def _island_colors(verts, faces, groups):
    """Colour the island by height and slope.

    island_n64.obj carries no vertex colours — its generator's palette did not
    survive the OBJ export (3 floats per `v`, not 6), and regenerating needs
    numpy + scipy + matplotlib, which is a heavy dependency to add to a
    hermetic build for data we can derive from the geometry we already have.

    Height and slope give the banded look an N64 island wants anyway: the
    palette is deliberately few, flat and separated in VALUE, so it still
    reads once the veil collapses hue (docs/VEIL_DESIGN.md §4).
    """
    lo = min(v[2] for v in verts)
    hi = max(v[2] for v in verts)
    span = max(hi - lo, 1e-6)

    WET_SAND = m.srgb(132, 116, 88)
    SAND     = m.srgb(196, 178, 138)
    SCRUB    = m.srgb(86, 104, 62)
    GRASS    = m.srgb(64, 84, 48)
    ROCK     = m.srgb(112, 108, 100)
    HIGH     = m.srgb(74, 72, 68)

    colors = [SAND] * len(verts)
    for face, group in zip(faces, groups):
        a, b, c = (verts[i] for i in face)
        u = [b[i] - a[i] for i in range(3)]
        w = [c[i] - a[i] for i in range(3)]
        n = (u[1] * w[2] - u[2] * w[1],
             u[2] * w[0] - u[0] * w[2],
             u[0] * w[1] - u[1] * w[0])
        length = math.sqrt(sum(v * v for v in n)) or 1.0
        # Flat ground has a normal pointing straight up (+Z after the axis
        # change); a cliff face's is near horizontal.
        flatness = abs(n[2] / length)

        for i in face:
            h = (verts[i][2] - lo) / span
            if group == "cliffs" or flatness < 0.55:
                colors[i] = ROCK if h < 0.55 else HIGH
            elif h < 0.015:
                colors[i] = WET_SAND
            elif h < 0.07:
                colors[i] = SAND
            elif h < 0.45:
                colors[i] = SCRUB
            else:
                colors[i] = GRASS
    return colors


MODELS = {
    # NOTE: the island is NOT here any more. It is generated by
    # tools/blender/pm_world.py, which builds it as a walkable hub with flat
    # ground the collision can bind to and named gates the game can find.
    # The OBJ entry that used to sit here carried "decimate": 0.15 — the
    # only decimation in this table — and that 15% is what turned a rounded
    # island into a flat-topped mesa. assets/obj/island_n64.obj is kept as
    # the provenance record and as the look reference.
    # The work submarine. Vertex colours come baked into the OBJ — vertical AO
    # and a per-facet rust bias — and LOACH_spec.md is explicit that it renders
    # with lighting OFF, so those colours ARE the shading.
    "loach": {
        "obj": "obj/loach.obj",
        # 2.72 units long as authored; x3.5 puts it near 9.5 m, big enough for
        # the centaur to be inside it and climb out. See the file comment.
        "scale": 3.5,
        "decimate": None,
        "color": "vertex",
        "split": "material",
    },
    # The lab. dank_lab_gen.py emits three zones — room, hall and dock — but
    # only into its F3DEX2 header; the OBJ carries materials, not zones. The
    # material split is what survives, which is enough: `caustic` and `screen`
    # are the emissive surfaces (the moon pool's light, the monitors) and will
    # want their own f3d preset once the veil's TLUT bake exists.
    #
    # The dock IS the moon pool — where the LOACH sits, and where the intro
    # hands Horner over to it. ~10 m x 5 m with 2.5 m ceilings.
    "dank_lab": {
        "obj": "obj/dank_lab.obj",
        "scale": 0.01,  # authored in centimetres
        "decimate": None,
        "color": "vertex",
        "split": "material",
    },
    # Horner himself is no longer built here — see tools/blender/horner.py,
    # which rebuilds him as a skinned, six-clip rig off the same
    # patrick_horner_gen.py geometry (via ph_rig.py's joint binding) instead
    # of importing patrick_horner.obj as a rigid prop. "horner_upright"
    # below is kept only as provenance for that generator's `--upright`
    # variant; nothing currently builds it.
    "horner_upright": {
        "obj": "obj/patrick_horner_upright.obj",
        "scale": 0.01,
        "decimate": None,
        "color": "vertex",
        "split": "material",
    },
    "drone": {
        "obj": "obj/n64_drone_enemy.obj",
        "scale": 1.2,
        "decimate": None,
        "color": "mtl",
        "split": "material",
    },
    # Island vegetation. Ships as ONE mesh of 862 triangles containing every
    # plant at once, which is the wrong granularity: a beach wants palms
    # placed individually, and paying 862 triangles per placement to get one
    # of them is not a trade worth making.
    #
    # So it is split into connected components and each real plant becomes its
    # own named object in the .t3dm. The game then places them with
    # t3d_model_get_object + a matrix each — one load, many placements, and
    # only the plants actually wanted get drawn.
    #
    # The split finds 295 components, but only ~15 are plants (42 tris for a
    # full palm down to 12 for a sprout); the remaining ~280 are 1-2 triangle
    # grass blades. Those are merged into a single `scatter` object rather
    # than dropped — at N64 resolution they are invisible individually and not
    # worth 280 draw calls, but they are the author's content and one extra
    # object costs nothing to carry.
    "palms": {
        "obj": "n64_florida_keys_palms.gltf",
        "kind": "gltf",
        "scale": 1.0,  # already authored in metres — a 6 m palm
        "decimate": None,
        "color": "vertex",
        "split": "loose",
        "loose_min_tris": 8,
    },
}

# The four guard mobs, from one entry each — same geometry pipeline, different
# file. Two of them stand on the beach when the sub comes in.
for _guard in ("cousin", "uncle", "whistler", "auntie"):
    MODELS[f"guard_{_guard}"] = {
        "obj": f"obj/mob_{_guard}.obj",
        # ~0.93 units tall as authored -> a 1.8 m person.
        "scale": 1.94,
        "decimate": None,
        "color": "mtl",
        "split": "material",
    }


def _source(spec):
    return os.path.join(m.arg("--assets", DEFAULT_ASSETS), spec["obj"])


def _load(spec):
    path = _source(spec)
    if not os.path.exists(path):
        raise SystemExit(
            "pm_props: no such source '%s'.\n"
            "  Pass --assets <dir> pointing at PetaByte-Madness/assets, or run\n"
            "  from the repo root where the default path resolves." % path)
    if spec.get("kind") == "gltf":
        return objkit.load_gltf(path)
    return objkit.load_obj(path)


def _loose_groups(obj, min_tris):
    """Connected components -> named groups, tiny fragments merged.

    Names carry intent, not just an index: the tall components are palms and
    the short ones shrubs, so the game asks for "palm_00" rather than knowing
    that component 3 happens to be a tree.
    """
    parts = objkit.loose_parts(obj["faces"])
    groups = {}
    scatter = []
    palms = shrubs = 0
    for faces in parts:
        if len(faces) < min_tris:
            scatter.extend(faces)
            continue
        height = max(obj["verts"][i][1] for f in faces for i in f) - \
            min(obj["verts"][i][1] for f in faces for i in f)
        if height >= 2.0:
            groups["palm_%02d" % palms] = faces
            palms += 1
        else:
            groups["shrub_%02d" % shrubs] = faces
            shrubs += 1
    if scatter:
        groups["scatter"] = scatter
    return groups


def build(spec):
    obj = _load(spec)

    # Must run before anything reads verts/colors: it appends to both.
    cloned = objkit.split_double_sided(obj)
    if cloned:
        print("  cloned %d double-sided face(s) so Blender keeps both windings"
              % cloned)

    scale = spec["scale"]
    verts = [tuple(c * scale for c in objkit.yup_to_zup(v))
             for v in obj["verts"]]

    if spec["color"] == "island":
        colors = _island_colors(verts, obj["faces"], obj["face_group"])
    elif spec["color"] == "vertex":
        if not obj["colors"]:
            raise SystemExit(f"pm_props: {spec['obj']} has no vertex colours")
        colors = [m.srgb(*(int(round(v * 255)) for v in c))
                  for c in obj["colors"]]
    else:  # "mtl" — bake the material's diffuse into the vertices
        mtl = objkit.load_mtl(os.path.splitext(_source(spec))[0] + ".mtl")
        colors = [m.srgb(255, 255, 255)] * len(verts)
        for face, material in zip(obj["faces"], obj["face_material"]):
            kd = mtl.get(material)
            if kd is None:
                continue
            rgb = m.srgb(*(int(round(v * 255)) for v in kd))
            for i in face:
                colors[i] = rgb

    if spec["split"] == "loose":
        groups = _loose_groups(obj, spec.get("loose_min_tris", 8))
    else:
        groups = objkit.group_faces(obj, by=spec["split"])
    total = 0
    for name, faces in sorted(groups.items()):
        used = sorted({i for f in faces for i in f})
        remap = {old: new for new, old in enumerate(used)}
        m.make_material(name)
        mesh = m.make_mesh(
            name,
            [verts[i] for i in used],
            [tuple(remap[i] for i in f) for f in faces],
            name,
            colors=[colors[i] for i in used],
            smooth=False,
        )
        if spec["decimate"]:
            mod = mesh.modifiers.new(name="Decimate", type='DECIMATE')
            mod.ratio = spec["decimate"]
            # Applied here rather than left to export_apply, so the triangle
            # count this script PRINTS is the count that ships. A budget you
            # only learn after the fact is not a budget.
            bpy.context.view_layer.objects.active = mesh
            bpy.ops.object.modifier_apply(modifier=mod.name)
        total += len(mesh.data.polygons)

    return total


def main():
    name = m.arg("--model")
    if name not in MODELS:
        raise SystemExit("pm_props.py: no model '%s' (have: %s)"
                         % (name, ", ".join(sorted(MODELS))))
    spec = MODELS[name]

    m.reset_scene()
    tris = build(spec)

    src = _load(spec)
    print("── %s: %d tris in, %d out%s ──"
          % (name, len(src["faces"]), tris,
             "" if not spec["decimate"]
             else " (decimate %.2f)" % spec["decimate"]))

    m.export_gltf(m.arg("--out"))


main()
