#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_lag.py — tools/poser/src/lag.gen.js from goblin.py's LAG table.

The poser previews follow-through by sampling floppy bones a few frames in the
past, exactly as goblin.py bakes it. The table used to be copied into pose.js
by hand, and a copy nothing compares is a copy that drifts: change an ear's lag
in the model and the editor would keep showing the old follow-through while
claiming to preview the export. goblin.py imports bpy, so the table is read
with ast rather than by importing the script.

    python3 tools/poser/gen_lag.py            rewrite src/lag.gen.js
    python3 tools/poser/gen_lag.py --check    exit 1 if it is stale
    [--source goblin.py] [--out lag.gen.js]   (nix/checks/poser-lag.nix)
"""

import ast
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "blender" / "goblin.py"
OUT = HERE / "src" / "lag.gen.js"


def read_lag(path):
    tree = ast.parse(Path(path).read_text())
    found = [n for n in tree.body if isinstance(n, ast.Assign)
             and any(isinstance(t, ast.Name) and t.id == "LAG" for t in n.targets)]
    if len(found) != 1:
        raise SystemExit(f"gen_lag: expected one top-level `LAG = {{...}}` in {path}, found {len(found)}")
    lag = ast.literal_eval(found[0].value)
    if not isinstance(lag, dict) or not all(isinstance(k, str) and type(v) is int and v >= 0 for k, v in lag.items()):
        raise SystemExit("gen_lag: LAG must map bone names to whole, non-negative frame counts")
    return lag


def render(lag):
    rows = "".join(f"  {json.dumps(bone)}: {frames},\n" for bone, frames in lag.items())
    return ("// SPDX-License-Identifier: MIT\n"
            "// GENERATED by tools/poser/gen_lag.py from tools/blender/goblin.py's LAG — do not edit.\n"
            "// nix/checks/poser-lag.nix regenerates it and fails on any difference.\n"
            "//\n"
            "// Frames each floppy bone trails the body by. Left and right differ on purpose.\n"
            f"export const LAG = {{\n{rows}}};\n")


def main(argv):
    def opt(name, default):
        return Path(argv[argv.index(name) + 1]) if name in argv else default

    out = opt("--out", OUT)
    text = render(read_lag(opt("--source", SOURCE)))
    if "--check" in argv:
        if not out.is_file() or out.read_text() != text:
            print(f"gen_lag: {out} is stale against goblin.py's LAG — run python3 tools/poser/gen_lag.py")
            return 1
        print("gen_lag: lag.gen.js matches goblin.py's LAG")
        return 0
    out.write_text(text)
    print(f"gen_lag: wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
