#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# tools/n64-input.py — a virtual N64 controller for automated capture runs.
#
#   n64-input.py probe --bml OUT.bml [--json OUT.json]
#   n64-input.py run   SCRIPT [--json PAD.json] [--geom "X,Y WxH"] [--outdir DIR]
#
# ── Why this exists ────────────────────────────────────────────────────
# A fresh ares settings.bml has EVERY input binding empty ("Start: ;;") and
# there is no ~/.config/ares/settings.bml to inherit from, so a capture run
# could reach the boot screen and nothing further: no button press could
# ever be delivered, and every screen behind "press start" was unreachable
# under automation. That is not a rendering problem but it looks exactly
# like one from the outside, which is how it went unnoticed.
#
# ── Why uinput rather than a synthetic keypress ────────────────────────
# wtype and friends can only send keystrokes, and this game's first-person
# sections need an ANALOG stick — full deflection in eight directions is
# not the same input and would not exercise the same code. /dev/uinput is
# writable by the user here (an ACL grants it, see `getfacl /dev/uinput`),
# so a real kernel-level gamepad is available without root.
#
# ── Why the bindings are probed rather than hardcoded ──────────────────
# ares binds to `<device-identifier>/<groupID>/<inputID>[/Lo|/Hi]` where
# the identifier is an SDL GUID (see desktop-ui/input/input.cpp's
# `inputAssignment` and ruby/input/joypad/sdl.cpp's `enumerate`). Both the
# GUID and the axis/button INDEX ordering are SDL's business, not ours, so
# this actuates each control one at a time, reads back through the same
# libSDL3 ares itself links, and writes the assignment strings from what
# SDL actually reported. A committed index table would be a guess that
# fails silently — as an unbound button does — the first time SDL changes
# its evdev enumeration order.
#
# The GUID is a pure function of the device's bus/vendor/product/version
# and name, all of which are fixed below, so it is stable between the
# probe run (which writes the bml before ares starts) and the run mode
# (which recreates the pad afterwards). `run` re-probes and asserts the
# GUID still matches rather than trusting that.

import argparse
import ctypes
import json
import os
import re
import shlex
import subprocess
import sys
import time

try:
    from evdev import UInput, AbsInfo, ecodes as e
except ImportError:
    sys.exit("n64-input: python evdev not available (it is in the nix devShell; "
             "run this through ./dev, or `nix develop`)")

# ── The device ─────────────────────────────────────────────────────────
# Fixed identity: the SDL GUID is derived from these, and the ares bindings
# are derived from the GUID. Changing any of them invalidates a settings
# file generated by an older revision — which `run` detects and reports.
PAD_NAME    = "Kiln Drive Pad"
PAD_VENDOR  = 0x1D79
PAD_PRODUCT = 0x6401
PAD_VERSION = 0x0001

AXIS_MAX = 32767

# Logical N64 control -> how it is presented on the virtual pad.
#
# The C buttons ride the right stick and the D-pad rides a hat, which is
# the ordinary modern layout for an N64 pad; ares reads both through axis
# Lo/Hi qualifiers, so nothing here needs a special case at the other end.
BUTTONS = {
    "a":     e.BTN_SOUTH,
    "b":     e.BTN_EAST,
    "z":     e.BTN_TL2,
    "l":     e.BTN_TL,
    "r":     e.BTN_TR,
    "start": e.BTN_START,
}
AXIS_CONTROLS = {
    "cup":    (e.ABS_RY, -AXIS_MAX),
    "cdown":  (e.ABS_RY, +AXIS_MAX),
    "cleft":  (e.ABS_RX, -AXIS_MAX),
    "cright": (e.ABS_RX, +AXIS_MAX),
    "xlo":    (e.ABS_X,  -AXIS_MAX),
    "xhi":    (e.ABS_X,  +AXIS_MAX),
    "ylo":    (e.ABS_Y,  -AXIS_MAX),
    "yhi":    (e.ABS_Y,  +AXIS_MAX),
}
HAT_CONTROLS = {
    "dup":    (e.ABS_HAT0Y, -1),
    "ddown":  (e.ABS_HAT0Y, +1),
    "dleft":  (e.ABS_HAT0X, -1),
    "dright": (e.ABS_HAT0X, +1),
}

# Every control the probe must resolve. A control that cannot be resolved
# is a hard failure: a partially-bound pad is the failure mode this whole
# file exists to eliminate.
CONTROLS = list(BUTTONS) + list(AXIS_CONTROLS) + list(HAT_CONTROLS)

# ares' settings.bml key for each control. L-Up/L-Down/L-Left/L-Right are
# deliberately NOT in here even though they exist in the file:
# desktop-ui/input/input.hpp's `InputDevice::analog(name, lo, hi)` hands
# the pair the SAME mapping objects the individual nodes already hold, and
# settings.cpp loads pairs AFTER inputs — so an empty `X-Axis/Lo` would
# overwrite whatever `L-Left` had just loaded. Binding the pair is binding
# both, and binding both is binding one of them to nothing.
BML_KEYS = {
    "dup":    ("Up",),
    "ddown":  ("Down",),
    "dleft":  ("Left",),
    "dright": ("Right",),
    "b":      ("B",),
    "a":      ("A",),
    "cup":    ("C-Up",),
    "cdown":  ("C-Down",),
    "cleft":  ("C-Left",),
    "cright": ("C-Right",),
    "l":      ("L",),
    "r":      ("R",),
    "z":      ("Z",),
    "start":  ("Start",),
    "xlo":    ("X-Axis", "Lo"),
    "xhi":    ("X-Axis", "Hi"),
    "ylo":    ("Y-Axis", "Lo"),
    "yhi":    ("Y-Axis", "Hi"),
}

# nall/hid.hpp: enum GroupID : u32 { Axis, Hat, Trigger, Button };
GROUP_AXIS, GROUP_HAT, GROUP_BUTTON = 0, 1, 3


def make_pad():
    caps = {
        e.EV_KEY: sorted(set(BUTTONS.values())),
        e.EV_ABS: [
            (e.ABS_X,  AbsInfo(0, -AXIS_MAX, AXIS_MAX, 0, 16, 0)),
            (e.ABS_Y,  AbsInfo(0, -AXIS_MAX, AXIS_MAX, 0, 16, 0)),
            (e.ABS_RX, AbsInfo(0, -AXIS_MAX, AXIS_MAX, 0, 16, 0)),
            (e.ABS_RY, AbsInfo(0, -AXIS_MAX, AXIS_MAX, 0, 16, 0)),
            (e.ABS_HAT0X, AbsInfo(0, -1, 1, 0, 0, 0)),
            (e.ABS_HAT0Y, AbsInfo(0, -1, 1, 0, 0, 0)),
        ],
    }
    try:
        return UInput(caps, name=PAD_NAME, vendor=PAD_VENDOR,
                      product=PAD_PRODUCT, version=PAD_VERSION,
                      bustype=e.BUS_USB)
    except PermissionError:
        sys.exit("n64-input: cannot open /dev/uinput. It is normally granted to the "
                 "seat's user by an ACL — check `getfacl /dev/uinput`.")


class Pad:
    """The virtual pad, with the state-tracking a script needs."""

    def __init__(self):
        self.ui = make_pad()
        self.held = set()
        self.center()

    def close(self):
        self.release_all()
        self.ui.close()

    def button(self, name, down):
        self.ui.write(e.EV_KEY, BUTTONS[name], 1 if down else 0)
        self.ui.syn()
        self.held.discard(name) if not down else self.held.add(name)

    def axis(self, code, value):
        self.ui.write(e.EV_ABS, code, int(value))
        self.ui.syn()

    def set_control(self, name, down):
        if name in BUTTONS:
            self.button(name, down)
        elif name in AXIS_CONTROLS:
            code, val = AXIS_CONTROLS[name]
            self.axis(code, val if down else 0)
            self.held.add(name) if down else self.held.discard(name)
        elif name in HAT_CONTROLS:
            code, val = HAT_CONTROLS[name]
            self.axis(code, val if down else 0)
            self.held.add(name) if down else self.held.discard(name)
        else:
            raise KeyError(name)

    def stick(self, x, y):
        # y is inverted on the wire: a script says +1 for "forward/up",
        # and evdev's convention for a stick pushed up is negative.
        self.axis(e.ABS_X, max(-1.0, min(1.0, x)) * AXIS_MAX)
        self.axis(e.ABS_Y, -max(-1.0, min(1.0, y)) * AXIS_MAX)

    def center(self):
        for code in (e.ABS_X, e.ABS_Y, e.ABS_RX, e.ABS_RY,
                     e.ABS_HAT0X, e.ABS_HAT0Y):
            self.ui.write(e.EV_ABS, code, 0)
        self.ui.syn()

    def release_all(self):
        for name in list(self.held):
            try:
                self.set_control(name, False)
            except KeyError:
                pass
        self.held.clear()
        self.center()


# ── SDL, through the same library ares links ───────────────────────────
SDL_INIT_JOYSTICK = 0x00000200


class SDL_GUID(ctypes.Structure):
    _fields_ = [("data", ctypes.c_ubyte * 16)]


def sdl_from_ares():
    """Resolve the libSDL3 $ARES actually links.

    Several SDL3 builds can coexist in the Nix store, and a GUID or an
    index probed against the wrong one describes a device ares is not
    looking at. nixpkgs' ares is a tiny exec wrapper, so the DT_NEEDED
    entries live on `.ares-wrapped` beside it, not on `ares` itself."""
    ares = os.environ.get("ARES")
    if not ares or not os.path.exists(ares):
        return None
    d, b = os.path.split(os.path.abspath(ares))
    for cand in (os.path.join(d, f".{b}-wrapped"), ares):
        if not os.path.exists(cand):
            continue
        try:
            out = subprocess.run(["ldd", cand], capture_output=True, text=True).stdout
        except OSError:
            return None
        for line in out.splitlines():
            if "libSDL3" in line and "=>" in line:
                return line.split("=>")[1].strip().split(" ")[0]
    return None


def load_sdl():
    """Load libSDL3. Prefer the exact library ares resolved: an index or
    GUID probed against a different SDL build is a probe of the wrong
    thing."""
    for cand in (os.environ.get("KILN_SDL3"), sdl_from_ares(),
                 "libSDL3.so.0", "libSDL3.so"):
        if not cand:
            continue
        try:
            return ctypes.CDLL(cand)
        except OSError:
            continue
    sys.exit("n64-input: libSDL3 not found. Set KILN_SDL3 to the library ares links "
             "(`ldd $(command -v ares) | grep SDL3`).")


class Sdl:
    def __init__(self):
        # SDL ignores joystick activity for an unfocused application unless
        # this is set. A drive run moves and screenshots windows, so focus
        # is exactly what cannot be assumed.
        os.environ.setdefault("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1")
        self.lib = load_sdl()
        L = self.lib
        L.SDL_Init.argtypes = [ctypes.c_uint32]
        L.SDL_Init.restype = ctypes.c_bool
        L.SDL_GetJoysticks.argtypes = [ctypes.POINTER(ctypes.c_int)]
        L.SDL_GetJoysticks.restype = ctypes.POINTER(ctypes.c_uint32)
        L.SDL_GetJoystickNameForID.argtypes = [ctypes.c_uint32]
        L.SDL_GetJoystickNameForID.restype = ctypes.c_char_p
        L.SDL_GetJoystickGUIDForID.argtypes = [ctypes.c_uint32]
        L.SDL_GetJoystickGUIDForID.restype = SDL_GUID
        L.SDL_GUIDToString.argtypes = [SDL_GUID, ctypes.c_char_p, ctypes.c_int]
        L.SDL_OpenJoystick.argtypes = [ctypes.c_uint32]
        L.SDL_OpenJoystick.restype = ctypes.c_void_p
        L.SDL_CloseJoystick.argtypes = [ctypes.c_void_p]
        L.SDL_UpdateJoysticks.argtypes = []
        L.SDL_GetNumJoystickAxes.argtypes = [ctypes.c_void_p]
        L.SDL_GetNumJoystickHats.argtypes = [ctypes.c_void_p]
        L.SDL_GetNumJoystickButtons.argtypes = [ctypes.c_void_p]
        L.SDL_GetJoystickAxis.argtypes = [ctypes.c_void_p, ctypes.c_int]
        L.SDL_GetJoystickAxis.restype = ctypes.c_int16
        L.SDL_GetJoystickHat.argtypes = [ctypes.c_void_p, ctypes.c_int]
        L.SDL_GetJoystickHat.restype = ctypes.c_uint8
        L.SDL_GetJoystickButton.argtypes = [ctypes.c_void_p, ctypes.c_int]
        L.SDL_GetJoystickButton.restype = ctypes.c_bool
        L.SDL_free.argtypes = [ctypes.c_void_p]
        if not L.SDL_Init(SDL_INIT_JOYSTICK):
            sys.exit("n64-input: SDL_Init(JOYSTICK) failed")
        self.joy = None
        self.guid = None

    def find_pad(self, timeout=10.0):
        """Wait for SDL to see the pad we just created, then open it."""
        deadline = time.time() + timeout
        while time.time() < deadline:
            self.lib.SDL_UpdateJoysticks()
            count = ctypes.c_int(0)
            ids = self.lib.SDL_GetJoysticks(ctypes.byref(count))
            for i in range(count.value):
                jid = ids[i]
                name = self.lib.SDL_GetJoystickNameForID(jid)
                if name and name.decode(errors="replace") == PAD_NAME:
                    buf = ctypes.create_string_buffer(64)
                    self.lib.SDL_GUIDToString(
                        self.lib.SDL_GetJoystickGUIDForID(jid), buf, 64)
                    self.guid = buf.value.decode()
                    self.joy = self.lib.SDL_OpenJoystick(jid)
                    self.lib.SDL_free(ids)
                    if not self.joy:
                        sys.exit("n64-input: SDL_OpenJoystick failed on the virtual pad")
                    return
            if ids:
                self.lib.SDL_free(ids)
            time.sleep(0.2)
        sys.exit(f"n64-input: SDL never saw a joystick named {PAD_NAME!r} — the uinput "
                 "device was created but is not being classified as a gamepad")

    def snapshot(self):
        self.lib.SDL_UpdateJoysticks()
        axes = [self.lib.SDL_GetJoystickAxis(self.joy, n)
                for n in range(self.lib.SDL_GetNumJoystickAxes(self.joy))]
        # Decomposed exactly as ares does it in ruby/input/joypad/sdl.cpp:
        # hat n becomes inputs 2n (X) and 2n+1 (Y).
        hats = []
        for n in range(self.lib.SDL_GetNumJoystickHats(self.joy)):
            state = self.lib.SDL_GetJoystickHat(self.joy, n)
            hats.append(-32767 if state & 0x08 else 32767 if state & 0x02 else 0)  # L/R
            hats.append(-32767 if state & 0x01 else 32767 if state & 0x04 else 0)  # U/D
        buttons = [int(self.lib.SDL_GetJoystickButton(self.joy, n))
                   for n in range(self.lib.SDL_GetNumJoystickButtons(self.joy))]
        return axes, hats, buttons


def probe(pad, sdl):
    """Actuate each control and record what SDL saw. Returns
    {control: "<groupID>/<inputID>[/Lo|/Hi]"}."""
    sdl.find_pad()
    pad.release_all()
    time.sleep(0.15)
    base = sdl.snapshot()
    resolved = {}
    unresolved = []

    for name in CONTROLS:
        pad.set_control(name, True)
        time.sleep(0.06)
        now = sdl.snapshot()
        pad.set_control(name, False)
        time.sleep(0.04)

        hit = None
        for group, idx in ((GROUP_AXIS, 0), (GROUP_HAT, 1), (GROUP_BUTTON, 2)):
            for i, (was, is_) in enumerate(zip(base[idx], now[idx])):
                if was == is_:
                    continue
                if group == GROUP_BUTTON:
                    hit = f"{group}/{i}"
                else:
                    hit = f"{group}/{i}/" + ("Lo" if is_ < 0 else "Hi")
                break
            if hit:
                break
        if hit:
            resolved[name] = hit
        else:
            unresolved.append(name)

    if unresolved:
        sys.exit("n64-input: SDL reported no movement for: "
                 + ", ".join(unresolved)
                 + "\nn64-input: the pad's capabilities and SDL disagree; bindings "
                   "would be silently dead, so refusing to write them.")
    return resolved


# ── The settings file ──────────────────────────────────────────────────
def render_bml(template, guid, resolved, port=1):
    ident = f"{guid}/0"  # slot 0: ares only increments it for a duplicate GUID
    out = template.replace("@PORT@", str(port))
    for name, keys in BML_KEYS.items():
        out = out.replace(f"@{name.upper()}@", f"{ident}/{resolved[name]}")
    # Comment lines are exempt: the template's own header explains the
    # @NAME@ convention and would otherwise trip this check.
    leftover = [l.strip() for l in out.splitlines()
                if not l.lstrip().startswith("//") and re.search(r"@[A-Z0-9_]+@", l)]
    if leftover:
        sys.exit("n64-input: unsubstituted placeholders in the template: "
                 + "; ".join(leftover))
    return out


def cmd_probe(args):
    pad = Pad()
    try:
        sdl = Sdl()
        resolved = probe(pad, sdl)
    finally:
        pad.close()

    tmpl_path = args.template or os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "ares-input.bml.in")
    with open(tmpl_path) as fh:
        template = fh.read()
    with open(args.bml, "w") as fh:
        fh.write(render_bml(template, sdl.guid, resolved, args.port))

    record = {"name": PAD_NAME, "guid": sdl.guid, "controls": resolved}
    if args.json:
        with open(args.json, "w") as fh:
            json.dump(record, fh, indent=2)
    print(f"n64-input: pad {PAD_NAME!r} guid {sdl.guid}")
    print(f"n64-input: wrote {args.bml} (controller port {args.port}, "
          f"{len(resolved)} controls bound)")
    return 0


# ── The script language ────────────────────────────────────────────────
# One verb per line, '#' comments, blank lines ignored:
#
#   wait 4            sleep 4 seconds
#   press start       tap (0.1 s), or `press start 0.4` to choose the hold
#   hold z 1.5        hold z for 1.5 s
#   stick 0 1 2.0     stick to (x=0, y=+1) for 2 s, then centre
#   down z / up z     hold and release across other lines
#   shot title.png    grim the ares window and print pixel statistics
#   log <text>        annotate the transcript
ALIASES = {
    "up": "dup", "down": "ddown", "left": "dleft", "right": "dright",
    "c-up": "cup", "c-down": "cdown", "c-left": "cleft", "c-right": "cright",
}


def resolve_control(word):
    name = ALIASES.get(word.lower(), word.lower())
    if name not in CONTROLS:
        sys.exit(f"n64-input: unknown control {word!r}; known: "
                 + ", ".join(sorted(set(CONTROLS) | set(ALIASES))))
    return name


def capture(out_path, geom):
    if not geom:
        print(f"n64-input:   (no --geom, skipping shot {out_path})")
        return
    try:
        subprocess.run(["grim", "-g", geom, out_path], check=True)
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"n64-input:   shot failed: {exc}", file=sys.stderr)
        return
    stats(out_path)


def stats(path):
    """The same pixel report ./dev shot prints, for the same reason: a
    320x240 console upscaled into a big mostly-dark screenshot reads as
    'black' to the eye when the picture is right there."""
    try:
        from PIL import Image
    except ImportError:
        print("n64-input:   (install pillow for pixel stats)")
        return
    from collections import Counter
    im = Image.open(path).convert("RGB")
    data = list(im.getdata())
    total = len(data)
    counts = Counter(data)
    nonblack = sum(n for c, n in counts.items() if sum(c) > 60)
    top = ", ".join("rgb%s %.1f%%" % (c, 100.0 * n / total)
                    for c, n in counts.most_common(3))
    print("n64-input:   %s %dx%d  non-black %.2f%%  [%s]"
          % (os.path.basename(path), im.size[0], im.size[1],
             100.0 * nonblack / total, top))
    if nonblack < total * 0.0005:
        print("n64-input:   WARNING: essentially empty frame")


def run_script(pad, path, geom, outdir):
    with open(path) as fh:
        lines = fh.readlines()

    for lineno, raw in enumerate(lines, 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = shlex.split(line)
        verb, rest = parts[0].lower(), parts[1:]
        where = f"{os.path.basename(path)}:{lineno}"

        if verb == "wait":
            secs = float(rest[0])
            print(f"n64-input: {where} wait {secs}")
            time.sleep(secs)
        elif verb == "log":
            print(f"n64-input: {where} — {' '.join(rest)}")
        elif verb in ("press", "hold"):
            name = resolve_control(rest[0])
            secs = float(rest[1]) if len(rest) > 1 else (0.1 if verb == "press" else 0.5)
            print(f"n64-input: {where} {verb} {name} {secs}s")
            pad.set_control(name, True)
            time.sleep(secs)
            pad.set_control(name, False)
        elif verb == "down":
            name = resolve_control(rest[0])
            print(f"n64-input: {where} down {name}")
            pad.set_control(name, True)
        elif verb == "up":
            # `up` is ambiguous with the d-pad alias on purpose-free ground:
            # with an argument that names a held control it releases it,
            # which is the only reading that makes sense next to `down`.
            name = resolve_control(rest[0])
            print(f"n64-input: {where} up {name}")
            pad.set_control(name, False)
        elif verb == "stick":
            x, y = float(rest[0]), float(rest[1])
            secs = float(rest[2]) if len(rest) > 2 else 1.0
            print(f"n64-input: {where} stick ({x}, {y}) {secs}s")
            pad.stick(x, y)
            time.sleep(secs)
            pad.stick(0.0, 0.0)
        elif verb == "release":
            print(f"n64-input: {where} release all")
            pad.release_all()
        elif verb == "shot":
            out = rest[0] if rest else f"shot-{lineno}.png"
            out = out if os.path.isabs(out) else os.path.join(outdir or ".", out)
            print(f"n64-input: {where} shot {out}")
            capture(out, geom)
        else:
            sys.exit(f"n64-input: {where}: unknown verb {verb!r}")


def cmd_run(args):
    pad = Pad()
    try:
        sdl = Sdl()
        sdl.find_pad()
        if args.json:
            with open(args.json) as fh:
                record = json.load(fh)
            if record.get("guid") != sdl.guid:
                sys.exit(
                    f"n64-input: pad GUID changed since the bindings were written "
                    f"({record.get('guid')} -> {sdl.guid}). ares is bound to a device "
                    "that no longer exists, so no input would reach the ROM.")
        if args.outdir:
            os.makedirs(args.outdir, exist_ok=True)
        run_script(pad, args.script, args.geom, args.outdir)
    finally:
        pad.close()
    return 0


def cmd_serve(args):
    """Hold the pad open across the whole ares session, then run the script.

    This is `probe` and `run` in ONE process, and the single process is the
    entire point. ares resolves each binding string to a live device when
    its settings load (InputMapping::bind matches the assignment's device
    identifier against the currently-connected devices) — a binding naming
    a device that is not plugged in resolves to nothing and is skipped for
    the rest of the session as "unbound".

    Creating the pad, probing it, closing it, starting ares, and creating
    it again is therefore a run where every button is silently dead. That
    is exactly what the first version of this tool did, and it is
    indistinguishable from a game that ignores input: the capture ran to
    completion, every screen was captured, and every one of them was the
    attract reel.

    So: create once, before ares, and hold it until the script is done.
    """
    pad = Pad()
    try:
        sdl = Sdl()
        resolved = probe(pad, sdl)

        tmpl_path = args.template or os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "ares-input.bml.in")
        with open(tmpl_path) as fh:
            template = fh.read()
        with open(args.bml, "w") as fh:
            fh.write(render_bml(template, sdl.guid, resolved, args.port))
        print(f"n64-input: pad {PAD_NAME!r} guid {sdl.guid}, "
              f"{len(resolved)} controls bound -> {args.bml}")

        # Tell the driver the bindings are on disk and the pad is live, so
        # it can start ares with both already true.
        with open(args.ready, "w") as fh:
            fh.write(sdl.guid + "\n")

        # Wait for the driver to report the window geometry. Until then
        # ares is still booting and nothing typed at it would land.
        deadline = time.time() + args.start_timeout
        while not os.path.exists(args.start):
            if time.time() > deadline:
                sys.exit("n64-input: the driver never reported an ares window; "
                         "giving up rather than typing at nothing")
            time.sleep(0.2)
        with open(args.start) as fh:
            geom = fh.read().strip()

        # The pad has been present the whole time, but ares only re-binds
        # when its device LIST changes (InputManager::poll). Nudging every
        # control once here is both a wake-up and a check: if these do not
        # reach the ROM, nothing later will either.
        for name in ("a", "b", "start"):
            pad.set_control(name, True)
            time.sleep(0.03)
            pad.set_control(name, False)
            time.sleep(0.03)

        if args.outdir:
            os.makedirs(args.outdir, exist_ok=True)
        run_script(pad, args.script, geom, args.outdir)
    finally:
        pad.close()
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("probe", help="create the pad, resolve its SDL indices, "
                                     "write an ares settings file")
    p.add_argument("--bml", required=True)
    p.add_argument("--json")
    p.add_argument("--template")
    p.add_argument("--port", type=int, default=1)
    p.set_defaults(func=cmd_probe)

    p = sub.add_parser("run", help="create the pad and execute an input script")
    p.add_argument("script")
    p.add_argument("--json", help="pad record from `probe`, to assert the GUID matches")
    p.add_argument("--geom", default=os.environ.get("KILN_DRIVE_GEOM", ""),
                   help="grim geometry of the ares window, \"X,Y WxH\"")
    p.add_argument("--outdir", default=os.environ.get("KILN_DRIVE_OUTDIR", ""))
    p.set_defaults(func=cmd_run)

    p = sub.add_parser("serve", help="hold the pad open across the whole ares "
                                     "session: probe, write bindings, wait, run")
    p.add_argument("script")
    p.add_argument("--bml", required=True)
    p.add_argument("--ready", required=True,
                   help="written once the bindings are on disk and the pad is live")
    p.add_argument("--start", required=True,
                   help="polled for; its contents are the ares window geometry")
    p.add_argument("--template")
    p.add_argument("--port", type=int, default=1)
    p.add_argument("--outdir", default=os.environ.get("KILN_DRIVE_OUTDIR", ""))
    p.add_argument("--start-timeout", type=float, default=180.0)
    p.set_defaults(func=cmd_serve)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
